# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Post-decryption analytics + deterministic story engine (Stage 6).

Pure Python, no encryption. Consumes the decrypted aggregate dict
({'cat','week','income'}) produced by the Stage 5 pipeline (or the plaintext
oracle / twin, which share the same shape) plus calendar-month completeness
labels, and emits a JSON-serializable result contract for the future frontend.
"""

from . import config, schema, monthly, timeline, story, build
from .build import build_result, validate_result
from .config import Config, DEFAULT

__all__ = ["config", "schema", "monthly", "timeline", "story", "build",
           "build_result", "validate_result", "Config", "DEFAULT"]
