# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Top-level assembly of the JSON-serializable analytics result contract.

build_result(agg, month_labels, cfg) -> the full result object the future
frontend consumes: categories, monthly records, timeline, comparisons, stories,
limitations, and privacy metadata. Output is sanitized to contain no NaN/Infinity.
"""

from reference import taxonomy
from .config import DEFAULT
from .monthly import build_month_record
from . import timeline as TL
from . import story as ST
from .schema import (SCHEMA_VERSION, default_limitations, privacy_metadata,
                     sanitize, find_non_finite)


def _categories():
    return [{"index": i, "name": n,
             "group": taxonomy.CATEGORIES[i][1],
             "fixed": taxonomy.CATEGORIES[i][2],
             "housing": taxonomy.CATEGORIES[i][3]}
            for i, n in enumerate(taxonomy.CATEGORY_NAMES)]


def build_result(agg, month_labels, cfg=DEFAULT, selected_pairs=None):
    """agg: decrypted aggregate dict {'cat','week','income'}.
    month_labels: list from reference.completeness.label_months().
    selected_pairs: optional list of (gm_a, gm_b) to compare explicitly.
    """
    records = [build_month_record(agg, label, cfg) for label in month_labels]
    by_gm = {r["global_m"]: r for r in records}
    complete = [r for r in records if r["complete"]]

    tl = {
        "trends": TL.trends(records, cfg),
        "month_over_month": TL.month_over_month(records, cfg),
        "rolling_baselines": TL.rolling_baselines(records, cfg),
    }

    # comparisons: explicit selected pairs + latest complete month vs its baseline
    pairwise = []
    for a, b in (selected_pairs or []):
        if a in by_gm and b in by_gm:
            pairwise.append(TL.compare_months(by_gm[a], by_gm[b], cfg))
    vs_baseline = []
    if len(complete) >= 2:
        latest = complete[-1]
        prior = complete[:-1]
        if cfg.rolling_window > 0:
            prior = prior[-cfg.rolling_window:]
        baseline = TL.build_baseline(prior, cfg)
        vs_baseline.append(TL.compare_to_baseline(latest, baseline, cfg))

    # stories: latest month-over-month, and latest vs baseline
    stories = []
    if tl["month_over_month"]:
        stories += ST.stories_for_comparison(
            tl["month_over_month"][-1],
            f"month-over-month ({tl['month_over_month'][-1]['to']})", cfg)
    if vs_baseline and vs_baseline[0].get("cosine"):
        stories += ST.stories_for_comparison(
            vs_baseline[0], f"vs baseline ({vs_baseline[0]['to']})", cfg)

    result = {
        "schema_version": SCHEMA_VERSION,
        "privacy": privacy_metadata(),
        "limitations": default_limitations(cfg),
        "config": {"eps_denom": cfg.eps_denom, "income_weight": cfg.income_weight,
                   "stability_pp": cfg.stability_pp, "stability_rel": cfg.stability_rel,
                   "min_meaningful_pp": cfg.min_meaningful_pp,
                   "min_meaningful_rel": cfg.min_meaningful_rel,
                   "rolling_window": cfg.rolling_window, "top_k_changes": cfg.top_k_changes},
        "categories": _categories(),
        "months": records,
        "timeline": tl,
        "comparisons": {"pairwise": pairwise, "vs_baseline": vs_baseline},
        "stories": stories,
        "counts": {"months_total": len(records), "months_complete": len(complete),
                   "months_partial": len(records) - len(complete)},
    }
    return sanitize(result)


def validate_result(result):
    """Return a list of JSON paths carrying NaN/Infinity (should be empty)."""
    return find_non_finite(result)
