# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Explicit, deterministic tolerances for the analytics + story engine.

Every threshold the story engine and metric guards use lives here, so behavior is
reproducible and auditable. No hidden magic numbers elsewhere.
"""

from dataclasses import dataclass


@dataclass(frozen=True)
class Config:
    eps_denom: float = 1.0        # ratio denominators below this (currency) are undefined
    income_weight: float = 0.15   # low weight of the income feature in similarity
    stability_pp: float = 1.0     # |share change| < this (pp) => "stable" ...
    stability_rel: float = 0.05   # ... AND relative change < this
    min_meaningful_pp: float = 1.0    # ranking/headline: ignore share moves below (pp)
    min_meaningful_rel: float = 0.05  # ranking/headline: ignore relative moves below
    rolling_window: int = 0       # 0 = all prior complete months; else trailing N
    top_k_changes: int = 3        # how many category changes to surface
    cv_mean_floor: float = 1e-6   # floor for coefficient-of-variation denominator
    dominant_driver_floor: float = 0.02  # below this, "no dominant driver"


DEFAULT = Config()
