# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Per-month analytics records: raw aggregates preserved, normalized metrics
exposed separately. Consumes the decrypted aggregate dict (same shape as the
plaintext oracle / twin): agg['cat'][(gm,c)], agg['week'][(gm,w)], agg['income'][gm].
"""

import math

from reference import taxonomy
from .config import DEFAULT
from .schema import guarded, guarded_value


def month_vectors(agg, gm):
    cat = [agg["cat"].get((gm, c), 0.0) for c in range(taxonomy.N_CATEGORIES)]
    week = [agg["week"].get((gm, w), 0.0) for w in range(5)]
    income = agg["income"].get(gm, 0.0)
    return cat, week, income


def _group_sum(cat_vec, idx_set):
    return sum(cat_vec[i] for i in idx_set)


def share_vector(cat_vec, eps):
    """Category shares (fractions) or None if total spend < eps."""
    total = sum(cat_vec)
    if total < eps:
        return None
    return [c / total for c in cat_vec]


def weekly_variability(week_vec, days_in_month, cfg=DEFAULT):
    """Rhythm over the 5 day-bins: raw stats plus per-day-normalized (length-fair).

    Bin day-counts: [7,7,7,7, days_in_month-28]; the last bin may be 0 (Feb) and
    is then excluded from the per-day view.
    """
    n = len(week_vec)
    mean = sum(week_vec) / n
    var = sum((w - mean) ** 2 for w in week_vec) / n
    raw = {"mean": mean, "variance": var, "std": math.sqrt(var)}

    bin_days = [7, 7, 7, 7, max(0, days_in_month - 28)]
    rates = [week_vec[i] / bin_days[i] for i in range(n) if bin_days[i] > 0]
    if rates:
        m = sum(rates) / len(rates)
        v = sum((r - m) ** 2 for r in rates) / len(rates)
        cv = guarded(math.sqrt(v), m, cfg.cv_mean_floor)  # coefficient of variation
        per_day = {"mean": m, "variance": v, "std": math.sqrt(v), "cv": cv}
    else:
        per_day = {"mean": None, "variance": None, "std": None,
                   "cv": guarded_value(None, "no bins with days")}
    return {"raw": raw, "per_day": per_day}


def concentration_hhi(cat_vec, eps):
    """True HHI over category shares: sum(share_c^2) in [1/N, 1]. Undefined if
    total spend < eps. Also a normalized form (0 = uniform, 1 = single category).
    """
    total = sum(cat_vec)
    if total < eps:
        return {"value": None, "defined": False, "reason": "total_spend<eps",
                "normalized": None}
    shares = [c / total for c in cat_vec]
    hhi = sum(s * s for s in shares)
    n = taxonomy.N_CATEGORIES
    normalized = (hhi - 1.0 / n) / (1.0 - 1.0 / n)  # min HHI is 1/N (uniform)
    return {"value": hhi, "defined": True, "reason": None, "normalized": normalized}


def build_month_record(agg, label, cfg=DEFAULT):
    """label is a dict from reference.completeness.label_months()."""
    gm = label["global_m"]
    cat, week, income = month_vectors(agg, gm)
    total_spend = sum(cat)
    fixed = _group_sum(cat, taxonomy.FIXED_IDX)
    essential = _group_sum(cat, taxonomy.ESSENTIAL_IDX)
    discretionary = _group_sum(cat, taxonomy.DISCRETIONARY_IDX)
    housing = _group_sum(cat, taxonomy.HOUSING_IDX)
    net = income - total_spend
    shares = share_vector(cat, cfg.eps_denom)

    metrics = {
        "total_spending": total_spend,
        "total_income": income,
        "net_cash_flow": net,
        "cash_flow_index": guarded(net, income + total_spend, cfg.eps_denom),
        "savings_rate": guarded(net, income, cfg.eps_denom),
        "category_shares": shares if shares is not None else [None] * taxonomy.N_CATEGORIES,
        "fixed_cost_load": {"of_income": guarded(fixed, income, cfg.eps_denom),
                            "of_spend": guarded(fixed, total_spend, cfg.eps_denom)},
        "essential_ratio": {"of_income": guarded(essential, income, cfg.eps_denom),
                            "of_spend": guarded(essential, total_spend, cfg.eps_denom)},
        "discretionary_ratio": {"of_income": guarded(discretionary, income, cfg.eps_denom),
                                "of_spend": guarded(discretionary, total_spend, cfg.eps_denom)},
        "housing_ratio": {"of_income": guarded(housing, income, cfg.eps_denom),
                          "of_spend": guarded(housing, total_spend, cfg.eps_denom)},
        "weekly_variability": weekly_variability(week, label["days_in_month"], cfg),
        "concentration_hhi": concentration_hhi(cat, cfg.eps_denom),
    }
    return {
        "global_m": gm,
        "year": label["year"],
        "month": label["month"],
        "label": f"{label['year']:04d}-{label['month']:02d}",
        "complete": label["complete"],
        "coverage_days": label["coverage_days"],
        "days_in_month": label["days_in_month"],
        # raw decrypted aggregates preserved internally
        "raw": {"category_sums": cat, "weekly_sums": week, "income": income,
                "total_spending": total_spend},
        "metrics": metrics,
    }
