# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Result-contract helpers: guarded values, sanitization, privacy + limitations.

Everything the analytics layer emits is a plain JSON-serializable structure
(dict / list / str / int / float / bool / None). Guarded ratios are represented
uniformly as {"value", "defined", "reason"} so the frontend never has to handle
NaN, Infinity, or divide-by-zero.
"""

import math

from reference.errors import safe_ratio

SCHEMA_VERSION = "1.0"


def guarded(numerator, denominator, eps):
    """Uniform guarded-ratio object."""
    value, reason = safe_ratio(numerator, denominator, eps)
    return {"value": value, "defined": value is not None, "reason": reason}


def guarded_value(value, reason=None):
    """Wrap a possibly-undefined non-ratio scalar in the same shape."""
    if value is None or not math.isfinite(value):
        return {"value": None, "defined": False, "reason": reason or "undefined"}
    return {"value": value, "defined": True, "reason": None}


def find_non_finite(obj, path="$"):
    """Return a list of JSON paths whose float value is NaN or Infinity."""
    bad = []
    if isinstance(obj, dict):
        for k, v in obj.items():
            bad += find_non_finite(v, f"{path}.{k}")
    elif isinstance(obj, (list, tuple)):
        for i, v in enumerate(obj):
            bad += find_non_finite(v, f"{path}[{i}]")
    elif isinstance(obj, float):
        if not math.isfinite(obj):
            bad.append(path)
    return bad


def sanitize(obj):
    """Recursively replace any non-finite float with None (belt-and-suspenders)."""
    if isinstance(obj, dict):
        return {k: sanitize(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [sanitize(v) for v in obj]
    if isinstance(obj, float) and not math.isfinite(obj):
        return None
    return obj


def privacy_metadata():
    return {
        "computed_locally": True,
        "server_saw_plaintext": False,
        "secret_key_leaves_device": False,
        "scheme": "CKKS",
        "ring_dimension": 65536,
        "security_level": "HEStd_128_classic",
        "bootstrapping": False,
        "note": ("Monthly aggregates were computed by the server homomorphically on "
                 "encrypted data (blind linear aggregation) and decrypted only on "
                 "the user's device. All ratios, similarity, trends, and narratives "
                 "below are derived locally from those decrypted aggregates."),
    }


def default_limitations(cfg):
    return [
        "Aggregates are CKKS-approximate; values carry small numerical error "
        "(measured ~1e-6 currency units in Stage 5), not exact to the cent.",
        "Partial calendar months are labeled and browsable but excluded from "
        "baselines and trend claims by default; they are never silently prorated.",
        f"Ratios with a denominator below {cfg.eps_denom} currency units are "
        "reported as undefined rather than as unstable or infinite values.",
        "Weekly rhythm uses fixed day-bins (1-7, 8-14, 15-21, 22-28, 29-end); the "
        "last bin is variable length and is per-day normalized using public "
        "day-counts.",
        "Narratives describe measured changes only; they do not infer causes, "
        "motives, life events, or give financial advice.",
        "The encryption keeps your values confidential from a semi-honest server; "
        "it does not verify that the server computed correctly — a wrong or altered "
        "result would not be detected by the encryption itself.",
    ]
