# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Deterministic local story engine.

Generates headlines and insight cards from explicit rules + templates over a
comparison object. It ONLY describes measured changes: no motives, emotions,
causes, life events, or financial advice. All ranking/stability use the explicit
tolerances in Config. Output is deterministic (stable sorts, no randomness).
"""

from reference import taxonomy
from .config import DEFAULT

N = taxonomy.N_CATEGORIES


# ---- formatting helpers (factual, numeric) --------------------------------
def _pct(x):
    return f"{x * 100:.1f}%"


def _pp(x):
    return f"{x:+.1f} pp"


def _rel_word(x):
    return "rose" if x > 0 else "fell"


def _relval(node):
    return node["rel"]["value"] if node and node.get("rel", {}).get("defined") else None


def _dval(node):
    return node["value"] if node and node.get("defined") else None


# ---- ranking / stability --------------------------------------------------
def rank_category_changes(comp, cfg=DEFAULT):
    pp = comp.get("category_pp_deltas")
    if pp is None:
        return []
    sf, st = comp.get("shares_from"), comp.get("shares_to")
    items = []
    for c in range(N):
        if abs(pp[c]) >= cfg.min_meaningful_pp:
            items.append({"index": c, "category": taxonomy.CATEGORY_NAMES[c], "pp": pp[c],
                          "from_share": (sf[c] if sf else None),
                          "to_share": (st[c] if st else None)})
    items.sort(key=lambda x: (-abs(x["pp"]), x["index"]))
    return items[: cfg.top_k_changes]


def stable_categories(comp, cfg=DEFAULT):
    pp = comp.get("category_pp_deltas")
    sf, st = comp.get("shares_from"), comp.get("shares_to")
    if pp is None or sf is None or st is None:
        return []
    out = []
    for c in range(N):
        change = abs(st[c] - sf[c])
        rel = change / sf[c] if sf[c] > 1e-9 else (0.0 if change < 1e-9 else 1.0)
        if abs(pp[c]) < cfg.stability_pp and rel < cfg.stability_rel:
            out.append(taxonomy.CATEGORY_NAMES[c])
    return out


# ---- source-of-change decomposition (descriptive, NOT causal) -------------
def source_of_change(comp, cfg=DEFAULT):
    rel_total = _relval(comp.get("total_spending"))
    rel_income = _relval(comp.get("total_income"))
    d_cashflow = _dval(comp.get("cash_flow_index_delta"))
    d_fixed = _dval(comp.get("fixed_cost_load_spend_delta"))
    d_rhythm = _dval(comp.get("rhythm_cv_delta"))
    pp = comp.get("category_pp_deltas")
    mix = 0.5 * sum(abs(p) / 100.0 for p in pp) if pp else 0.0  # total variation
    factors = {
        "total spending level": abs(rel_total) if rel_total is not None else 0.0,
        "income / cash flow": max(abs(rel_income) if rel_income is not None else 0.0,
                                  abs(d_cashflow) if d_cashflow is not None else 0.0),
        "category mix": mix,
        "fixed-cost load": abs(d_fixed) if d_fixed is not None else 0.0,
        "spending rhythm": abs(d_rhythm) if d_rhythm is not None else 0.0,
    }
    driver = max(factors, key=lambda k: (factors[k],))
    if factors[driver] < cfg.dominant_driver_floor:
        title = "No dominant driver — overall change was small"
        detail = "All measured components changed by less than the reporting floor."
    else:
        title = f"Change driven mainly by {driver}"
        detail = (f"Largest measured component: {driver} "
                  f"({factors[driver]:.3f}). This is the largest normalized "
                  f"component of change, described factually — not a stated cause.")
    return {"type": "insight", "kind": "source_of_change", "title": title,
            "detail": detail, "evidence": {"factors": factors, "driver": driver}}


# ---- headline -------------------------------------------------------------
def headline_card(comp, cfg=DEFAULT):
    ranked = rank_category_changes(comp, cfg)
    rel_total = _relval(comp.get("total_spending"))
    rel_income = _relval(comp.get("total_income"))
    d_cashflow = _dval(comp.get("cash_flow_index_delta"))
    d_fixed = _dval(comp.get("fixed_cost_load_spend_delta"))
    d_rhythm = _dval(comp.get("rhythm_cv_delta"))
    ref = comp.get("from", "the baseline")

    cands = []  # (salience, priority, title, detail)
    if rel_total is not None and abs(rel_total) >= cfg.min_meaningful_rel:
        cands.append((abs(rel_total), 0,
                      f"Total spending {_rel_word(rel_total)} {_pct(abs(rel_total))}",
                      f"Total spending {_rel_word(rel_total)} {_pct(abs(rel_total))} vs {ref}."))
    if ranked:
        top = ranked[0]
        cands.append((abs(top["pp"]) / 100.0, 1,
                      f"{top['category']} share {_rel_word(top['pp'])} {_pp(top['pp'])}",
                      f"{top['category']} share {_rel_word(top['pp'])} by {_pp(top['pp'])} vs {ref}."))
    if rel_income is not None and abs(rel_income) >= cfg.min_meaningful_rel:
        cands.append((abs(rel_income), 2,
                      f"Income {_rel_word(rel_income)} {_pct(abs(rel_income))}",
                      f"Income {_rel_word(rel_income)} {_pct(abs(rel_income))} vs {ref}."))
    if d_cashflow is not None and abs(d_cashflow) >= 0.05:
        cands.append((abs(d_cashflow), 3,
                      f"Cash-flow index {_rel_word(d_cashflow)} {d_cashflow:+.2f}",
                      f"The cash-flow index moved {d_cashflow:+.2f} vs {ref}."))
    if d_fixed is not None and abs(d_fixed) >= cfg.min_meaningful_rel:
        cands.append((abs(d_fixed), 4,
                      f"Fixed-cost load {_rel_word(d_fixed)} {_pp(d_fixed * 100)}",
                      f"Fixed-cost load (of spend) moved {_pp(d_fixed * 100)} vs {ref}."))
    if d_rhythm is not None and abs(d_rhythm) >= cfg.min_meaningful_rel:
        cands.append((abs(d_rhythm), 5,
                      f"Weekly rhythm {_rel_word(d_rhythm)} {d_rhythm:+.3f}",
                      f"Weekly spending variability moved {d_rhythm:+.3f} vs {ref}."))

    if not cands:
        return {"type": "headline", "kind": "stable",
                "title": f"Spending was stable versus {ref}",
                "detail": "No measured change exceeded the reporting thresholds.",
                "evidence": {}}
    cands.sort(key=lambda x: (-x[0], x[1]))
    sal, _, title, detail = cands[0]
    return {"type": "headline", "kind": "primary_change", "title": title,
            "detail": detail, "evidence": {"salience": sal}}


def category_change_cards(comp, cfg=DEFAULT):
    cards = []
    for it in rank_category_changes(comp, cfg):
        fs = it["from_share"]
        ts = it["to_share"]
        span = (f" ({_pct(fs)} to {_pct(ts)})" if fs is not None and ts is not None else "")
        cards.append({"type": "insight", "kind": "category_change",
                      "title": f"{it['category']} {_rel_word(it['pp'])} {_pp(it['pp'])}",
                      "detail": f"{it['category']} share {_rel_word(it['pp'])} "
                                f"{_pp(it['pp'])}{span}.",
                      "evidence": {"category": it["category"], "pp": it["pp"],
                                   "from_share": fs, "to_share": ts}})
    return cards


def stable_card(comp, cfg=DEFAULT):
    stable = stable_categories(comp, cfg)
    if not stable:
        return None
    return {"type": "insight", "kind": "stable_categories",
            "title": f"{len(stable)} categories stable",
            "detail": "Stable (within tolerance): " + ", ".join(stable) + ".",
            "evidence": {"categories": stable,
                         "tolerance_pp": cfg.stability_pp,
                         "tolerance_rel": cfg.stability_rel}}


def stories_for_comparison(comp, context_label, cfg=DEFAULT):
    cards = [headline_card(comp, cfg)]
    cards += category_change_cards(comp, cfg)
    s = stable_card(comp, cfg)
    if s:
        cards.append(s)
    cards.append(source_of_change(comp, cfg))
    caveat = ""
    if comp.get("involves_partial"):
        caveat = " (one side is a partial month — interpret with care)"
    for card in cards:
        card["context"] = context_label + caveat
    return cards
