# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Timeline analytics: month-over-month, trends, rolling baselines, and
pairwise / month-vs-baseline comparisons (cosine, Euclidean, per-category pp).

Partial months are excluded from baselines and trends by default. Comparisons
may involve a partial month but are flagged so the story engine can caveat them.
"""

import math

from reference import taxonomy
from .config import DEFAULT
from .monthly import month_vectors, share_vector
from .schema import guarded, guarded_value

N = taxonomy.N_CATEGORIES


def _shares_from_raw(rec, eps):
    return share_vector(rec["raw"]["category_sums"], eps)


def _metric_value(rec, path):
    """Fetch a possibly-guarded scalar metric by dotted path; return float|None."""
    node = rec["metrics"]
    for p in path.split("."):
        node = node[p]
    if isinstance(node, dict) and "value" in node:
        return node["value"]
    return node


def compare_feature(shares_a, inc_a, shares_b, inc_b, cfg=DEFAULT):
    """Cosine, Euclidean, and per-category pp deltas over the augmented feature
    vector (shares + one low-weight, cross-period-normalized income feature)."""
    if shares_a is None or shares_b is None:
        return {"cosine": guarded_value(None, "a zero-spend month"),
                "euclidean": guarded_value(None, "a zero-spend month"),
                "category_pp_deltas": None}
    denom = max(inc_a, inc_b)
    fa = inc_a / denom if denom >= cfg.eps_denom else 0.0
    fb = inc_b / denom if denom >= cfg.eps_denom else 0.0
    va = list(shares_a) + [cfg.income_weight * fa]
    vb = list(shares_b) + [cfg.income_weight * fb]
    dot = sum(x * y for x, y in zip(va, vb))
    na = math.sqrt(sum(x * x for x in va))
    nb = math.sqrt(sum(y * y for y in vb))
    cosine = (guarded_value(dot / (na * nb)) if na > 1e-12 and nb > 1e-12
              else guarded_value(None, "zero-norm vector"))
    euclidean = guarded_value(math.sqrt(sum((x - y) ** 2 for x, y in zip(va, vb))))
    pp = [(shares_b[c] - shares_a[c]) * 100.0 for c in range(N)]
    return {"cosine": cosine, "euclidean": euclidean, "category_pp_deltas": pp}


def _rel(a, b, eps):
    """Relative change (b-a)/a, guarded."""
    return guarded(b - a, a, eps)


def compare_months(rec_a, rec_b, cfg=DEFAULT):
    ra, rb = rec_a["raw"], rec_b["raw"]
    sa = _shares_from_raw(rec_a, cfg.eps_denom)
    sb = _shares_from_raw(rec_b, cfg.eps_denom)
    feat = compare_feature(sa, ra["income"], sb, rb["income"], cfg)

    def dmetric(path):
        av, bv = _metric_value(rec_a, path), _metric_value(rec_b, path)
        if av is None or bv is None:
            return guarded_value(None, "undefined in one month")
        return guarded_value(bv - av)

    return {
        "from": rec_a["label"], "to": rec_b["label"],
        "from_gm": rec_a["global_m"], "to_gm": rec_b["global_m"],
        "involves_partial": (not rec_a["complete"]) or (not rec_b["complete"]),
        "total_spending": {"from": ra["total_spending"], "to": rb["total_spending"],
                           "abs": rb["total_spending"] - ra["total_spending"],
                           "rel": _rel(ra["total_spending"], rb["total_spending"], cfg.eps_denom)},
        "total_income": {"from": ra["income"], "to": rb["income"],
                         "abs": rb["income"] - ra["income"],
                         "rel": _rel(ra["income"], rb["income"], cfg.eps_denom)},
        "net_cash_flow_abs": rb["income"] - rb["total_spending"] - (ra["income"] - ra["total_spending"]),
        "cash_flow_index_delta": dmetric("cash_flow_index"),
        "savings_rate_delta": dmetric("savings_rate"),
        "fixed_cost_load_spend_delta": dmetric("fixed_cost_load.of_spend"),
        "discretionary_ratio_spend_delta": dmetric("discretionary_ratio.of_spend"),
        "hhi_delta": dmetric("concentration_hhi"),
        "rhythm_cv_delta": dmetric("weekly_variability.per_day.cv"),
        "cosine": feat["cosine"], "euclidean": feat["euclidean"],
        "category_pp_deltas": feat["category_pp_deltas"],
        "shares_from": sa, "shares_to": sb,
    }


def build_baseline(window_records, cfg=DEFAULT):
    """Mean share vector + mean income/total over complete months in the window."""
    usable = []
    for rec in window_records:
        if not rec["complete"]:
            continue
        s = _shares_from_raw(rec, cfg.eps_denom)
        if s is not None:
            usable.append((rec, s))
    if not usable:
        return None
    n = len(usable)
    share_mean = [sum(s[c] for _, s in usable) / n for c in range(N)]
    share_std = [math.sqrt(sum((s[c] - share_mean[c]) ** 2 for _, s in usable) / n)
                 for c in range(N)]
    mean_income = sum(rec["raw"]["income"] for rec, _ in usable) / n
    mean_total = sum(rec["raw"]["total_spending"] for rec, _ in usable) / n
    return {"months_used": n,
            "gms_used": [rec["global_m"] for rec, _ in usable],
            "share_vector": share_mean, "share_std": share_std,
            "mean_income": mean_income, "mean_total_spending": mean_total}


def rolling_baselines(records, cfg=DEFAULT):
    """For each complete month, a baseline over prior complete months (window)."""
    complete = [r for r in records if r["complete"]]
    out = []
    for i, rec in enumerate(complete):
        prior = complete[:i]
        if cfg.rolling_window > 0:
            prior = prior[-cfg.rolling_window:]
        baseline = build_baseline(prior, cfg)
        out.append({"global_m": rec["global_m"], "label": rec["label"],
                    "baseline": baseline})
    return out


def compare_to_baseline(rec, baseline, cfg=DEFAULT):
    if baseline is None:
        return {"to": rec["label"], "baseline_months": 0,
                "note": "no complete prior months for a baseline"}
    s = _shares_from_raw(rec, cfg.eps_denom)
    feat = compare_feature(baseline["share_vector"], baseline["mean_income"],
                           s, rec["raw"]["income"], cfg)
    return {
        "to": rec["label"], "to_gm": rec["global_m"],
        "baseline_months": baseline["months_used"],
        "baseline_gms": baseline["gms_used"],
        "involves_partial": not rec["complete"],
        "total_spending": {"baseline": baseline["mean_total_spending"],
                           "to": rec["raw"]["total_spending"],
                           "rel": _rel(baseline["mean_total_spending"],
                                       rec["raw"]["total_spending"], cfg.eps_denom)},
        "total_income": {"baseline": baseline["mean_income"], "to": rec["raw"]["income"],
                         "rel": _rel(baseline["mean_income"], rec["raw"]["income"], cfg.eps_denom)},
        "cosine": feat["cosine"], "euclidean": feat["euclidean"],
        "category_pp_deltas": feat["category_pp_deltas"],  # to - baseline
        "shares_from": baseline["share_vector"], "shares_to": s,
    }


_TREND_METRICS = [
    ("total_spending", "total_spending"),
    ("total_income", "total_income"),
    ("net_cash_flow", "net_cash_flow"),
    ("savings_rate", "savings_rate"),
    ("cash_flow_index", "cash_flow_index"),
    ("fixed_cost_load_of_spend", "fixed_cost_load.of_spend"),
    ("discretionary_ratio_of_spend", "discretionary_ratio.of_spend"),
    ("essential_ratio_of_spend", "essential_ratio.of_spend"),
    ("housing_ratio_of_spend", "housing_ratio.of_spend"),
    ("concentration_hhi", "concentration_hhi"),
    ("rhythm_cv", "weekly_variability.per_day.cv"),
]


def trends(records, cfg=DEFAULT):
    """Series + direction for each scalar metric across COMPLETE months only."""
    complete = [r for r in records if r["complete"]]
    out = {}
    for name, path in _TREND_METRICS:
        series = [{"global_m": r["global_m"], "label": r["label"],
                   "value": _metric_value(r, path)} for r in complete]
        defined = [p["value"] for p in series if p["value"] is not None]
        if len(defined) >= 2:
            first, last = defined[0], defined[-1]
            change = last - first
            scale = max(abs(first), abs(last), 1e-9)
            if abs(change) / scale < cfg.min_meaningful_rel:
                direction = "flat"
            else:
                direction = "increasing" if change > 0 else "decreasing"
            summary = {"first": first, "last": last, "total_change": change,
                       "direction": direction, "n_points": len(defined)}
        else:
            summary = {"first": None, "last": None, "total_change": None,
                       "direction": "insufficient_data", "n_points": len(defined)}
        out[name] = {"series": series, "summary": summary}
    return out


def month_over_month(records, cfg=DEFAULT):
    complete = [r for r in records if r["complete"]]
    return [compare_months(complete[i - 1], complete[i], cfg)
            for i in range(1, len(complete))]
