# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Build synthetic decrypted-aggregate dicts + month labels for analytics tests."""

import calendar

from reference import taxonomy


def make_agg(specs):
    """specs: list of per-month dicts, each with:
        year, month, cat={name: amount}, income=amount,
        optional week=[5 floats], complete=bool, coverage_days=int.
    Returns (agg, labels) with global_m = list index.
    """
    agg = {"cat": {}, "week": {}, "income": {}}
    labels = []
    for gm, s in enumerate(specs):
        total = 0.0
        for name, amt in s.get("cat", {}).items():
            agg["cat"][(gm, taxonomy.category_index(name))] = amt
            total += amt
        y, m = s["year"], s["month"]
        dim = calendar.monthrange(y, m)[1]
        # Default weekly distribution = even PER DAY (realistic; keeps per-day rhythm
        # cv = 0 regardless of month length). Bin day-counts: [7,7,7,7, dim-28].
        bin_days = [7, 7, 7, 7, max(0, dim - 28)]
        week = s.get("week", [total * bd / dim for bd in bin_days])
        for w in range(5):
            agg["week"][(gm, w)] = week[w]
        agg["income"][gm] = s.get("income", 0.0)
        complete = s.get("complete", True)
        labels.append({"global_m": gm, "year": y, "month": m, "complete": complete,
                       "coverage_days": s.get("coverage_days", dim if complete else dim // 2),
                       "days_in_month": dim})
    return agg, labels


def month(year, month_, cat, income, week=None, complete=True, coverage_days=None):
    d = {"year": year, "month": month_, "cat": cat, "income": income, "complete": complete}
    if week is not None:
        d["week"] = week
    if coverage_days is not None:
        d["coverage_days"] = coverage_days
    return d
