# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Shared test helpers."""

from reference.errors import assert_close


def compare_aggregates(a, b, abs_tol=1e-3, rel_tol=1e-9):
    """Assert two agg dicts ({'cat','week','income'}) agree over the union of keys."""
    for stream in ("cat", "week", "income"):
        keys = set(a[stream]) | set(b[stream])
        for k in keys:
            av = a[stream].get(k, 0.0)
            bv = b[stream].get(k, 0.0)
            assert_close(av, bv, abs_tol=abs_tol, rel_tol=rel_tol,
                         msg=f"stream={stream} key={k}")


def stream_total(agg, stream):
    return sum(agg[stream].values())
