# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Timeline: comparisons, trends, rolling baselines; identical/different/
income-only/expense-only/category-mix scenarios; partial-month exclusion."""

import math

from analytics.monthly import build_month_record
from analytics import timeline as TL
from tests._analytics_helpers import make_agg, month

APPROX = lambda a, b, t=1e-9: math.isclose(a, b, rel_tol=t, abs_tol=t)


def _records(specs):
    agg, labels = make_agg(specs)
    return [build_month_record(agg, lb) for lb in labels]


def test_identical_months_cosine_one_distance_zero():
    recs = _records([month(2024, 1, {"Groceries": 500.0, "Dining": 300.0}, 3000.0),
                     month(2024, 2, {"Groceries": 500.0, "Dining": 300.0}, 3000.0)])
    c = TL.compare_months(recs[0], recs[1])
    assert APPROX(c["cosine"]["value"], 1.0, 1e-6)
    assert APPROX(c["euclidean"]["value"], 0.0, 1e-6)
    assert all(abs(pp) < 1e-9 for pp in c["category_pp_deltas"])
    assert APPROX(c["total_spending"]["rel"]["value"], 0.0)


def test_radically_different_months():
    recs = _records([month(2024, 1, {"Groceries": 800.0}, 3000.0),
                     month(2024, 2, {"Entertainment": 800.0}, 3000.0)])
    c = TL.compare_months(recs[0], recs[1])
    # disjoint spending categories -> cosine driven only by the shared income feature
    assert c["cosine"]["value"] < 0.5
    assert c["euclidean"]["value"] > 1.0


def test_income_only_change():
    recs = _records([month(2024, 1, {"Groceries": 500.0, "Dining": 300.0}, 3000.0),
                     month(2024, 2, {"Groceries": 500.0, "Dining": 300.0}, 6000.0)])
    c = TL.compare_months(recs[0], recs[1])
    assert APPROX(c["total_spending"]["rel"]["value"], 0.0)
    assert APPROX(c["total_income"]["rel"]["value"], 1.0)
    assert all(abs(pp) < 1e-9 for pp in c["category_pp_deltas"])  # mix unchanged


def test_expense_only_uniform_scale_keeps_mix():
    recs = _records([month(2024, 1, {"Groceries": 500.0, "Dining": 300.0}, 3000.0),
                     month(2024, 2, {"Groceries": 1000.0, "Dining": 600.0}, 3000.0)])
    c = TL.compare_months(recs[0], recs[1])
    assert c["total_spending"]["rel"]["value"] > 0.9   # spend roughly doubled
    assert all(abs(pp) < 1e-6 for pp in c["category_pp_deltas"])  # shares unchanged


def test_category_mix_change_same_total():
    recs = _records([month(2024, 1, {"Groceries": 500.0, "Dining": 500.0}, 3000.0),
                     month(2024, 2, {"Groceries": 200.0, "Dining": 800.0}, 3000.0)])
    c = TL.compare_months(recs[0], recs[1])
    assert APPROX(c["total_spending"]["rel"]["value"], 0.0, 1e-6)
    from reference import taxonomy
    g = taxonomy.category_index("Groceries")
    d = taxonomy.category_index("Dining")
    assert APPROX(c["category_pp_deltas"][g], -30.0, 1e-6)  # 50% -> 20%
    assert APPROX(c["category_pp_deltas"][d], +30.0, 1e-6)  # 50% -> 80%
    assert c["cosine"]["value"] < 1.0


def test_trends_direction_increasing_over_complete_months():
    recs = _records([month(2024, m, {"Groceries": 300.0 + 100.0 * m}, 3000.0)
                     for m in range(1, 5)])
    tr = TL.trends(recs)
    assert tr["total_spending"]["summary"]["direction"] == "increasing"
    assert len(tr["total_spending"]["series"]) == 4


def test_rolling_baseline_mean_of_prior_complete():
    recs = _records([month(2024, 1, {"Groceries": 400.0, "Dining": 600.0}, 3000.0),
                     month(2024, 2, {"Groceries": 600.0, "Dining": 400.0}, 3000.0),
                     month(2024, 3, {"Groceries": 500.0, "Dining": 500.0}, 3000.0)])
    rb = TL.rolling_baselines(recs)
    third = [x for x in rb if x["global_m"] == 2][0]["baseline"]
    assert third["months_used"] == 2
    from reference import taxonomy
    g = taxonomy.category_index("Groceries")
    # mean of Groceries share over months 1,2 = mean(0.4, 0.6) = 0.5
    assert APPROX(third["share_vector"][g], 0.5, 1e-9)


def test_partial_months_excluded_from_trends_and_baselines():
    recs = _records([
        month(2024, 1, {"Groceries": 500.0}, 3000.0, complete=False),  # partial first
        month(2024, 2, {"Groceries": 500.0}, 3000.0),
        month(2024, 3, {"Groceries": 500.0}, 3000.0),
        month(2024, 4, {"Groceries": 500.0}, 3000.0, complete=False),  # partial last
    ])
    tr = TL.trends(recs)
    # only the 2 complete months appear in trend series
    assert len(tr["total_spending"]["series"]) == 2
    rb = TL.rolling_baselines(recs)
    assert all(x["global_m"] in (1, 2) for x in rb)  # baselines only over complete months


def test_compare_to_baseline():
    recs = _records([month(2024, 1, {"Groceries": 400.0, "Dining": 600.0}, 3000.0),
                     month(2024, 2, {"Groceries": 600.0, "Dining": 400.0}, 3000.0),
                     month(2024, 3, {"Groceries": 200.0, "Dining": 800.0}, 3000.0)])
    baseline = TL.build_baseline(recs[:2])
    c = TL.compare_to_baseline(recs[2], baseline)
    assert c["baseline_months"] == 2
    from reference import taxonomy
    d = taxonomy.category_index("Dining")
    # baseline Dining share 0.5, month3 0.8 -> +30 pp
    assert APPROX(c["category_pp_deltas"][d], 30.0, 1e-6)
