# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Per-month metric definitions, guarded denominators, and HHI."""

import math

from analytics.monthly import build_month_record
from tests._analytics_helpers import make_agg, month

APPROX = lambda a, b: math.isclose(a, b, rel_tol=1e-9, abs_tol=1e-9)


def _rec(spec):
    agg, labels = make_agg([spec])
    return build_month_record(agg, labels[0])


def test_scalar_and_ratio_metrics_hand_computed():
    # Feb 2023 (28 days) so the empty 5th day-bin drops out -> even per-day rhythm.
    r = _rec(month(2023, 2, {"Housing": 1000.0, "Groceries": 500.0, "Dining": 300.0},
                   income=3000.0))
    m = r["metrics"]
    assert APPROX(m["total_spending"], 1800.0)
    assert APPROX(m["total_income"], 3000.0)
    assert APPROX(m["net_cash_flow"], 1200.0)
    assert APPROX(m["cash_flow_index"]["value"], 1200.0 / 4800.0)
    assert APPROX(m["savings_rate"]["value"], 0.4)
    assert APPROX(m["fixed_cost_load"]["of_income"]["value"], 1000.0 / 3000.0)
    assert APPROX(m["fixed_cost_load"]["of_spend"]["value"], 1000.0 / 1800.0)
    assert APPROX(m["essential_ratio"]["of_spend"]["value"], 1500.0 / 1800.0)
    assert APPROX(m["discretionary_ratio"]["of_spend"]["value"], 300.0 / 1800.0)
    assert APPROX(m["housing_ratio"]["of_income"]["value"], 1000.0 / 3000.0)
    # category shares
    shares = m["category_shares"]
    from reference import taxonomy
    assert APPROX(shares[taxonomy.category_index("Housing")], 1000.0 / 1800.0)
    assert APPROX(sum(s for s in shares if s is not None), 1.0)
    # rhythm: spending is even per day, so the length-fair per-day cv == 0
    # (Feb has no 5th day-bin; raw per-bin stats are not used for rhythm).
    assert m["weekly_variability"]["per_day"]["cv"]["defined"] is True
    assert APPROX(m["weekly_variability"]["per_day"]["cv"]["value"], 0.0)


def test_zero_income_guards_income_ratios():
    m = _rec(month(2024, 1, {"Housing": 1000.0}, income=0.0))["metrics"]
    assert m["savings_rate"]["defined"] is False
    assert m["fixed_cost_load"]["of_income"]["defined"] is False
    assert m["housing_ratio"]["of_income"]["defined"] is False
    # spend-based still defined
    assert m["fixed_cost_load"]["of_spend"]["defined"] is True
    assert m["cash_flow_index"]["defined"] is True  # income+spend>0


def test_zero_spend_guards_shares_and_hhi():
    m = _rec(month(2024, 1, {}, income=5000.0))["metrics"]
    assert all(s is None for s in m["category_shares"])
    assert m["concentration_hhi"]["defined"] is False
    assert m["savings_rate"]["defined"] is True  # income>0


def test_tiny_denominator_below_eps_is_guarded():
    m = _rec(month(2024, 1, {"Housing": 100.0}, income=0.5))["metrics"]  # income < eps=1
    assert m["savings_rate"]["defined"] is False


def test_hhi_single_category_is_one():
    m = _rec(month(2024, 1, {"Housing": 500.0}, income=1000.0))["metrics"]
    assert APPROX(m["concentration_hhi"]["value"], 1.0)
    assert APPROX(m["concentration_hhi"]["normalized"], 1.0)


def test_hhi_uniform_is_min():
    cats = {n: 100.0 for n in __import__("reference").taxonomy.CATEGORY_NAMES}
    m = _rec(month(2024, 1, cats, income=5000.0))["metrics"]
    assert APPROX(m["concentration_hhi"]["value"], 0.1)       # 1/N
    assert APPROX(m["concentration_hhi"]["normalized"], 0.0)


def test_raw_aggregates_preserved():
    r = _rec(month(2024, 1, {"Housing": 1000.0, "Dining": 200.0}, income=3000.0))
    assert APPROX(r["raw"]["total_spending"], 1200.0)
    assert APPROX(r["raw"]["income"], 3000.0)
    assert len(r["raw"]["category_sums"]) == 10
    assert len(r["raw"]["weekly_sums"]) == 5
