# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Production-app tests: CSV import validation + orchestrator end-to-end, with an
oracle cross-check proving the REAL CKKS pipeline matches plaintext ground truth."""

import datetime

from app import csv_import as ci, orchestrator, demo
from reference import taxonomy
from reference.aggregate import direct_aggregate


def _t(y, m, d, amt, cat, typ):
    idx = None if typ == "income" else taxonomy.category_index(cat)
    return {"date": datetime.date(y, m, d), "amount": amt, "type": typ,
            "category": (cat if typ == "expense" else "Income"), "category_index": idx, "description": "x"}


def test_csv_messy_validation():
    messy = ("Date,Memo,Amount,Category,Flow\n"
             "2025-01-03,Rent,-2150.00,Rent/Mortgage,debit\n"
             "2025-01-05,Paycheck,3100.00,Salary,credit\n"
             "2025-01-07,Transfer to savings,-500.00,Transfer,debit\n"
             "bad-date,Glitch,-5.00,Dining,debit\n"
             "2025-01-08,Euro charge,-€20.00,Shopping,debit\n")
    q = ci.inspect_csv(messy)
    assert q["ok"] and q["suggested_sign"] == "type_field"
    cfg = {"mapping": q["suggested_mapping"], "sign_mode": "type_field",
           "type_map": {"debit": "expense", "credit": "income"},
           "category_map": {"Rent/Mortgage": "Housing", "Salary": "Income", "Dining": "Dining",
                            "Shopping": "Shopping", "Transfer": "Exclude"}, "include_flagged": False}
    txns, rep = ci.build_transactions(messy, cfg)
    reasons = " ".join(r["reason"] for r in rep["invalid_rows"])
    assert "unrecognized date" in reasons and "non-USD currency" in reasons  # not silently guessed
    assert rep["counts"]["income"] == 1 and rep["counts"]["expense"] == 1     # rent + paycheck
    assert any("transfer/refund" in w for w in rep["warnings"])               # transfer excluded, reported
    assert rep["ok"]  # usable transactions exist despite invalid rows


def test_example_csv_imports_cleanly():
    q = ci.inspect_csv(demo.example_csv())
    cfg = {"mapping": q["suggested_mapping"], "sign_mode": q["suggested_sign"],
           "category_map": {c: (q["suggested_category_map"].get(c) or ("Income" if c == "Income" else c)) for c in q["categories"]},
           "type_map": {t: (q["suggested_type_map"].get(t) or t) for t in q["types"]}, "include_flagged": False}
    txns, rep = ci.build_transactions(demo.example_csv(), cfg)
    assert rep["ok"] and rep["counts"]["total"] == 8 and rep["counts"]["invalid"] == 0


def test_orchestrator_matches_plaintext_oracle():
    """The full real pipeline (pack -> CKKS encrypt/server/decrypt -> analytics)
    must reproduce the plaintext aggregation within CKKS tolerance."""
    txns = [_t(2024, 1, 5, 1000.0, "Housing", "expense"), _t(2024, 1, 6, 200.0, "Groceries", "expense"),
            _t(2024, 1, 10, 3000.0, "Income", "income"),
            _t(2024, 2, 5, 1100.0, "Housing", "expense"), _t(2024, 2, 6, 250.0, "Dining", "expense"),
            _t(2024, 2, 10, 3000.0, "Income", "income")]
    res = orchestrator.analyze(txns, "pytest")
    assert res["counts"]["months_total"] >= 2
    assert res["defaults"]["dashboard_gm"] is not None
    direct, _ = direct_aggregate(txns)
    by_gm = {m["global_m"]: m for m in res["months"]}
    for (gm, c), v in direct["cat"].items():
        got = by_gm[gm]["raw"]["category_sums"][c]
        assert abs(got - v) <= max(0.05, 1e-4 * abs(v)), f"cat {gm},{c}: {got} vs {v}"
    for gm, v in direct["income"].items():
        got = by_gm[gm]["metrics"]["total_income"]
        assert abs(got - v) <= max(0.05, 1e-4 * abs(v)), f"income {gm}: {got} vs {v}"
