# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Tests for the on-device semantic categorizer.

Proves it GENERALIZES to unseen/international merchants (not a dictionary), runs
with zero external network, categorizes a raw 3-column CSV with ~no required manual
work (non-blocking policy: low-confidence -> best-guess "Other", flagged, optional
review), keeps user corrections local, holds back truly uncategorizable rows, and
that disabling the categorizer or any Stage-5 binary blocks results appropriately.
Also verifies the in-browser JS model matches the Python reference exactly.
"""

import json
import os
import socket
import subprocess

import pytest

from app import categorize, categorize_model, csv_import, orchestrator, pipeline, demo
from reference import taxonomy

CATS = set(taxonomy.CATEGORY_NAMES)
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_MAP = {"date": "date", "description": "description", "amount": "amount",
            "category": None, "type": None}


def _cfg(**kw):
    c = {"mapping": BASE_MAP, "sign_mode": "amount_sign_neg_expense",
         "auto_categorize": True, "category_map": {}, "type_map": {}, "use_cache": False}
    c.update(kw)
    return c


def _csv(merchants, per=6):
    rows = ["date,description,amount"]
    for i in range(per * len(merchants)):
        rows.append(f"2025-03-{(i % 28) + 1:02d},{merchants[i % len(merchants)]},-{20 + i % 40}.00")
    rows.append("2025-03-15,PAYROLL DIRECT DEPOSIT,3200.00")
    return "\n".join(rows) + "\n"


# ---- held-out, UNSEEN, international merchants (none verbatim in the corpus) ----
UNSEEN = [
    ("Dining", "SQ *BLUE BOTTLE COFFEE"), ("Dining", "PANDA EXPRESS #1123"),
    ("Dining", "SHAKE SHACK NEW YORK"), ("Groceries", "TRADER JOES #556"),
    ("Groceries", "SPROUTS FARMERS MKT"), ("Transportation", "CHEVRON 00291847"),
    ("Transportation", "LYFT *RIDE FRI"), ("Healthcare", "WALGREENS #04123 RX"),
    ("Healthcare", "QUEST DIAGNOSTICS LAB"), ("Shopping", "NORDSTROM RACK #221"),
    ("Subscriptions", "HULU 877-8244858"), ("Subscriptions", "ADOBE *CREATIVE CLD"),
    ("Utilities", "CONED BILL PAYMENT"), ("Insurance", "PROGRESSIVE *INSURANCE"),
    ("Housing", "GREYSTAR RENT 4410"), ("Entertainment", "AMC ONLINE 6035"),
]
INTL = [
    ("Groceries", "MERCADONA 5482 VALENCIA"), ("Groceries", "SUPERMERCADO DIA"),
    ("Groceries", "REWE SAGT DANKE"), ("Groceries", "LIDL DIENSTLEISTUNG"),
    ("Dining", "RESTAURANTE EL RINCON"), ("Dining", "PANADERIA LA ESPIGA"),
    ("Dining", "BOULANGERIE PAUL PARIS"), ("Dining", "TRATTORIA DA MARIO"),
    ("Transportation", "GASOLINERA REPSOL"), ("Transportation", "TANKSTELLE ARAL"),
    ("Transportation", "SNCF INTERNET PARIS"), ("Healthcare", "FARMACIA SANCHEZ"),
    ("Healthcare", "APOTHEKE AM MARKT"), ("Healthcare", "PHARMACIE DE LA GARE"),
    ("Utilities", "IBERDROLA CLIENTES"), ("Utilities", "EDF FACTURE"),
    ("Shopping", "ZARA MADRID CENTRO"), ("Insurance", "ALLIANZ VERSICHERUNG"),
]


def _acc(sample):
    return sum(categorize.categorize(d)["category"] == lab for lab, d in sample) / len(sample)


# 1) Generalizes to previously UNSEEN merchants (this is the whole point).
def test_generalizes_to_unseen_merchants():
    acc = _acc(UNSEEN)
    assert acc >= 0.75, f"unseen accuracy too low: {acc:.2f}"


# 2) Generalizes to INTERNATIONAL merchants (ES/DE/FR/IT), not just US.
def test_generalizes_to_international_merchants():
    acc = _acc(INTL)
    assert acc >= 0.80, f"international accuracy too low: {acc:.2f}"


# 3) Output schema: one fixed category + confidence + short_reason + model_stage.
def test_output_schema():
    r = categorize.categorize("STARBUCKS #1122 SEATTLE WA")
    assert r["category"] in CATS
    assert 0.0 <= r["confidence"] <= 1.0
    assert isinstance(r["short_reason"], str) and r["short_reason"]
    assert r["model_stage"] in ("classifier", "rules+classifier", "llm", "none")


# 4) ZERO external network requests during classification.
def test_no_network(monkeypatch):
    def boom(*a, **k):
        raise AssertionError("categorizer attempted a network connection")
    monkeypatch.setattr(socket.socket, "connect", boom)
    monkeypatch.setattr(socket.socket, "connect_ex", boom)
    monkeypatch.setattr(socket, "create_connection", boom)
    for _, d in UNSEEN + INTL:
        categorize.categorize(d)
    csv_import.build_transactions(_csv(["SQ *ABC", "MERCADONA 1"]), _cfg())


# 5) Raw 3-column CSV: ~everything auto-categorized, ZERO required manual action.
def test_three_column_no_manual_work():
    merchants = [d for _, d in (UNSEEN + INTL)]
    txns, rep = csv_import.build_transactions(_csv(merchants, per=4), _cfg())
    exp = rep["counts"]["expense"]
    assert rep["ready"] is True                 # analysis is enabled
    assert rep["uncategorized"] == 0            # nothing requires manual action
    c = rep["categorization"]
    assert c["auto"] + c["flagged"] + c["other"] == exp   # every expense categorized
    assert all(t["type"] == "income" or t["category"] in CATS for t in txns)


# 6) Repeated merchants get consistent categories.
def test_repeated_merchants_consistent():
    txns, _ = csv_import.build_transactions(_csv(["STARBUCKS #1", "STARBUCKS #2", "STARBUCKS #3"]), _cfg())
    assert {t["category"] for t in txns if t["type"] == "expense"} == {"Dining"}


# 7) Low-confidence is analyzed (best guess) AND surfaced for OPTIONAL review — not blocking.
def test_low_confidence_optional_review_not_blocking():
    txns, rep = csv_import.build_transactions(_csv(["SQ *ZZQ9 UNKNOWN", "STARBUCKS #1"]), _cfg())
    assert rep["ready"] is True                          # never blocked by review
    assert rep["categorization"]["review_items"]         # something offered for optional review
    # the unknown merchant was still analyzed (best guess), not dropped
    assert any("zzq9" in (t["description"] or "").lower() for t in txns)


# 8) User corrections are retained and reused locally.
def test_user_corrections_retained(tmp_path, monkeypatch):
    cache = str(tmp_path / "mc.json")
    monkeypatch.setattr(csv_import, "CACHE_PATH", cache)
    csv = _csv(["SQ *ZZQ9 UNKNOWN", "STARBUCKS #1"])
    cfg = _cfg(use_cache=True)
    _, rep = csv_import.build_transactions(csv, cfg)
    key = rep["categorization"]["review_items"][0]["key"]
    _, rep2 = csv_import.build_transactions(csv, dict(cfg, category_overrides={key: "Healthcare"}))
    assert os.path.exists(cache)
    txns3, _ = csv_import.build_transactions(csv, cfg)   # fresh; correction reused from local cache
    assert any(t["type"] == "expense" and t["description"] and "zzq9" in t["description"].lower()
               and t["category"] == "Healthcare" for t in txns3)


# 9) Disabling the categorizer prevents uncategorized expenses from reaching FHE packing.
def test_disabling_categorizer_holds_expenses_back():
    txns, rep = csv_import.build_transactions(_csv(["SQ *ABC", "MERCADONA 1"]), _cfg(classifier_enabled=False))
    assert rep["uncategorized"] > 0 and rep["ready"] is False
    assert not any(t["type"] == "expense" for t in txns)   # none reached the packable set


# 10) Disabling any required Stage-5 binary blocks BOTH demo and uploaded-data results.
def test_disabling_stage5_binary_blocks_all(monkeypatch, tmp_path):
    monkeypatch.setattr(pipeline, "BIN", str(tmp_path / "no_binaries"))
    os.makedirs(str(tmp_path / "no_binaries"), exist_ok=True)
    with pytest.raises(Exception):
        orchestrator.analyze(demo.generate_transactions(), "t_demo")
    up = [{"date": __import__("datetime").date(2025, 3, 1), "amount": 50.0, "type": "expense",
           "category": "Groceries", "category_index": taxonomy.category_index("Groceries"), "description": "x"}]
    with pytest.raises(Exception):
        orchestrator.analyze(up, "t_upload")


# 11) The in-browser JS model matches the Python reference exactly (parity).
def test_browser_js_matches_python():
    if not os.path.exists(os.path.join(ROOT, "web", "categorizer.json")):
        pytest.skip("model not built")
    descs = [d for _, d in (UNSEEN + INTL)]
    js = ("const fs=require('fs');global.fetch=async()=>({json:async()=>"
          "JSON.parse(fs.readFileSync(process.argv[1],'utf8'))});"
          "const C=require(process.argv[2]);(async()=>{await C.load('x');"
          "console.log(JSON.stringify(process.argv[3].split('\\n').map(d=>C.classify(d).category)))})();")
    try:
        out = subprocess.run(
            ["node", "-e", js, os.path.join(ROOT, "web", "categorizer.json"),
             os.path.join(ROOT, "web", "classifier.js"), "\n".join(descs)],
            capture_output=True, text=True, timeout=60)
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pytest.skip("node unavailable")
    assert out.returncode == 0, out.stderr
    js_cats = json.loads(out.stdout)
    py_cats = [categorize.categorize(d)["category"] for d in descs]
    assert js_cats == py_cats
