# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""No transaction is silently omitted: placement counts and value sums conserve."""

import pytest

from reference import fixtures
from reference.aggregate import direct_aggregate
from reference.twin import build_batches, twin_aggregate
from reference.errors import assert_close
from tests._helpers import stream_total


@pytest.mark.parametrize("name", list(fixtures.ALL_GENERATORS))
def test_placement_counts_match_inputs(name):
    txns = fixtures.ALL_GENERATORS[name]()
    n_exp = sum(1 for t in txns if t["type"] == "expense")
    n_inc = sum(1 for t in txns if t["type"] == "income")
    _, meta = build_batches(txns)
    # every expense placed once in ct1 (category) and once in ct2 (weekly)
    assert meta["ct1_placements"] == n_exp
    assert meta["ct2_week_placements"] == n_exp
    # every income placed once in ct2 (income)
    assert meta["ct2_income_placements"] == n_inc


@pytest.mark.parametrize("name", list(fixtures.ALL_GENERATORS))
def test_value_sums_conserve(name):
    txns = fixtures.ALL_GENERATORS[name]()
    exp_sum = sum(t["amount"] for t in txns if t["type"] == "expense")
    inc_sum = sum(t["amount"] for t in txns if t["type"] == "income")

    direct, base = direct_aggregate(txns)
    batches, _ = build_batches(txns, base=base)
    twin = twin_aggregate(batches)

    # direct and twin both conserve the full input value, per stream
    for agg in (direct, twin):
        assert_close(stream_total(agg, "cat"), exp_sum, msg=f"{name} cat total")
        assert_close(stream_total(agg, "week"), exp_sum, msg=f"{name} week total")
        assert_close(stream_total(agg, "income"), inc_sum, msg=f"{name} income total")
