# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Overflow spills into additive batches with no truncation or double-counting."""

from reference import fixtures, layout
from reference.aggregate import direct_aggregate
from reference.twin import build_batches, twin_aggregate
from reference.errors import assert_close
from tests._helpers import compare_aggregates, stream_total


def _roundtrip(txns):
    direct, base = direct_aggregate(txns)
    batches, meta = build_batches(txns, base=base)
    twin = twin_aggregate(batches)
    return direct, twin, batches, meta


def _has_extra_layer(batches):
    return any(b.layer >= 1 for b in batches)


def _groups(batches):
    return {b.group for b in batches}


def test_overflow_category_spills_and_recombines():
    txns = fixtures.gen_overflow_category()
    direct, twin, batches, _ = _roundtrip(txns)
    assert _has_extra_layer(batches), "40 in one (month,category) must spill to layer>=1"
    compare_aggregates(direct, twin)
    # exactly the 40 transactions are accounted for, none dropped or doubled
    assert_close(stream_total(twin, "cat"), sum(t["amount"] for t in txns))


def test_overflow_week_spills_and_recombines():
    txns = fixtures.gen_overflow_week()
    direct, twin, batches, _ = _roundtrip(txns)
    assert _has_extra_layer(batches), "70 in one (month,week-bin) must spill to layer>=1"
    compare_aggregates(direct, twin)
    assert_close(stream_total(twin, "week"), sum(t["amount"] for t in txns))


def test_overflow_income_spills_and_recombines():
    txns = fixtures.gen_overflow_income()
    direct, twin, batches, _ = _roundtrip(txns)
    assert _has_extra_layer(batches), "70 income in one month must spill to layer>=1"
    compare_aggregates(direct, twin)
    assert_close(stream_total(twin, "income"), sum(t["amount"] for t in txns))


def test_overflow_months_uses_multiple_groups():
    txns = fixtures.gen_multi_year(n_months=14)
    direct, twin, batches, _ = _roundtrip(txns)
    assert _groups(batches) == {0, 1}, "14 months must span two month-groups"
    compare_aggregates(direct, twin)


def test_no_double_counting_totals():
    # Combined stress: category + income overflow together.
    txns = fixtures.gen_overflow_category() + fixtures.gen_overflow_income()
    direct, twin, batches, _ = _roundtrip(txns)
    compare_aggregates(direct, twin)
    exp = sum(t["amount"] for t in txns if t["type"] == "expense")
    inc = sum(t["amount"] for t in txns if t["type"] == "income")
    assert_close(stream_total(twin, "cat"), exp)
    assert_close(stream_total(twin, "income"), inc)
