# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Ordinary aggregation is correct, and large transactions are never clipped."""

import datetime

from reference import taxonomy, fixtures
from reference.aggregate import direct_aggregate
from reference.twin import build_batches, twin_aggregate
from reference.errors import assert_close


def _txn(d, amt, cat, typ):
    ci = None if typ == "income" else taxonomy.category_index(cat)
    return {"date": d, "amount": amt, "type": typ, "category": cat, "category_index": ci}


def test_hand_computed_aggregation():
    g = taxonomy.category_index("Groceries")  # 2
    d = taxonomy.category_index("Dining")      # 6
    txns = [
        _txn(datetime.date(2024, 1, 5), 10.0, "Groceries", "expense"),   # week-bin 0
        _txn(datetime.date(2024, 1, 5), 20.0, "Groceries", "expense"),   # week-bin 0
        _txn(datetime.date(2024, 1, 10), 30.0, "Dining", "expense"),     # week-bin 1
        _txn(datetime.date(2024, 1, 15), 1000.0, "Income", "income"),
    ]
    agg, base = direct_aggregate(txns)
    assert base == (2024, 1)
    assert_close(agg["cat"][(0, g)], 30.0)
    assert_close(agg["cat"][(0, d)], 30.0)
    assert_close(agg["week"][(0, 0)], 30.0)
    assert_close(agg["week"][(0, 1)], 30.0)
    assert_close(agg["income"][0], 1000.0)


def test_large_transaction_not_clipped_and_roundtrips():
    txns = fixtures.gen_basic(n_months=1, seed=0, big_transaction=True)
    h = taxonomy.category_index("Housing")
    direct, _ = direct_aggregate(txns)
    # The 250000 Housing transaction must appear in full in the direct total.
    assert direct["cat"][(0, h)] >= 250000.0

    # And it must survive scale -> pack -> fold -> unscale in the twin exactly.
    batches, _ = build_batches(txns)
    twin = twin_aggregate(batches)
    assert_close(twin["cat"][(0, h)], direct["cat"][(0, h)],
                 abs_tol=1e-3, rel_tol=1e-9, msg="large Housing txn")
