# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Incomplete calendar months are labeled correctly."""

import datetime

from reference.completeness import label_months


def test_partial_first_and_last_months():
    # Window Jan 15 -> Mar 20, 2024. Jan partial, Feb complete, Mar partial.
    dates = [datetime.date(2024, 1, 15), datetime.date(2024, 2, 10),
             datetime.date(2024, 3, 20)]
    labels = label_months(dates)
    assert [l["month"] for l in labels] == [1, 2, 3]
    jan, feb, mar = labels
    assert jan["complete"] is False
    assert feb["complete"] is True
    assert mar["complete"] is False
    assert jan["coverage_days"] == 17    # days 15..31
    assert feb["coverage_days"] == 29    # 2024 is a leap year
    assert mar["coverage_days"] == 20    # days 1..20


def test_fully_covered_window_all_complete():
    dates = [datetime.date(2024, 1, 1), datetime.date(2024, 3, 31)]
    labels = label_months(dates)
    assert all(l["complete"] for l in labels)
    assert len(labels) == 3


def test_middle_month_with_no_transactions_still_complete():
    # Gap in Feb, but the window spans it -> Feb is complete (coverage, not presence).
    dates = [datetime.date(2024, 1, 1), datetime.date(2024, 3, 31)]
    labels = label_months(dates)
    feb = [l for l in labels if l["month"] == 2][0]
    assert feb["complete"] is True


def test_global_month_indexing_is_contiguous():
    dates = [datetime.date(2024, 11, 5), datetime.date(2025, 2, 20)]
    labels = label_months(dates)
    assert [l["global_m"] for l in labels] == [0, 1, 2, 3]
    assert [(l["year"], l["month"]) for l in labels] == [
        (2024, 11), (2024, 12), (2025, 1), (2025, 2)]
