# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Deterministic story engine: headlines, ranking, stability, source-of-change,
and the guarantee that narratives describe measured changes only."""

from analytics.monthly import build_month_record
from analytics import timeline as TL
from analytics import story as ST
from tests._analytics_helpers import make_agg, month

# Words the story engine must never produce (motives, causes, advice, life events).
FORBIDDEN = ["because", "stress", "stressed", "trip", "vacation", "holiday", "advice",
             "should", "recommend", "probably", "emotion", "relationship", "job",
             "fired", "birthday", "wedding", "divorce", "happy", "sad", "worried",
             "good job", "bad", "overspent", "too much"]


def _cmp(a, b):
    agg, labels = make_agg([a, b])
    ra = build_month_record(agg, labels[0])
    rb = build_month_record(agg, labels[1])
    return TL.compare_months(ra, rb)


def test_headline_total_spending_increase():
    c = _cmp(month(2024, 1, {"Groceries": 500.0}, 3000.0),
             month(2024, 2, {"Groceries": 700.0}, 3000.0))
    cards = ST.stories_for_comparison(c, "test")
    head = cards[0]
    assert head["type"] == "headline"
    assert head["kind"] == "primary_change"
    assert "spending" in head["title"].lower()


def test_headline_stable_when_no_meaningful_change():
    c = _cmp(month(2024, 1, {"Groceries": 500.0, "Dining": 300.0}, 3000.0),
             month(2024, 2, {"Groceries": 500.0, "Dining": 300.0}, 3000.0))
    head = ST.headline_card(c)
    assert head["kind"] == "stable"


def test_category_change_ranking_largest_first():
    c = _cmp(month(2024, 1, {"Groceries": 500.0, "Dining": 500.0}, 3000.0),
             month(2024, 2, {"Groceries": 100.0, "Dining": 900.0}, 3000.0))
    ranked = ST.rank_category_changes(c)
    assert ranked[0]["category"] in ("Dining", "Groceries")
    assert abs(ranked[0]["pp"]) >= abs(ranked[-1]["pp"])


def test_stable_categories_detected():
    c = _cmp(month(2024, 1, {"Groceries": 500.0, "Dining": 500.0}, 3000.0),
             month(2024, 2, {"Groceries": 500.0, "Dining": 500.0}, 3000.0))
    assert "Groceries" in ST.stable_categories(c)


def test_source_of_change_total_scale():
    c = _cmp(month(2024, 1, {"Groceries": 500.0, "Dining": 500.0}, 3000.0),
             month(2024, 2, {"Groceries": 1000.0, "Dining": 1000.0}, 3000.0))
    assert ST.source_of_change(c)["evidence"]["driver"] == "total spending level"


def test_source_of_change_income():
    c = _cmp(month(2024, 1, {"Groceries": 500.0, "Dining": 500.0}, 3000.0),
             month(2024, 2, {"Groceries": 500.0, "Dining": 500.0}, 6000.0))
    assert ST.source_of_change(c)["evidence"]["driver"] == "income / cash flow"


def test_source_of_change_category_mix():
    c = _cmp(month(2024, 1, {"Groceries": 500.0, "Dining": 500.0}, 3000.0),
             month(2024, 2, {"Groceries": 100.0, "Dining": 900.0}, 3000.0))
    assert ST.source_of_change(c)["evidence"]["driver"] == "category mix"


def test_stories_never_contain_motive_or_advice_language():
    scenarios = [
        _cmp(month(2024, 1, {"Groceries": 500.0}, 3000.0),
             month(2024, 2, {"Entertainment": 1500.0}, 1000.0)),
        _cmp(month(2024, 1, {"Housing": 2000.0}, 5000.0),
             month(2024, 2, {"Housing": 500.0, "Dining": 900.0}, 5000.0)),
    ]
    for c in scenarios:
        for card in ST.stories_for_comparison(c, "test"):
            text = (card["title"] + " " + card["detail"]).lower()
            for w in FORBIDDEN:
                assert w not in text, f"forbidden word {w!r} in story: {text!r}"
