# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""The faithful packed-layout twin reproduces direct plaintext aggregation."""

import pytest

from reference import fixtures
from reference.aggregate import direct_aggregate
from reference.twin import build_batches, twin_aggregate
from tests._helpers import compare_aggregates


@pytest.mark.parametrize("name", list(fixtures.ALL_GENERATORS))
def test_twin_matches_direct(name):
    txns = fixtures.ALL_GENERATORS[name]()
    direct, base = direct_aggregate(txns)
    batches, _ = build_batches(txns, base=base)
    twin = twin_aggregate(batches)
    compare_aggregates(direct, twin)
