# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Output contract: JSON-serializable, no NaN/inf, partial-month handling,
1-month / multi-month / multi-year datasets, and real-fixture integration."""

import json

import pytest

from analytics import build_result, validate_result
from analytics.schema import SCHEMA_VERSION
from tests._analytics_helpers import make_agg, month

from reference import fixtures
from reference.aggregate import direct_aggregate
from reference.completeness import label_months


def _build(specs, **kw):
    agg, labels = make_agg(specs)
    return build_result(agg, labels, **kw)


REQUIRED_TOP = {"schema_version", "privacy", "limitations", "config", "categories",
                "months", "timeline", "comparisons", "stories", "counts"}


def test_schema_shape_and_json_serializable():
    r = _build([month(2024, m, {"Groceries": 400.0 + 50.0 * m, "Dining": 300.0}, 3000.0)
                for m in range(1, 4)])
    assert REQUIRED_TOP <= set(r.keys())
    assert r["schema_version"] == SCHEMA_VERSION
    assert r["privacy"]["server_saw_plaintext"] is False
    assert len(r["categories"]) == 10
    json.dumps(r)  # must not raise (fully serializable, no NaN/inf tokens)


def test_no_non_finite_across_edge_cases():
    specs = [
        month(2024, 1, {}, 0.0),                       # zero spend, zero income
        month(2024, 2, {"Housing": 1000.0}, 0.0),      # zero income
        month(2024, 3, {"Groceries": 100.0}, 0.5),     # tiny income denom
        month(2024, 4, {"Groceries": 500.0, "Dining": 500.0}, 3000.0),
        month(2024, 5, {"Entertainment": 5000.0}, 500.0),  # radically different
    ]
    r = _build(specs)
    assert validate_result(r) == [], "no NaN/Infinity may reach the result object"
    text = json.dumps(r)
    assert "NaN" not in text and "Infinity" not in text


def test_one_month_dataset():
    r = _build([month(2024, 1, {"Groceries": 500.0}, 3000.0)])
    assert r["counts"]["months_total"] == 1
    assert r["timeline"]["month_over_month"] == []
    assert r["stories"] == []
    assert validate_result(r) == []


def test_multi_year_dataset():
    specs = [month(2024 + (m // 12), (m % 12) + 1, {"Groceries": 500.0, "Dining": 300.0},
                   3000.0) for m in range(14)]
    r = _build(specs)
    assert r["counts"]["months_total"] == 14
    assert r["counts"]["months_complete"] == 14
    assert len(r["timeline"]["trends"]["total_spending"]["series"]) == 14
    assert validate_result(r) == []


def test_partial_months_labeled_and_excluded():
    specs = [month(2024, 1, {"Groceries": 500.0}, 3000.0, complete=False)]
    specs += [month(2024, m, {"Groceries": 500.0}, 3000.0) for m in range(2, 5)]
    specs += [month(2024, 5, {"Groceries": 500.0}, 3000.0, complete=False)]
    r = _build(specs)
    assert r["counts"]["months_partial"] == 2
    assert r["counts"]["months_complete"] == 3
    # partial months still present/browsable
    partial = [mo for mo in r["months"] if not mo["complete"]]
    assert len(partial) == 2
    # trends only over complete months
    assert len(r["timeline"]["trends"]["total_spending"]["series"]) == 3


def test_selected_pairwise_comparison():
    specs = [month(2024, m, {"Groceries": 500.0 * m, "Dining": 300.0}, 3000.0)
             for m in range(1, 4)]
    r = _build(specs, selected_pairs=[(0, 2)])
    assert len(r["comparisons"]["pairwise"]) == 1
    assert r["comparisons"]["pairwise"][0]["from_gm"] == 0
    assert r["comparisons"]["pairwise"][0]["to_gm"] == 2


@pytest.mark.parametrize("name", list(fixtures.ALL_GENERATORS))
def test_integration_with_real_oracle_aggregates(name):
    txns = fixtures.ALL_GENERATORS[name]()
    agg, _ = direct_aggregate(txns)
    labels = label_months([t["date"] for t in txns])
    r = build_result(agg, labels)
    assert validate_result(r) == []
    json.dumps(r)
