# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""All ratios guard against zero / very small denominators (no inf, no NaN)."""

import math

from reference import taxonomy
from reference.metrics import monthly_metrics, similarity
from reference.errors import safe_ratio


def _cat_vec(**named):
    v = [0.0] * taxonomy.N_CATEGORIES
    for name, amt in named.items():
        v[taxonomy.category_index(name)] = amt
    return v


def _is_guarded(result):
    val, flag = result
    return val is None and isinstance(flag, str)


def test_zero_income_guards_income_denominated_ratios():
    cat = _cat_vec(Groceries=300.0, Housing=1200.0)
    m = monthly_metrics(cat, [100.0, 200.0, 500.0, 700.0, 0.0], income=0.0)
    assert _is_guarded(m["savings_rate"])
    assert _is_guarded(m["fixed_load_income"])
    assert _is_guarded(m["housing_ratio_income"])
    # spend-denominated ratios are still defined (spend > 0)
    assert m["fixed_load_spend"][0] is not None
    assert m["cashflow_index"][0] is not None  # income+spend > 0


def test_zero_spend_guards_shares_and_hhi():
    cat = _cat_vec()  # all zero
    m = monthly_metrics(cat, [0.0] * 5, income=5000.0)
    assert all(_is_guarded(s) for s in m["category_shares"])
    assert _is_guarded(m["hhi"])
    assert _is_guarded(m["cashflow_index"]) is False  # income>0 so defined
    assert m["savings_rate"][0] is not None            # income>0


def test_small_denominator_below_eps_is_guarded():
    # income 0.5 < default eps 1.0 -> unstable, must be guarded not amplified.
    val, flag = safe_ratio(100.0, 0.5, eps_denom=1.0)
    assert val is None and flag is not None


def test_no_inf_or_nan_anywhere():
    cat = _cat_vec(Groceries=0.0001)  # tiny spend
    m = monthly_metrics(cat, [0.0001, 0, 0, 0, 0], income=0.0001)
    for key, res in m.items():
        if isinstance(res, tuple):
            val = res[0]
            assert val is None or math.isfinite(val), f"{key} not finite: {val}"


def test_similarity_guards_zero_spend_month():
    a = _cat_vec(Groceries=100.0, Dining=50.0)
    b = _cat_vec()  # zero-spend month
    sim = similarity(a, 3000.0, b, 3000.0)
    assert sim["cosine"][0] is None
    assert sim["euclidean"][0] is None


def test_similarity_defined_for_normal_months():
    a = _cat_vec(Groceries=100.0, Dining=50.0)
    b = _cat_vec(Groceries=90.0, Dining=60.0)
    sim = similarity(a, 3000.0, b, 3200.0)
    cos = sim["cosine"][0]
    assert cos is not None and 0.0 <= cos <= 1.0 + 1e-9
    assert sim["euclidean"][0] is not None and sim["euclidean"][0] >= 0.0
    assert len(sim["category_deltas"]) == taxonomy.N_CATEGORIES
