# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""CipherSpend on-device runtime (local orchestrator).

This package is the "client device" in the FHE architecture: it parses/categorizes
CSVs, packs them (reusing the Stage-3 `reference` modules), drives the real Stage-5
CKKS four-program pipeline (keygen/encrypt/server/decrypt native binaries), and
computes analytics with the Stage-6 `analytics` package. Nothing here calls any
remote or external service; the secret key stays in a client-only home directory.
"""
