# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""On-device semantic merchant classifier — training corpus, canonicalizer, and a
JS-replicable char n-gram featurizer + linear model.

This is a genuine text-classification model (multinomial logistic regression over
word-boundary character n-grams), trained on a RICH, MULTILINGUAL corpus of
category *definitions and diverse examples* — not a merchant dictionary. Sub-word
features let it generalize to previously unseen, abbreviated, and international
merchants (e.g. "farmacia"/"apotheke"/"pharmacie" -> Healthcare; "ristorante"/
"taqueria"/"brasserie" -> Dining) without ever having seen those exact names.

The featurizer here is intentionally simple and deterministic so the identical
inference can run IN THE BROWSER (see web/classifier.js) from exported weights —
tiny (~KB), instant cold-start, zero model download, zero network.
"""

import re

from reference import taxonomy

CATEGORIES = list(taxonomy.CATEGORY_NAMES)   # the 10 fixed categories

# ---- canonical merchant extraction ---------------------------------------
_PHONE = re.compile(r"\b(?:\+?\d[\d\-\.\(\) ]{6,}\d)\b")
_LONGNUM = re.compile(r"\b[a-z]*\d{3,}[a-z0-9]*\b")     # store/txn ids, card tails
_URL = re.compile(r"\b(?:https?://|www\.)\S+|\b[a-z0-9\-]+\.(?:com|net|org|io|co|es|de|fr|mx|uk)\b")
_NOISE = re.compile(r"\b(pos|debit|credit|card|purchase|payment|pmt|ach|ppd|des|id|ref|"
                    r"recurring|trans|transaction|auth|authorized|online|web|recur|bill|"
                    r"billpay|checkcard|ckcd|visa|mastercard|amex|xxxx|usd|eur|gbp|mxn|"
                    r"the|inc|llc|ltd|co|corp|sa|gmbh|srl|bv|of|and)\b")
_STATES = re.compile(r"\b(a[klrz]|c[aot]|d[ce]|fl|ga|hi|i[adln]|k[sy]|la|m[adeinost]|"
                     r"n[cdehjmvy]|o[hkr]|pa|ri|s[cd]|t[nx]|ut|v[at]|w[aivy])\b")
_MULTISPACE = re.compile(r"\s+")


def canonicalize(desc):
    """Strip bank-processing boilerplate, dates, phone numbers, transaction ids,
    card prefixes, URLs, and location codes — leaving the core merchant text.
    The ORIGINAL description is preserved by the caller."""
    s = (desc or "").lower()
    s = s.replace("*", " ").replace("#", " ").replace("/", " ")
    s = re.sub(r"https?://|www\.", " ", s)
    # keep a domain's NAME but drop the TLD (steamgames.com -> steamgames)
    s = re.sub(r"\b([a-z][a-z0-9\-]{2,})\.(?:com|net|org|io|co|es|de|fr|mx|uk|it|pt|eu)\b", r"\1", s)
    s = _PHONE.sub(" ", s)
    s = re.sub(r"\d{1,2}[\-/]\d{1,2}(?:[\-/]\d{2,4})?", " ", s)   # dates
    s = _LONGNUM.sub(" ", s)
    s = re.sub(r"[^a-zÀ-ſ ]+", " ", s)                  # keep letters (incl. accents)
    s = _NOISE.sub(" ", s)
    s = _STATES.sub(" ", s)
    s = _MULTISPACE.sub(" ", s).strip()
    return s


# ---- JS-replicable char n-gram featurizer --------------------------------
NGRAMS = (3, 4, 5)


def features(canonical):
    """Set of word-boundary char n-grams (sizes 3-5). Deterministic; mirrored 1:1
    in web/classifier.js so browser inference matches training exactly."""
    s = " " + _MULTISPACE.sub(" ", (canonical or "").strip()) + " "
    if s == "  ":
        return set()
    feats = set()
    L = len(s)
    for n in NGRAMS:
        if L >= n:
            for i in range(L - n + 1):
                g = s[i:i + n]
                if g != " " * n:
                    feats.add(g)
    return feats


# ---- rich multilingual training corpus (definitions + diverse examples) ---
# Each entry is a canonical-ish merchant phrase. Spans EN / ES / DE / FR / IT /
# PT and common abbreviations. These teach morphology, NOT specific merchants.
CORPUS = {
"Housing": """rent monthly rent apartment rental property management leasing office realty
real estate mortgage home loan landlord tenant lease hoa homeowners association condo
alquiler renta arriendo alquiler mensual inmobiliaria administracion propiedad hipoteca
casa vivienda arrendamiento renta departamento miete mietwohnung wohnung immobilien makler
hausverwaltung loyer bailleur immobilier location appartement syndic affitto immobiliare
canone locazione aluguel imobiliaria condominio greystar avalon equity residential""",

"Utilities": """electric electricity power company energy utility natural gas water sewer
waste trash internet broadband fiber wifi cable phone mobile wireless telecom cellular
data plan light bill power grid coned pge duke energy national grid comcast xfinity spectrum
verizon att t mobile electricidad energia luz agua saneamiento gas natural internet fibra
telefono movil compania electrica endesa iberdrola naturgy telefonica vodafone movistar
strom energie wasser abwasser gaswerke stadtwerke telekom vodafone mobilfunk elektrizitat
electricite energie eau assainissement orange sfr free bouygues enel eni tim wind acea""",

"Groceries": """grocery groceries supermarket market food store fresh market whole foods
farmers market produce butcher greengrocer mini mart convenience deli grocer hypermarket
supermercado mercado abarrotes tienda alimentacion fruteria verduleria carniceria
comestibles mercadona carrefour dia alcampo lidl aldi supermarkt lebensmittel markt
edeka rewe kaufland penny netto epicerie marche alimentation supermarche coop conad esselunga
alimentari mercearia hortifruti kroger safeway publix wegmans trader joe costco walmart heb""",

"Transportation": """gas station fuel gasoline petrol diesel filling station uber lyft taxi
cab rideshare transit metro subway bus train railway tram parking garage toll turnpike
highway car wash auto repair mechanic tires oil change dmv vehicle registration bike scooter
gasolinera combustible gasolina estacion servicio peaje autopista taller mecanico neumaticos
transporte publico metro autobus tren renfe cabify didi tankstelle benzin kraftstoff
parkhaus maut bahn deutsche bahn werkstatt reifen essence carburant peage stationnement
sncf ratp benzina carburante pedaggio autostrada officina shell exxon chevron bp""",

"Insurance": """insurance premium policy coverage auto insurance health insurance life
insurance home insurance renters insurance liability deductible claim insurer underwriting
geico allstate state farm progressive nationwide liberty mutual seguro seguros poliza prima
aseguradora cobertura mapfre mutua axa allianz zurich generali versicherung police assurance
mutuelle assicurazione polizza seguradora previdencia farmers metlife""",

"Healthcare": """pharmacy drugstore chemist prescription rx clinic hospital doctor physician
medical center dental dentist orthodontist optometry optical vision eye care urgent care
laboratory lab diagnostics therapy physical therapy wellness health copay medicine
farmacia botica clinica hospital medico consultorio dentista optica salud laboratorio
urgencias receta apotheke arzt zahnarzt klinik krankenhaus gesundheit rezept labor
pharmacie medecin dentiste clinique sante hopital ordonnance farmacia medico dentista
ospedale salute cvs walgreens kaiser labcorp quest aetna""",

"Dining": """restaurant cafe coffee shop coffeehouse bar pub bistro diner grill kitchen
eatery tavern brasserie steakhouse pizzeria pizza sushi ramen taqueria burger fast food
bakery patisserie donuts food truck cantina buffet noodle wings barbecue bbq lunch dinner
restaurante cafeteria comedor bar cantina taqueria taco parrilla churreria panaderia
marisqueria cerveceria ristorante trattoria osteria pizzeria gelateria caffe kaffeehaus
imbiss gaststatte bierhaus baeckerei cafe restaurant boulangerie brasserie creperie
shack joint eatery grill house burger shack chicken shack sandwich shop juice bar smoothie
starbucks mcdonald chipotle dunkin panera subway kfc dominos grubhub doordash shake shack""",

"Entertainment": """cinema movie theater theatre movies concert live music venue festival
museum gallery amusement park zoo aquarium bowling arcade games gaming esports stadium arena
sports event tickets box office nightclub comedy show exhibition cine teatro concierto
festival museo galeria parque atracciones entradas boletos estadio espectaculo kino
theater konzert freizeitpark museum eintrittskarten stadion cinema concert spectacle
musee parc billets stade biglietti museo teatro amc regal ticketmaster steam playstation""",

"Shopping": """store shop retail department store boutique mall outlet clothing apparel
fashion shoes footwear electronics gadgets hardware furniture home goods bookstore toys
jewelry cosmetics beauty supply general merchandise online store marketplace tienda ropa
calzado zapatos electronica ferreteria muebles libreria jugueteria joyeria papeleria
almacen laden geschaeft bekleidung schuhe elektronik moebel buchhandlung spielwaren
boutique magasin vetements chaussures electronique meubles librairie negozio abbigliamento
department store galeries lafayette galerias mediamarkt media markt saturn el corte ingles
scarpe amazon target best buy ikea zara nike macys nordstrom etsy ebay walmart""",

"Subscriptions": """subscription membership monthly plan annual plan streaming service
music streaming video streaming cloud storage software license saas app store gym membership
fitness club news magazine digital subscription premium plus recurring suscripcion membresia
plan mensual streaming almacenamiento nube gimnasio revista suscripcion digital abo abonnement
mitgliedschaft streamingdienst fitnessstudio zeitschrift abonnement adhesion salle de sport
abbonamento palestra netflix spotify hulu disney prime youtube apple icloud adobe microsoft
patreon audible planet fitness dropbox notion""",
}


# ---- supporting keyword rules (multilingual, high-signal) -----------------
# Used as a SUPPORTING signal combined with the model — never the primary path.
STRONG = {}
def _r(cat, *ws):
    for w in ws:
        STRONG[w] = cat
_r("Healthcare", "pharmacy", "farmacia", "apotheke", "pharmacie", "rx", "drugstore", "botica",
   "dental", "dentista", "zahnarzt", "clinic", "clinica", "clinique", "hospital", "medico",
   "medecin", "arzt", "laboratorio", "labor", "quest", "walgreens", "cvs", "urgencias")
_r("Housing", "rent", "alquiler", "renta", "miete", "loyer", "affitto", "mortgage", "hipoteca",
   "inmobiliaria", "greystar", "landlord", "realty", "arriendo")
_r("Insurance", "insurance", "seguro", "seguros", "versicherung", "assurance", "assicurazione",
   "mapfre", "allianz", "geico", "progressive", "poliza", "aseguradora")
_r("Utilities", "electric", "electricidad", "strom", "iberdrola", "endesa", "telekom", "movistar",
   "vodafone", "comcast", "verizon", "edf", "enel", "coned", "utility", "factura", "elektrizitat")
_r("Transportation", "gas", "gasolina", "gasolinera", "benzin", "tankstelle", "essence", "carburant",
   "uber", "lyft", "taxi", "peaje", "toll", "parking", "sncf", "renfe", "bahn", "chevron",
   "exxon", "exxonmobil", "combustible")
_r("Dining", "restaurant", "restaurante", "ristorante", "trattoria", "cafe", "cafeteria", "coffee",
   "pizzeria", "taqueria", "boulangerie", "panaderia", "brasserie", "chipotle", "starbucks", "shack")
_r("Entertainment", "cinema", "kino", "cine", "movie", "theater", "theatre", "steam", "steamgames",
   "playstation", "xbox", "museo", "concierto", "amc", "concert")
_r("Groceries", "supermercado", "supermarket", "grocery", "mercado", "mercadona", "lidl", "aldi",
   "rewe", "carrefour", "sprouts", "kroger", "publix", "heb", "abarrotes")
_r("Subscriptions", "netflix", "spotify", "hulu", "disney", "subscription", "suscripcion",
   "membership", "gym", "gimnasio", "abo", "abonnement", "abbonamento", "adobe", "palestra")
_r("Shopping", "store", "tienda", "zara", "ikea", "mediamarkt", "amazon", "target", "nordstrom",
   "electronica", "ferreteria", "galeries", "lafayette", "bestbuy", "corte")


# Broad real-world merchant brands across regions — world knowledge that lifts
# coverage of common merchants and, via shared sub-word patterns, similar ones.
BRANDS = {
"Groceries": "safeway kroger publix wegmans meijer costco heb sprouts foodlion giant shoprite winco wincofoods stopandshop stater vons ralphs albertsons wholefoods traderjoes groceryoutlet oxxo soriana chedraui bodegaaurrera walmartsupercenter jumbo albertheijn intermarche auchan monoprix casino carrefour conad esselunga coop pam tesco sainsbury asda morrisons lidl aldi rewe edeka kaufland penny netto billa spar",
"Dining": "fiveguys jerseymikes wendys burgerking tacobell popeyes raisingcanes innout shakeshack sweetgreen cava dominos pizzahut papajohns littlecaesars olivegarden applebees chilis ihop dennys wafflehouse chickfila chipotle starbucks dunkin panera subway doordash grubhub ubereats postmates deliveroo justeat rappi pedidosya glovo kebab doner shawarma pho ramen bbq",
"Transportation": "shell exxon chevron mobil arco ampm valero conoco phillips marathon speedway circlek wawa quiktrip sheetz costcogas uber lyft ola didi cabify grab bolt uhaul penske budgettruck hertz enterprise avis spothero passportparking ezpass fastrak sunpass ypf axion petrobras copec repsol cepsa galp tankstelle aral esso autostrade telepass renfe trenitalia flixbus blablacar",
"Insurance": "geico allstate progressive statefarm nationwide libertymutual farmers usaa metlife prudential aetna cigna anthem mapfre axa allianz zurich generali mutua aseguradora",
"Healthcare": "cvs walgreens riteaid duanereade labcorp questdiagnostics onemedical zocdoc teladoc kaiser sutter clevelandclinic mayo lenscrafters warbyparker farmaciasguadalajara farmaciasahumada apotheke pharmacie farmacia clinica hospital laboratorio analisis dental dentist orthodontist optometrist",
"Utilities": "comcast xfinity spectrum verizon att tmobile metropcs cricket boostmobile sprint centurylink cox frontier pge coned dukeenergy nationalgrid dominion sce conedison edf engie iberdrola endesa naturgy enel eni telefonica movistar vodafone orange telekom telcel claro tim",
"Entertainment": "amc regal cinemark cinepolis fandango ticketmaster stubhub livenation eventbrite topgolf davebusters bowling museum zoo aquarium sixflags disneyland universal steam playstation xbox nintendo twitch fandom",
"Shopping": "amazon target bestbuy homedepot lowes ikea wayfair chewy michaels hobbylobby macys nordstrom kohls tjmaxx marshalls ross nike adidas lululemon gap oldnavy uniqlo sephora ulta decathlon leroymerlin mediamarkt saturn fnac elcorteingles bauhaus obi conforama zara hm mango",
"Subscriptions": "netflix spotify hulu disneyplus hbomax peacock paramount applemusic youtubepremium amazonprime audible kindle adobe microsoft dropbox icloud googleone notion github patreon substack nyt wsj economist lafitness planetfitness equinox peloton classpass",
}


def build_training_examples():
    """Return (texts, labels) — one example per whitespace token phrase is too
    sparse, so we use short phrases: split each category blob into overlapping
    1-3 word phrases to give the model diverse, realistic merchant-length inputs."""
    texts, labels = [], []
    for cat, blob in CORPUS.items():
        toks = blob.split()
        # single tokens
        for t in toks:
            texts.append(t); labels.append(cat)
        # 2- and 3-word phrases (sliding) — teaches multi-word merchant patterns
        for k in (2, 3):
            for i in range(len(toks) - k + 1):
                texts.append(" ".join(toks[i:i + k])); labels.append(cat)
    # real-brand world knowledge — each brand (weighted a few times so it registers)
    for cat, blob in BRANDS.items():
        for t in blob.split():
            for _ in range(3):
                texts.append(t); labels.append(cat)
    return texts, labels
