# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Privacy-preserving LOCAL merchant categorizer — three-stage on-device pipeline.

  1. Canonical merchant extraction (categorize_model.canonicalize): strip bank
     boilerplate, dates, phone numbers, txn ids, card prefixes, location codes.
  2. Local semantic classifier: a char n-gram logistic-regression text model
     (web/categorizer.json), trained on a rich multilingual corpus — it classifies
     PREVIOUSLY UNSEEN, abbreviated, and international merchants (not a dictionary).
  3. Local LLM fallback: a pluggable on-device refiner (`local_llm_refine`) for the
     lowest-confidence cases. No remote inference is ever called; if no on-device LLM
     runtime is wired, low-confidence items are labelled uncertain ("Other") and shown
     for OPTIONAL review — the run is never blocked and nothing is silently excluded.

Dictionary/keyword rules are a SUPPORTING signal folded into the score, not the
primary categorizer. The identical model + featurizer runs in the browser
(web/classifier.js), so classification can happen fully client-side. Zero network:
merchant text, model inputs/outputs, and learned mappings stay on the device.

Every classification returns {category, confidence, short_reason, model_stage},
where category is always one of CipherSpend's 10 fixed categories.
"""

import json
import math
import os

from reference import taxonomy
from . import categorize_model as CM

CATEGORIES = list(taxonomy.CATEGORY_NAMES)
_CATSET = set(CATEGORIES)

# confidence bands (policy): >=HIGH auto-accept quietly; >=MED auto-accept + optional
# review; <MED -> best-guess labelled uncertain ("Other") + optional review. None block.
CONF_HIGH = 0.70
CONF_MED = 0.45

_MODEL_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                           "web", "categorizer.json")


class _Model:
    """Loads the exported char-ngram linear model and runs inference (mirrors
    web/classifier.js exactly)."""

    def __init__(self, path=_MODEL_PATH):
        with open(path) as f:
            m = json.load(f)
        self.categories = m["categories"]
        self.vocab = {g: i for i, g in enumerate(m["vocab"])}
        self.coef = m["coef"]                 # [C][V]
        self.intercept = m["intercept"]       # [C]
        self.rules = m["rules"]               # token -> category
        self.rule_bonus = m.get("rule_bonus", 2.3)

    def scores(self, canonical):
        feats = CM.features(canonical)
        idx = [self.vocab[g] for g in feats if g in self.vocab]
        logits = list(self.intercept)
        for c in range(len(self.categories)):
            row = self.coef[c]
            s = 0.0
            for j in idx:
                s += row[j]
            logits[c] += s
        rule_hit = None
        for tok in canonical.split():
            cat = self.rules.get(tok)
            if cat in _CATSET:
                logits[self.categories.index(cat)] += self.rule_bonus
                rule_hit = tok
        return logits, rule_hit


_MODEL = None
def _model():
    global _MODEL
    if _MODEL is None:
        _MODEL = _Model()
    return _MODEL


def _softmax(logits):
    m = max(logits)
    e = [math.exp(v - m) for v in logits]
    s = sum(e)
    return [v / s for v in e]


# ---- stage 3 interface: optional on-device LLM refiner --------------------
def local_llm_refine(canonical, direction, candidates):
    """Refine a low-confidence classification with a SMALL LOCAL LLM (WebLLM /
    llama.cpp / equivalent on-device runtime). Must return None or a dict
    {category, confidence, short_reason} using ONLY the 10 fixed categories, and
    must make NO remote calls. No on-device LLM runtime is wired in this build, so
    this returns None and the caller falls back to the uncertain ("Other") label.
    """
    return None


def categorize(desc, direction=None, enable_llm=True):
    """Classify one description locally. Returns {category, confidence,
    short_reason, model_stage} — category is always one of the 10 fixed categories."""
    canonical = CM.canonicalize(desc)
    logits, rule_hit = _model().scores(canonical)   # empty text -> intercept-only best guess
    probs = _softmax(logits)
    top = max(range(len(probs)), key=lambda i: probs[i])
    cat, conf = CATEGORIES[top], probs[top]
    stage = "rules+classifier" if rule_hit else "classifier"
    reason = (f"matches '{rule_hit}' + spending patterns" if rule_hit
              else f"closest to {cat.lower()} spending patterns")

    if conf < CONF_MED and enable_llm:
        r = local_llm_refine(canonical, direction, CATEGORIES)
        if r and r.get("category") in _CATSET:
            return {"category": r["category"], "confidence": float(r.get("confidence", CONF_MED)),
                    "short_reason": r.get("short_reason", "local LLM"), "model_stage": "llm",
                    "canonical": canonical, "uncertain": r.get("confidence", CONF_MED) < CONF_MED}

    return {"category": cat, "confidence": round(float(conf), 3), "short_reason": reason,
            "model_stage": stage, "canonical": canonical, "uncertain": conf < CONF_MED}


# ---- persistent local cache + user corrections ----------------------------
class MerchantCache:
    """Local, on-device cache of canonical-merchant -> decision, incl. user
    corrections (reused at full confidence). Persisted to a JSON file under the
    gitignored run dir. Never leaves the device."""

    def __init__(self, path):
        self.path = path
        self.data = {}
        self._load()

    def _load(self):
        try:
            with open(self.path) as f:
                self.data = json.load(f)
        except (OSError, ValueError):
            self.data = {}

    def save(self):
        os.makedirs(os.path.dirname(self.path), exist_ok=True)
        tmp = self.path + ".tmp"
        with open(tmp, "w") as f:
            json.dump(self.data, f)
        os.replace(tmp, self.path)

    def get(self, key):
        return self.data.get(key)

    def put(self, key, category, source, confidence):
        if category in _CATSET or category == "__exclude__":
            self.data[key] = {"category": category, "source": source, "confidence": confidence}

    def set_user(self, key, category):
        self.put(key, category, "user", 1.0)


class Categorizer:
    """Classifies expense transactions locally with the non-blocking policy.

    Optional `client_categories` (canonical_key -> {category, confidence,
    model_stage}) lets categorization run in the browser and be reused here so the
    backend never re-does ML. `classifier_enabled=False` disables the model tier
    (for tests): then only user/cached/client decisions resolve, and everything
    else is uncertain — never silently categorized or dropped."""

    def __init__(self, cache_path=None, overrides=None, excluded_keys=None,
                 client_categories=None, classifier_enabled=True):
        self.cache = MerchantCache(cache_path) if cache_path else None
        self.overrides = dict(overrides or {})
        self.excluded_keys = set(excluded_keys or [])
        self.client = dict(client_categories or {})
        self.classifier_enabled = classifier_enabled

    def classify_one(self, desc):
        key = CM.canonicalize(desc) or (desc or "").strip().lower()
        # 1) explicit user decisions this session win
        if key in self.excluded_keys:
            return {"key": key, "category": "__exclude__", "confidence": 1.0, "source": "user",
                    "model_stage": "user", "flagged": False, "excluded": True, "uncertain": False}
        if key in self.overrides:
            return {"key": key, "category": self.overrides[key], "confidence": 1.0, "source": "user",
                    "model_stage": "user", "flagged": False, "excluded": False, "uncertain": False}
        # 2) persisted cache (incl. prior user corrections)
        if self.cache:
            c = self.cache.get(key)
            if c:
                excl = (c["category"] == "__exclude__")
                return {"key": key, "category": c["category"], "confidence": c.get("confidence", 0.9),
                        "source": c.get("source", "cache"), "model_stage": c.get("source", "cache"),
                        "flagged": False, "excluded": excl, "uncertain": False}
        # 3) classification supplied by the in-browser model, reused verbatim
        if key in self.client:
            cc = self.client[key]
            cat = cc.get("category")
            if cat in _CATSET:
                conf = float(cc.get("confidence", 0.5))
                return {"key": key, "category": cat, "confidence": conf,
                        "source": "client", "model_stage": cc.get("model_stage", "classifier"),
                        "flagged": conf < CONF_HIGH, "excluded": False, "uncertain": conf < CONF_MED}
        # 4) local model (server-side reference / fallback)
        if not self.classifier_enabled:
            return {"key": key, "category": None, "confidence": 0.0, "source": "disabled",
                    "model_stage": "none", "flagged": True, "excluded": False, "uncertain": True}
        r = categorize(desc)
        cat = r["category"]
        if cat not in _CATSET:                       # no merchant text -> uncertain, still reviewable
            return {"key": key, "category": None, "confidence": 0.0, "source": "unresolved",
                    "model_stage": r["model_stage"], "flagged": True, "excluded": False, "uncertain": True}
        out = {"key": key, "category": cat, "confidence": r["confidence"], "source": "model",
               "model_stage": r["model_stage"], "flagged": r["confidence"] < CONF_HIGH,
               "excluded": False, "uncertain": r["uncertain"]}
        if self.cache and out["confidence"] >= CONF_HIGH:   # remember confident auto decisions
            self.cache.put(key, cat, "model", out["confidence"])
        return out

    def commit_cache(self):
        if self.cache:
            self.cache.save()
