# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Canonical CSV import: inspect → configure (mapping/sign/categories) → validate.

Canonical columns: date, description, amount, category, type. The importer never
silently guesses ambiguous signs, transfers, refunds, duplicates, or currencies —
it surfaces them for an explicit decision and reports exactly what it did.
"""

import csv
import datetime
import io
import os
import re
from collections import Counter, defaultdict

from reference import taxonomy, layout
from reference.completeness import label_months
from reference.periods import week_bin, base_month, global_month_index  # noqa: F401
from . import categorize

TAXONOMY = list(taxonomy.CATEGORY_NAMES)
CANON_FIELDS = ["date", "description", "amount", "category", "type"]
MAX_TRANSACTIONS = 200_000
# local, on-device merchant->category cache (under the gitignored run dir)
CACHE_PATH = os.path.join(os.path.dirname(__file__), "run", "merchant_cache.json")

_CUR_BAD = re.compile(r"[€£¥₹₩]")                       # non-USD symbols -> don't guess FX
_TRANSFERish = re.compile(r"\b(transfer|refund|reversal|reimburse|cc\s*payment|"
                          r"credit\s*card\s*payment|payment\s*received|venmo|zelle|"
                          r"autopay|balance\s*adjustment)\b", re.I)
_INCOME_WORDS = ("income", "credit", "deposit", "payroll", "salary", "inflow")
_EXPENSE_WORDS = ("expense", "debit", "purchase", "withdrawal", "outflow", "payment")


def _norm(s):
    return (s or "").strip()


def _guess_col(headers, field):
    """Return (header, confidence) where confidence is 'exact' (header equals a
    known alias), 'fuzzy' (alias appears as a substring — a visible, changeable
    inference), or 'none' (no match; the UI must ask). Never a silent guess."""
    hl = [h.lower().strip() for h in headers]
    alias = {
        "date": ["date", "posted", "transaction date", "when"],
        "description": ["description", "desc", "memo", "name", "merchant", "payee", "details"],
        "amount": ["amount", "amt", "value", "debit/credit", "total"],
        "category": ["category", "cat", "type", "group", "bucket"],
        "type": ["type", "transaction type", "direction", "debit/credit", "flow"],
    }[field]
    for a in alias:
        if a in hl:
            return headers[hl.index(a)], "exact"
    for i, h in enumerate(hl):
        if any(a in h for a in alias):
            return headers[i], "fuzzy"
    return None, "none"


def _parse_amount(raw):
    """Return (value, error). Strips $ and thousands commas; rejects other currency."""
    s = _norm(raw)
    if s == "":
        return None, "empty amount"
    if _CUR_BAD.search(s):
        return None, "non-USD currency symbol (not auto-converted)"
    neg = s.startswith("(") and s.endswith(")")          # accounting negatives
    s2 = s.replace("(", "").replace(")", "").replace("$", "").replace(",", "").replace("USD", "").strip()
    try:
        v = float(s2)
    except ValueError:
        return None, f"amount not a number: {raw!r}"
    if neg:
        v = -abs(v)
    return v, None


def _parse_date(raw):
    s = _norm(raw)
    for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%m/%d/%y", "%d/%m/%Y", "%Y/%m/%d"):
        try:
            return datetime.date(*datetime.datetime.strptime(s, fmt).timetuple()[:3]), None
        except ValueError:
            continue
    return None, f"unrecognized date: {raw!r}"


def _read(text):
    reader = csv.reader(io.StringIO(text))
    rows = [r for r in reader if any(_norm(c) for c in r)]
    if not rows:
        return [], []
    return rows[0], rows[1:]


def inspect_csv(text, mapping=None):
    """First pass — detect structure and everything that needs a human decision.

    `mapping` (optional): a confirmed field->header map. When provided, categories,
    types, sign, and flags are re-derived from THOSE columns instead of the guessed
    ones — so if the user maps a category column the importer didn't auto-detect,
    its values surface for mapping (never silently left empty and dropped later).
    """
    headers, rows = _read(text)
    if not headers:
        return {"ok": False, "error": "empty or unreadable CSV"}
    idx = {h: i for i, h in enumerate(headers)}
    guesses = {f: _guess_col(headers, f) for f in CANON_FIELDS}
    valid = set(headers)
    if mapping:
        # honor the user's confirmed columns (ignoring any that no longer exist)
        suggested = {f: (mapping.get(f) if mapping.get(f) in valid else None) for f in CANON_FIELDS}
        mapping_confidence = {f: ("user" if suggested[f] else "none") for f in CANON_FIELDS}
    else:
        suggested = {f: g[0] for f, g in guesses.items()}
        mapping_confidence = {f: g[1] for f, g in guesses.items()}

    cat_col = suggested.get("category")
    type_col = suggested.get("type")
    amt_col = suggested.get("amount")
    def col(row, name):
        c = suggested.get(name)
        return row[idx[c]] if c and idx.get(c) is not None and idx[c] < len(row) else ""

    categories = sorted({_norm(col(r, "category")) for r in rows if _norm(col(r, "category"))})
    types = sorted({_norm(col(r, "type")) for r in rows if _norm(col(r, "type"))})
    # unique merchant descriptions so the browser can classify them locally (in-browser),
    # only when there's no category column (i.e. auto-categorization applies)
    descriptions = []
    if not cat_col:
        descriptions = sorted({_norm(col(r, "description")) for r in rows if _norm(col(r, "description"))})[:5000]

    negatives = positives = 0
    currency_bad = 0
    for r in rows:
        v, err = _parse_amount(col(r, "amount"))
        if err == "non-USD currency symbol (not auto-converted)":
            currency_bad += 1
        elif v is not None:
            if v < 0:
                negatives += 1
            elif v > 0:
                positives += 1

    transfer_like = sum(1 for r in rows if _TRANSFERish.search(col(r, "description")))
    seen = Counter(tuple(_norm(c) for c in r) for r in rows)
    duplicates = sum(c - 1 for c in seen.values() if c > 1)

    # suggested sign convention (a HINT — the user must confirm)
    if types:
        suggested_sign = "type_field"
    elif negatives and positives:
        suggested_sign = "amount_sign_neg_expense"
    else:
        suggested_sign = None                            # ambiguous -> force a choice

    # auto-suggest category mapping only for confident matches: an exact/case-
    # insensitive taxonomy name, or the reserved income label. Everything else is
    # None => the user must map it (never silently guessed).
    tax_lower = {t.lower(): t for t in TAXONOMY}
    income_lower = taxonomy.INCOME_LABEL.lower()
    cat_suggestion = {}
    for c in categories:
        cl = c.lower()
        if cl in tax_lower:
            cat_suggestion[c] = tax_lower[cl]
        elif cl == income_lower:
            cat_suggestion[c] = "Income"
        else:
            cat_suggestion[c] = None

    type_suggestion = {}
    for t in types:
        tl = t.lower()
        if any(w in tl for w in _INCOME_WORDS):
            type_suggestion[t] = "income"
        elif any(w in tl for w in _EXPENSE_WORDS):
            type_suggestion[t] = "expense"
        else:
            type_suggestion[t] = None                    # user must map

    dates = [d for d, _ in (_parse_date(col(r, "date")) for r in rows) if d]
    date_range = ([min(dates).isoformat(), max(dates).isoformat()] if dates else None)

    return {
        "ok": True, "headers": headers, "row_count": len(rows),
        "sample": [dict(zip(headers, r)) for r in rows[:6]],
        "suggested_mapping": suggested, "mapping_confidence": mapping_confidence,
        "categories": categories, "types": types, "descriptions": descriptions,
        "suggested_category_map": cat_suggestion,
        "suggested_type_map": type_suggestion,
        "sign_options": ["type_field", "amount_sign_neg_expense", "amount_sign_pos_expense"],
        "suggested_sign": suggested_sign,
        "taxonomy": TAXONOMY,
        "flags": {"negatives": negatives, "positives": positives, "currency_symbols": currency_bad,
                  "transfer_like": transfer_like, "duplicates": duplicates},
        "date_range": date_range,
    }


def build_transactions(text, cfg):
    """Second pass — apply the confirmed config, validate, and build transactions.

    cfg keys: mapping{date,description,amount,category,type}, sign_mode,
    category_map{src->taxonomy|"Income"|"Exclude"}, type_map{src->income|expense|exclude},
    include_flagged(bool).
    Returns (transactions, report). transactions match the shape build_batches expects.
    """
    headers, rows = _read(text)
    idx = {h: i for i, h in enumerate(headers)}
    m = cfg.get("mapping", {})
    sign_mode = cfg.get("sign_mode")
    cat_map = cfg.get("category_map", {})
    type_map = cfg.get("type_map", {})
    include_flagged = bool(cfg.get("include_flagged", False))

    # LOCAL auto-categorization (for CSVs without a category column). Runs entirely
    # on-device; merchant descriptions never leave the machine (no network calls).
    auto_categorize = bool(cfg.get("auto_categorize", False))
    overrides = cfg.get("category_overrides", {}) or {}      # {key: category} from optional user review
    excluded_keys = set(cfg.get("excluded_merchants", []) or [])
    client_categories = cfg.get("client_categories", {}) or {}   # {key: {...}} from the in-browser model
    categorizer = None
    if auto_categorize:
        categorizer = categorize.Categorizer(
            cache_path=(CACHE_PATH if cfg.get("use_cache", True) else None),
            overrides=overrides, excluded_keys=excluded_keys,
            client_categories=client_categories,
            classifier_enabled=bool(cfg.get("classifier_enabled", True)))
        if categorizer.cache is not None:                   # persist user corrections locally
            for k, vcat in overrides.items():
                categorizer.cache.set_user(k, vcat)
            for k in excluded_keys:
                categorizer.cache.set_user(k, "__exclude__")
    # non-blocking policy: everything gets a best-guess category; low-confidence is
    # analyzed AND surfaced for OPTIONAL review; only truly uncategorizable rows
    # (empty text / classifier disabled) are held back — never silently dropped.
    review, uncat = {}, {}
    cat_stats = {"auto": 0, "flagged": 0, "other": 0, "user_excluded": 0, "user_fixed": 0}

    def cell(r, field):
        c = m.get(field)
        return r[idx[c]] if c and idx.get(c) is not None and idx[c] < len(r) else ""

    txns, invalid, warnings = [], [], []
    excluded = defaultdict(int)
    seen = Counter()

    if sign_mode not in ("type_field", "amount_sign_neg_expense", "amount_sign_pos_expense"):
        return [], {"ok": False, "error": "sign convention not confirmed"}

    for n, r in enumerate(rows, start=2):                 # row 1 is the header
        key = (_norm(cell(r, "date")), _norm(cell(r, "amount")), _norm(cell(r, "description")))
        seen[key] += 1

        d, derr = _parse_date(cell(r, "date"))
        v, verr = _parse_amount(cell(r, "amount"))
        if derr:
            invalid.append({"row": n, "reason": derr, "kind": "date"}); continue
        if verr:
            invalid.append({"row": n, "reason": verr,
                            "kind": "currency" if "currency" in verr else "amount"}); continue
        if v == 0:
            invalid.append({"row": n, "reason": "zero amount", "kind": "zero"}); continue

        desc = _norm(cell(r, "description"))
        # determine income vs expense (no silent guessing)
        if sign_mode == "type_field":
            tv = _norm(cell(r, "type"))
            mapped = type_map.get(tv)
            if mapped is None:
                invalid.append({"row": n, "reason": f"unmapped transaction type {tv!r}",
                                "kind": "unmapped_type"}); continue
            if mapped == "exclude":
                excluded["type"] += 1; continue
            kind = mapped
            amount = abs(v)
        else:
            neg_is_expense = (sign_mode == "amount_sign_neg_expense")
            is_expense = (v < 0) if neg_is_expense else (v > 0)
            kind = "expense" if is_expense else "income"
            amount = abs(v)

        # transfers/refunds: never silently included; excluded unless opted in
        if _TRANSFERish.search(desc) and not include_flagged:
            excluded["transfer_refund"] += 1; continue

        if kind == "income":
            txns.append({"date": d, "amount": amount, "type": "income",
                         "category": taxonomy.INCOME_LABEL, "category_index": None, "description": desc})
        else:
            src = _norm(cell(r, "category"))
            mapped = cat_map.get(src) if src else None
            auto_source = None
            if mapped is None and categorizer is not None:
                # infer the category LOCALLY from the merchant description (non-blocking)
                dcz = categorizer.classify_one(desc)
                if dcz["excluded"]:                        # user explicitly excluded this merchant
                    excluded["user_uncategorized"] += 1; cat_stats["user_excluded"] += 1; continue
                if dcz["category"] not in taxonomy.CATEGORY_INDEX:
                    # uncategorizable (empty text / classifier disabled) — held back for
                    # attention, never analyzed silently and never dropped
                    it = uncat.setdefault(dcz["key"], {"key": dcz["key"], "sample": desc[:60], "count": 0})
                    it["count"] += 1
                    continue
                mapped = dcz["category"]; auto_source = dcz["model_stage"]
                if dcz["source"] == "user":
                    cat_stats["user_fixed"] += 1
                elif dcz["uncertain"]:
                    cat_stats["other"] += 1                # very low confidence: analyzed as best guess, labelled "Other"
                elif dcz["flagged"]:
                    cat_stats["flagged"] += 1              # medium: analyzed, optional review
                else:
                    cat_stats["auto"] += 1                 # high confidence
                if dcz["flagged"] and dcz["source"] not in ("user", "cache"):
                    it = review.setdefault(dcz["key"], {
                        "key": dcz["key"], "sample": desc[:60], "suggested": mapped,
                        "confidence": dcz["confidence"], "model_stage": dcz["model_stage"],
                        "uncertain": dcz["uncertain"], "count": 0})
                    it["count"] += 1
            if mapped is None:
                invalid.append({"row": n, "reason": f"unmapped category {src!r}",
                                "kind": "unmapped_category"}); continue
            if mapped == "Exclude":
                excluded["category"] += 1; continue
            if mapped == "Income":                        # a category the user marks as income
                txns.append({"date": d, "amount": amount, "type": "income",
                             "category": taxonomy.INCOME_LABEL, "category_index": None, "description": desc})
                continue
            if mapped not in taxonomy.CATEGORY_INDEX:
                invalid.append({"row": n, "reason": f"category maps to unknown taxonomy {mapped!r}",
                                "kind": "unmapped_category"}); continue
            txn = {"date": d, "amount": amount, "type": "expense", "category": mapped,
                   "category_index": taxonomy.category_index(mapped), "description": desc}
            if auto_source:
                txn["categorized_by"] = auto_source
            txns.append(txn)

    if categorizer is not None:
        categorizer.commit_cache()                        # retain auto + user decisions locally

    dup = sum(c - 1 for c in seen.values() if c > 1)
    if dup:
        warnings.append(f"{dup} exact-duplicate row(s) kept — review if unintended (not auto-removed).")
    if excluded.get("transfer_refund"):
        warnings.append(f"{excluded['transfer_refund']} transfer/refund-like row(s) excluded — "
                        "enable 'include flagged' to keep them.")
    if excluded.get("category"):
        warnings.append(f"{excluded['category']} row(s) excluded by category mapping.")
    if len(txns) > MAX_TRANSACTIONS:
        return [], {"ok": False, "error": f"too many transactions ({len(txns)} > {MAX_TRANSACTIONS})"}

    dates = [t["date"] for t in txns]
    months = []
    if dates:
        for lab in label_months(dates):
            months.append({"label": f"{lab['year']:04d}-{lab['month']:02d}", "complete": lab["complete"],
                           "coverage_days": lab["coverage_days"], "days_in_month": lab["days_in_month"]})
    partial = [mo["label"] for mo in months if not mo["complete"]]
    if partial:
        warnings.append(f"Partial month(s) detected and excluded from trends/baselines: {', '.join(partial)}.")

    exp = [t for t in txns if t["type"] == "expense"]
    inc = [t for t in txns if t["type"] == "income"]

    # group skipped rows by kind so the preview can say exactly what was set aside
    invalid_summary = Counter(iv.get("kind", "other") for iv in invalid)

    # estimate how many encrypted batches this history spans (12 months each), the
    # same grouping the pipeline uses — surfaced honestly (longer history == more
    # batches == a coarser history-length signal the server can infer).
    est_batches = 0
    if dates:
        b = base_month(dates)
        est_batches = len({global_month_index(d, b) // layout.MONTHS_PER_BATCH for d in dates})

    review_items = sorted(review.values(), key=lambda x: (-x["count"], x["confidence"]))
    flagged = sum(it["count"] for it in review_items)     # OPTIONAL review (analyzed already)
    uncat_items = sorted(uncat.values(), key=lambda x: -x["count"])
    uncategorized = sum(it["count"] for it in uncat_items)   # held back (rare: empty text / disabled)
    if uncategorized:
        warnings.append(f"{uncategorized} expense(s) had no usable merchant text to categorize — "
                        "held for your attention, not analyzed, and not dropped.")

    report = {
        # analysis proceeds on usable transactions; invalid rows are skipped and
        # reported, not treated as a hard failure.
        "ok": len(txns) > 0,
        # READY unless it's structurally invalid: nothing usable, or (rare) the
        # categorizer couldn't run and expenses are uncategorizable. OPTIONAL review
        # of low-confidence classifications never blocks the run.
        "ready": len(txns) > 0 and uncategorized == 0,
        "has_invalid": len(invalid) > 0,
        "rows_total": len(rows),   # every data row read from the file (the "Y" in "X of Y")
        "counts": {"total": len(txns), "expense": len(exp), "income": len(inc),
                   "invalid": len(invalid), "excluded": sum(excluded.values()),
                   "flagged": flagged, "uncategorized": uncategorized},
        "totals": {"spend": round(sum(t["amount"] for t in exp), 2),
                   "income": round(sum(t["amount"] for t in inc), 2)},
        "invalid_rows": invalid[:200], "invalid_truncated": max(0, len(invalid) - 200),
        "invalid_summary": dict(invalid_summary),
        "excluded_summary": dict(excluded),
        "categorization": {"enabled": auto_categorize, "auto": cat_stats["auto"],
                           "flagged": cat_stats["flagged"], "other": cat_stats["other"],
                           "user_excluded": cat_stats["user_excluded"], "user_fixed": cat_stats["user_fixed"],
                           "review_items": review_items[:200], "uncategorized_items": uncat_items[:100]},
        "flagged": flagged, "uncategorized": uncategorized,
        "warnings": warnings, "months": months,
        "complete_months": sum(1 for mo in months if mo["complete"]),
        "partial_months": len(partial),
        "est_batches": est_batches, "months_per_batch": layout.MONTHS_PER_BATCH,
        "sign_mode": sign_mode,
    }
    if not txns and not invalid and not uncategorized:
        report["error"] = "no usable transactions after import"
    return txns, report
