# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Deterministic demo dataset — the approved, verified 14-month story rendered as
individual transactions. It is passed to the SAME orchestrator (real CKKS + real
Stage-6 analytics) as uploaded data; nothing about the demo path is special-cased.

Events (verified in scratchpad/verify.js): Aug 2024 travel, Dec 2024 holiday +
year-end bonus, Feb 2025 one-off medical bill, Mar 2025 lean month, mid-year raise.
Per-(month,category) transaction amounts sum exactly to the verified monthly totals.
"""

import datetime

from reference import taxonomy

MONTHNAMES = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
CAT_MODELS = [
    ("Housing", 2148, .004, 0, 0), ("Utilities", 166, .06, 0, .30),
    ("Groceries", 628, .09, 2.1, 0), ("Transportation", 284, .13, .7, 0),
    ("Insurance", 243, .01, 0, 0), ("Healthcare", 71, .30, 0, 0),
    ("Dining", 352, .10, 11, 0), ("Entertainment", 157, .16, 0, 0),
    ("Shopping", 262, .18, 0, 0), ("Subscriptions", 68, .03, 2.6, 0),
]
MERCHANTS = {
    "Housing": ["Rent"], "Utilities": ["City Power", "Water Dept", "Fiber Internet"],
    "Groceries": ["Whole Foods", "Trader Joe's", "Safeway", "Costco", "Corner Market"],
    "Transportation": ["Shell", "Uber", "Transit Card", "Chevron", "Parking"],
    "Insurance": ["Auto Insurance", "Renters Insurance"],
    "Healthcare": ["Clinic Copay", "Pharmacy", "Dental", "Medical Center"],
    "Dining": ["Chipotle", "Blue Bottle", "Trattoria", "DoorDash", "Ramen Bar", "Taco Stand"],
    "Entertainment": ["AMC Theaters", "Concert Tickets", "Steam", "Museum"],
    "Shopping": ["Amazon", "Target", "Uniqlo", "Best Buy", "REI"],
    "Subscriptions": ["Netflix", "Spotify", "iCloud", "News+"],
}
TYPICAL_COUNT = {"Housing": 1, "Utilities": 2, "Groceries": 8, "Transportation": 6,
                 "Insurance": 1, "Healthcare": 1, "Dining": 9, "Entertainment": 3,
                 "Shopping": 5, "Subscriptions": 3}


def mulberry32(a):
    a &= 0xFFFFFFFF
    def rnd():
        nonlocal a
        a = (a + 0x6D2B79F5) & 0xFFFFFFFF
        t = a
        t = (t ^ (t >> 15)) * (t | 1) & 0xFFFFFFFF
        t ^= (t + ((t ^ (t >> 7)) * (t | 61) & 0xFFFFFFFF)) & 0xFFFFFFFF
        return ((t ^ (t >> 14)) & 0xFFFFFFFF) / 4294967296
    return rnd


def _days_in(y, m):
    return (datetime.date(y + (m // 12), (m % 12) + 1, 1) - datetime.timedelta(days=1)).day


def _split(total, k, rnd):
    """Split `total` into k positive amounts (2dp) that sum exactly to total."""
    if k <= 1 or total <= 0:
        return [round(total, 2)]
    ws = [0.5 + rnd() for _ in range(k)]
    s = sum(ws)
    parts = [round(total * w / s, 2) for w in ws]
    parts[-1] = round(total - sum(parts[:-1]), 2)
    return [p for p in parts if p > 0] or [round(total, 2)]


def monthly_targets():
    """Reproduce the verified monthly category totals + income (matches verify.js)."""
    rng = mulberry32(20260811)
    out = []
    y, mo = 2024, 6
    for i in range(14):
        partial = (i == 13)
        mn = MONTHNAMES[mo - 1]
        income = 6180 + (690 if i >= 7 else 0)
        income *= (1 + (rng() * 2 - 1) * .009)
        if mn == "Dec":
            income += 3760 + round(rng() * 260)
        if i == 9:
            income = 4260 + round(rng() * 130)
        cats = {}
        for (n, base, noise, drift, seas) in CAT_MODELS:
            amt = base + drift * i
            if seas:
                w = 1 if mn in ("Nov", "Dec", "Jan", "Feb") else -.45
                amt *= 1 + seas * w * .5
            amt *= (1 + (rng() * 2 - 1) * noise)
            if i == 2:
                amt *= {"Transportation": 2.8, "Dining": 1.5, "Entertainment": 1.85, "Shopping": 1.3}.get(n, 1)
            if mn == "Dec":
                amt *= {"Shopping": 2.45, "Entertainment": 1.8, "Dining": 1.28}.get(n, 1)
            if i == 8 and n == "Healthcare":
                amt = 890 + round(rng() * 160)
            cats[n] = max(0.0, round(amt, 2))
        sc = .4 if partial else 1.0
        cats = {n: round(v * sc, 2) for n, v in cats.items()}
        income = round(income * sc, 2)
        out.append({"y": y, "mo": mo, "partial": partial, "income": income, "cats": cats})
        mo += 1
        if mo > 12:
            mo, y = 1, y + 1
    return out


def generate_transactions():
    """Explode monthly targets into individual transactions (canonical shape)."""
    rng = mulberry32(0x5EED1234)
    txns = []
    for rec in monthly_targets():
        y, mo, dim = rec["y"], rec["mo"], _days_in(rec["y"], rec["mo"])
        maxday = 12 if rec["partial"] else dim
        # income: two payroll deposits (+ a labeled bonus deposit in December)
        mn = MONTHNAMES[mo - 1]
        base_income = rec["income"]
        bonus = round(base_income * 0.38, 2) if mn == "Dec" else 0.0
        payroll = base_income - bonus
        for k, day in enumerate((1, min(15, maxday))):
            amt = round(payroll / 2, 2) if k == 0 else round(payroll - round(payroll / 2, 2), 2)
            if amt > 0:
                txns.append(_txn(y, mo, day, amt, taxonomy.INCOME_LABEL, "income", "Payroll"))
        if bonus > 0:
            txns.append(_txn(y, mo, min(20, maxday), round(bonus, 2), taxonomy.INCOME_LABEL, "income", "Year-end bonus"))
        # expenses per category
        for name, total in rec["cats"].items():
            if total <= 0:
                continue
            k = max(1, min(TYPICAL_COUNT.get(name, 3), 1 + int(total // 60)))
            if name in ("Housing", "Insurance"):
                k = 1
            parts = _split(total, k, rng)
            merchants = MERCHANTS[name]
            for j, amt in enumerate(parts):
                day = 1 + int(rng() * (maxday - 1))
                if name == "Housing":
                    day = 1
                desc = merchants[int(rng() * len(merchants)) % len(merchants)]
                txns.append(_txn(y, mo, day, amt, name, "expense", desc))
    txns.sort(key=lambda t: (t["date"], t["description"]))
    return txns


def _txn(y, mo, day, amount, category, ttype, desc):
    ci = None if ttype == "income" else taxonomy.category_index(category)
    return {"date": datetime.date(y, mo, max(1, day)), "amount": round(amount, 2),
            "type": ttype, "category": category, "category_index": ci, "description": desc}


def example_csv():
    """A tiny, clean canonical example for the 'download example' affordance."""
    return ("date,description,amount,category,type\n"
            "2025-01-03,Rent,2150.00,Housing,expense\n"
            "2025-01-05,Payroll,3100.00,Income,income\n"
            "2025-01-06,Whole Foods,84.20,Groceries,expense\n"
            "2025-01-09,Shell,52.10,Transportation,expense\n"
            "2025-01-12,Chipotle,14.75,Dining,expense\n"
            "2025-01-15,Payroll,3100.00,Income,income\n"
            "2025-01-18,Netflix,15.99,Subscriptions,expense\n"
            "2025-01-22,Amazon,63.40,Shopping,expense\n")


def demo_csv():
    """The full demo story as a canonical CSV (used for the demo download)."""
    lines = ["date,description,amount,category,type"]
    for t in generate_transactions():
        lines.append(f"{t['date'].isoformat()},{t['description']},{t['amount']:.2f},{t['category']},{t['type']}")
    return "\n".join(lines) + "\n"
