# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Orchestrator: transactions -> real CKKS pipeline -> Stage-6 analytics -> result.

The SINGLE entry point both the demo and uploaded CSVs flow through, so they run
the identical real pipeline. Attaches per-month stories (Stage-6 story engine) and
"smart defaults" so the first view of every screen opens on a real insight.
"""

import sys
import time

from . import pipeline
from .pipeline import ROOT

if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

from reference.periods import base_month, global_month_index
from reference.completeness import label_months
from analytics import build_result
from analytics import timeline as TL
from analytics import story as ST


def _labels(transactions):
    dates = [t["date"] for t in transactions]
    return label_months(dates), base_month(dates)


def _salience(mom):
    """How 'interesting' a month-over-month change is (for smart defaults)."""
    def relv(node):
        return abs(node["rel"]["value"]) if node and node.get("rel", {}).get("defined") else 0.0
    def dv(node):
        return abs(node["value"]) if node and node.get("defined") else 0.0
    pp = mom.get("category_pp_deltas") or [0]
    return max(relv(mom.get("total_spending")), relv(mom.get("total_income")),
              dv(mom.get("cash_flow_index_delta")), max(abs(p) for p in pp) / 100.0)


def _attach_stories_and_defaults(result):
    by_gm = {m["global_m"]: m for m in result["months"]}
    complete = [m for m in result["months"] if m["complete"]]
    month_stories = {}
    for i in range(1, len(complete)):
        prev, cur = complete[i - 1], complete[i]
        cmp = TL.compare_months(prev, cur)
        head = ST.headline_card(cmp)
        soc = ST.source_of_change(cmp)
        factors = soc["evidence"]["factors"]
        driver = soc["evidence"]["driver"]
        driver_val = factors[driver]
        month_stories[str(cur["global_m"])] = {
            "from": prev["label"], "headline": head["title"], "headline_kind": head["kind"],
            "cards": [{"title": c["title"], "detail": c["detail"]} for c in ST.category_change_cards(cmp)],
            "source": {"driver": driver, "val": float(driver_val), "dominant": bool(driver_val >= 0.02)},
            "stable": ST.stable_categories(cmp),
            "involves_partial": cmp.get("involves_partial", False),
        }
    result["month_stories"] = month_stories

    # smart defaults: dashboard = most salient complete month; compare = most different adjacent pair
    moms = result["timeline"]["month_over_month"]
    all_months = result["months"]
    dash_gm = (complete[-1]["global_m"] if complete
               else (all_months[-1]["global_m"] if all_months else None))  # fall back to any month
    if moms:
        best = max(moms, key=_salience)
        dash_gm = best["to_gm"]
        least_similar = min(moms, key=lambda m: (m.get("cosine", {}).get("value") if m.get("cosine", {}).get("defined") else 1.0))
        ca, cb = least_similar["from_gm"], least_similar["to_gm"]
    elif len(complete) >= 1:
        ca = cb = complete[-1]["global_m"]
    else:
        ca = cb = (result["months"][0]["global_m"] if result["months"] else 0)
    result["defaults"] = {"dashboard_gm": dash_gm, "compare_a_gm": ca, "compare_b_gm": cb}
    result["default_compare"] = compare_pair(result, ca, cb)  # precomputed so Compare needs no fetch on load
    return result


def analyze(transactions, job_id, emit=None):
    """Full run. emit(event) streams real stage progress. Returns the result dict."""
    emit = emit or (lambda e: None)
    labels, base = _labels(transactions)

    # build the agg over the REAL CKKS pipeline (reuses Stage-3 packing + Stage-5 binaries)
    agg, pinfo = pipeline.run_pipeline(transactions, base, job_id, emit=emit)

    # Stage-6 analytics (reused, not duplicated)
    t0 = time.perf_counter()
    result = build_result(agg, labels)
    result = _attach_stories_and_defaults(result)
    emit({"stage": "analytics", "ms": round((time.perf_counter() - t0) * 1000),
          "detail": f"{result['counts']['months_total']} months analyzed on device"})

    result["pipeline"] = {
        "num_batches": pinfo["num_batches"],
        "ciphertext_in_mb": round(pinfo["in_bytes"] / 1e6, 2),
        "ciphertext_out_mb": round(pinfo["out_bytes"] / 1e6, 2),
        "rotation_keys_mb": round(pinfo["keys"]["rotation_keys_bytes"] / 1e6, 2),
        "scheme": "CKKS", "ring_dimension": 65536, "security": "HEStd_128_classic",
    }
    result["source"] = {"transactions": len(transactions)}
    return result


def compare_pair(result, a_gm, b_gm):
    """Arbitrary two-month comparison for the Compare screen — reuses Stage-6."""
    by_gm = {m["global_m"]: m for m in result["months"]}
    if a_gm not in by_gm or b_gm not in by_gm:
        return None
    cmp = TL.compare_months(by_gm[a_gm], by_gm[b_gm])
    cmp["stories"] = {"source": ST.source_of_change(cmp)}
    return cmp
