# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Real CKKS four-program pipeline runner.

Reuses the Stage-3 packing (`reference.twin.build_batches`) and the compiled
Stage-5 binaries (keygen / encrypt / server / decrypt). Emits real per-stage
timings and ciphertext byte sizes — no fake timers. The secret key is written
only to the client home; the server home never receives it (the server binary
also refuses to run if a secret key is present — preserved from Stage 5).
"""

import os
import shutil
import subprocess
import sys
import time

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

from reference.twin import build_batches           # Stage-3, tested
from reference import scaling, layout              # Stage-3 layout constants

BIN = os.path.join(ROOT, "stage5", "build")
RUN = os.path.join(ROOT, "app", "run")
CLIENT_HOME = os.path.join(RUN, "client_home")     # holds the SECRET key — device only
SERVER_HOME = os.path.join(RUN, "server_home")     # context + eval keys only, no sk

CT1_TARGETS, CT2_TARGETS = 120, 72                 # target slots per the approved layout


class PipelineError(RuntimeError):
    pass


def _run(cmd):
    t0 = time.perf_counter()
    p = subprocess.run(cmd, capture_output=True, text=True)
    dt = time.perf_counter() - t0
    # Observability: log the real Stage-5 OpenFHE executable PATH, exit code, and
    # wall-clock duration to the local server log. Contains no transaction values
    # (only the binary path, return code, and timing) — safe to log, local-only.
    print(f"[stage5] exec {cmd[0]} rc={p.returncode} in {dt*1000:.0f} ms",
          file=sys.stderr, flush=True)
    if p.returncode != 0:
        # Note: stderr from our binaries never contains transaction values.
        raise PipelineError(f"{os.path.basename(cmd[0])} failed ({p.returncode}): {p.stderr.strip()}")
    return dt, p.stdout.strip()


def _restrict_key_perms():
    """Confine the CKKS secret key to the owner: 0700 on the client home dir,
    0600 on sk.bin, so it is not world-readable on a multi-user host. Best-effort
    (no-op on platforms without POSIX modes)."""
    try:
        os.chmod(CLIENT_HOME, 0o700)
        sk = os.path.join(CLIENT_HOME, "sk.bin")
        if os.path.exists(sk):
            os.chmod(sk, 0o600)
    except OSError:
        pass


def ensure_keys():
    """Generate the CKKS context + keys once (data-independent), reused across
    requests. Returns measured key/context sizes plus whether this call actually
    created the keys (vs. found them already on device) and the real keygen time,
    so the UI can surface a truthful device key-creation moment. Enforces
    sk-client-only."""
    cc = os.path.join(CLIENT_HOME, "cc.bin")
    existed = os.path.exists(cc) and os.path.exists(os.path.join(SERVER_HOME, "rotkeys.bin"))
    keygen_ms = 0
    if not existed:
        os.makedirs(RUN, exist_ok=True)
        dt, _ = _run([os.path.join(BIN, "keygen"), CLIENT_HOME, SERVER_HOME])
        keygen_ms = round(dt * 1000)
        _restrict_key_perms()
        _log_artifacts("key", [os.path.join(CLIENT_HOME, f) for f in ("cc.bin", "pk.bin", "sk.bin")]
                       + [os.path.join(SERVER_HOME, f) for f in ("cc.bin", "rotkeys.bin")])
    # trust-boundary invariant: the server home must never hold the secret key
    if os.path.exists(os.path.join(SERVER_HOME, "sk.bin")):
        raise PipelineError("secret key present in server home — refusing")
    size = lambda d, f: os.path.getsize(os.path.join(d, f))
    return {
        "created": not existed,
        "keygen_ms": keygen_ms,
        "public_key_bytes": size(CLIENT_HOME, "pk.bin"),
        "secret_key_bytes": size(CLIENT_HOME, "sk.bin"),
        "rotation_keys_bytes": size(SERVER_HOME, "rotkeys.bin"),
        "context_bytes": size(CLIENT_HOME, "cc.bin"),
    }


def _export_packed(batches, packed_dir):
    os.makedirs(packed_dir, exist_ok=True)
    for i, b in enumerate(batches):
        b.ct1.astype("<f8").tofile(os.path.join(packed_dir, f"batch{i}_ct1.f64"))
        b.ct2.astype("<f8").tofile(os.path.join(packed_dir, f"batch{i}_ct2.f64"))


def _dir_bytes(d, suffix):
    return sum(os.path.getsize(os.path.join(d, f)) for f in os.listdir(d) if f.endswith(suffix))


def _log_artifacts(label, paths):
    """Log each freshly-written crypto artifact's path, size, and mtime to the local
    server log (metadata only — never any transaction values)."""
    for pth in paths:
        try:
            st = os.stat(pth)
            print(f"[stage5] artifact {label}: {pth}  {st.st_size} bytes  mtime={st.st_mtime:.3f}",
                  file=sys.stderr, flush=True)
        except OSError:
            pass


def _files(d, suffix):
    return sorted(os.path.join(d, f) for f in os.listdir(d) if f.endswith(suffix)) if os.path.isdir(d) else []


def _recombine(batches, dec_dir, scale):
    """Sum decrypted target slots across batches (additive) and reverse scaling.
    Mirrors the Stage-5 harness recombination; produces the {cat,week,income} agg."""
    from collections import defaultdict
    cat, week, income = defaultdict(float), defaultdict(float), defaultdict(float)
    for i, b in enumerate(batches):
        a1 = np.fromfile(os.path.join(dec_dir, f"batch{i}_ct1.f64"), dtype="<f8", count=CT1_TARGETS)
        a2 = np.fromfile(os.path.join(dec_dir, f"batch{i}_ct2.f64"), dtype="<f8", count=CT2_TARGETS)
        base = b.group * layout.MONTHS_PER_BATCH
        for mm in range(layout.MONTHS_PER_BATCH):
            gm = base + mm
            for c in range(layout.N_CATEGORIES):
                cat[(gm, c)] += a1[mm * 10 + c]
            for w in range(layout.WEEK_BINS):
                week[(gm, w)] += a2[mm * 5 + w]
            income[gm] += a2[layout.INCOME_BASE + mm]
    unscale = scaling.unscale
    return {"cat": {k: unscale(v, scale) for k, v in cat.items()},
            "week": {k: unscale(v, scale) for k, v in week.items()},
            "income": {k: unscale(v, scale) for k, v in income.items()}}


def run_pipeline(transactions, base, job_id, scale=scaling.DEFAULT_SCALE, emit=None):
    """Run the real CKKS pipeline over `transactions`.

    emit(stage_dict) is called after each stage with real timings/sizes so the UI
    can reflect the actual pipeline. Returns (agg, stages).
    """
    emit = emit or (lambda s: None)
    keys = ensure_keys()

    job = os.path.join(RUN, "jobs", job_id)
    packed, inct, outct, dec = (os.path.join(job, d) for d in ("packed", "in", "out", "dec"))
    for d in (packed, inct, outct, dec):
        os.makedirs(d, exist_ok=True)

    # Stage: read & categorize / pack (on device) — reuse Stage-3 build_batches
    t0 = time.perf_counter()
    batches, meta = build_batches(transactions, base=base, scale=scale)
    nb = len(batches)
    _export_packed(batches, packed)
    emit({"stage": "read", "ms": round((time.perf_counter() - t0) * 1000),
          "detail": f"{len(transactions)} transactions · {nb} encrypted batch(es)"})

    # Stage: encrypt locally
    dt, _ = _run([os.path.join(BIN, "encrypt"), CLIENT_HOME, packed, inct, str(nb)])
    in_bytes = _dir_bytes(inct, "_in.bin")
    _log_artifacts("ciphertext-in", _files(inct, "_in.bin"))
    emit({"stage": "encrypt", "ms": round(dt * 1000), "detail": f"{nb*2} ciphertexts encoded"})

    # Stage: upload (local file handoff to the server home) — measure real bytes
    t0 = time.perf_counter()
    emit({"stage": "upload", "ms": round((time.perf_counter() - t0) * 1000),
          "bytes": in_bytes, "detail": f"{in_bytes/1e6:.2f} MB ciphertext"})

    # Stage: compute on encrypted data (server binary — no secret key)
    dt, _ = _run([os.path.join(BIN, "server"), SERVER_HOME, inct, outct, str(nb)])
    out_bytes = _dir_bytes(outct, "_out.bin")
    _log_artifacts("evaluated-out", _files(outct, "_out.bin"))
    emit({"stage": "compute", "ms": round(dt * 1000),
          "detail": "folded encrypted aggregates (depth 0, 6 rotations)"})

    # Stage: return encrypted results — measure real bytes
    emit({"stage": "return", "ms": 0, "bytes": out_bytes, "detail": f"{out_bytes/1e6:.2f} MB, still encrypted"})

    # Stage: decrypt locally (uses the secret key — device only)
    dt, _ = _run([os.path.join(BIN, "decrypt"), CLIENT_HOME, outct, dec, str(nb)])
    _log_artifacts("decrypted-out", _files(dec, ".f64"))
    emit({"stage": "decrypt", "ms": round(dt * 1000), "detail": "unlocked on this device"})

    agg = _recombine(batches, dec, scale)
    # Best-effort removal of the per-job dir. During a run it holds the ciphertexts
    # AND transient cleartext: the pre-encryption packed slot vectors and the
    # decrypted aggregate .f64 files (the user's financial aggregates in the clear).
    # These live only under the git-ignored app/run/jobs/<id>/ and are deleted here;
    # CIPHERSPEND_KEEP_ARTIFACTS=1 intentionally preserves them for inspection.
    if not os.environ.get("CIPHERSPEND_KEEP_ARTIFACTS"):
        shutil.rmtree(job, ignore_errors=True)
    return agg, {"num_batches": nb, "in_bytes": in_bytes, "out_bytes": out_bytes, "keys": keys}
