# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Local Flask server — the CipherSpend device runtime's HTTP surface.

Binds to 127.0.0.1 only. No external/remote calls of any kind; request bodies
(which carry transactions) are never forwarded or logged anywhere. Serves the
static frontend and the pipeline/analytics endpoints.
"""

import json
import queue
import threading
import uuid

from flask import Flask, Response, request, send_from_directory

from . import csv_import, demo, orchestrator, pipeline
from .pipeline import ROOT

import os
WEB = os.path.join(ROOT, "web")
app = Flask(__name__, static_folder=None)

# Bound request bodies: a 200k-transaction CSV is well under this; anything larger
# is refused before it is parsed into memory (413).
app.config["MAX_CONTENT_LENGTH"] = 64 * 1024 * 1024  # 64 MB

# The server is meant to be reached only from this machine's own browser at the
# fixed loopback origin. Two same-origin/loopback checks defend the local API
# against a malicious web page the user happens to have open:
#   1. Host allowlist  -> defeats DNS-rebinding (attacker page resolves its own
#      hostname to 127.0.0.1, but the Host header would not be an allowed value).
#   2. Origin / Sec-Fetch-Site -> defeats cross-site POSTs (CSRF) to /api/*.
# No user data is persisted server-side to steal (results are in-memory under an
# unguessable token), so this is defense-in-depth, not the only line.
_ALLOWED_HOSTS = {"127.0.0.1:5057", "localhost:5057"}
_ALLOWED_ORIGINS = {"http://127.0.0.1:5057", "http://localhost:5057"}


@app.before_request
def _guard_local_only():
    if request.host not in _ALLOWED_HOSTS:
        return ("forbidden host", 403)
    # Only cross-site *writes* to the API matter; static GETs are same-origin.
    if request.path.startswith("/api/"):
        site = request.headers.get("Sec-Fetch-Site")
        if site and site not in ("same-origin", "same-site", "none"):
            return ("cross-site request refused", 403)
        origin = request.headers.get("Origin")
        if origin and origin not in _ALLOWED_ORIGINS:
            return ("cross-origin request refused", 403)
    return None


def _json_body():
    """Parse a JSON body without trusting Content-Type sniffing to bypass the
    cross-origin guard; returns {} on absent/invalid body rather than raising."""
    return request.get_json(silent=True) or {}


# In-memory result cache (local process only) so the Compare screen can request
# arbitrary two-month comparisons without re-running the pipeline.
RESULTS = {}


@app.get("/")
def index():
    return send_from_directory(WEB, "index.html")


@app.get("/<path:fname>")
def static_file(fname):
    if fname.startswith("api/"):
        return ("not found", 404)
    return send_from_directory(WEB, fname)


@app.get("/api/example.csv")
def example_csv():
    return Response(demo.example_csv(), mimetype="text/csv",
                    headers={"Content-Disposition": "attachment; filename=cipherspend-example.csv"})


@app.post("/api/keygen")
def keygen():
    """Surface the on-device key-creation moment for the own-data onboarding path.

    Idempotent: generates the CKKS context + keys on first use (via the same
    ensure_keys() the pipeline uses), otherwise confirms they already exist. The
    secret key is created on and confined to the client home; this endpoint returns
    only measured sizes and a `created`/timing flag — never any key material.
    """
    try:
        keys = pipeline.ensure_keys()
    except pipeline.PipelineError as ex:
        return app.response_class(json.dumps({"ok": False, "error": str(ex)}),
                                  mimetype="application/json", status=500)
    out = {
        "ok": True,
        "created": keys["created"],
        "keygen_ms": keys["keygen_ms"],
        "rotation_keys_mb": round(keys["rotation_keys_bytes"] / 1e6, 2),
        "scheme": "CKKS", "ring_dimension": 65536, "security": "HEStd_128_classic",
    }
    return app.response_class(json.dumps(out), mimetype="application/json")


@app.post("/api/inspect")
def inspect():
    body = _json_body()
    return app.response_class(json.dumps(csv_import.inspect_csv(body.get("text", ""), body.get("mapping"))),
                              mimetype="application/json")


def _prewarm_keys():
    """Kick OpenFHE key generation on a background thread so it runs CONCURRENTLY
    with local categorization/review. ensure_keys is idempotent + cached, so the
    later analyze finds the keys already on device."""
    def _go():
        try:
            pipeline.ensure_keys()
        except Exception:
            pass  # analyze will surface any real keygen error later
    threading.Thread(target=_go, daemon=True).start()


@app.post("/api/preview")
def preview():
    body = _json_body()
    cfg = body.get("cfg", {})
    if cfg.get("auto_categorize"):
        _prewarm_keys()   # categorize locally while the key is generated in parallel
    _, report = csv_import.build_transactions(body.get("text", ""), cfg)
    return app.response_class(json.dumps(report), mimetype="application/json")


@app.get("/api/result")
def result_get():
    res = RESULTS.get(request.args.get("token", ""))
    if not res:
        return ("unknown session", 404)
    return app.response_class(json.dumps(res), mimetype="application/json")


@app.post("/api/compare")
def compare():
    body = _json_body()
    res = RESULTS.get(body.get("token"))
    if not res:
        return ("unknown session", 404)
    cmp = orchestrator.compare_pair(res, int(body["a"]), int(body["b"]))
    return app.response_class(json.dumps(cmp), mimetype="application/json")


@app.post("/api/analyze")
def analyze():
    body = _json_body()
    q = queue.Queue()

    def work():
        try:
            if body.get("mode") == "demo":
                txns = demo.generate_transactions()
            else:
                txns, report = csv_import.build_transactions(body.get("text", ""), body.get("cfg", {}))
                if not report.get("ok"):
                    q.put({"event": "error", "report": report,
                           "message": report.get("error", "import validation failed")})
                    q.put(None); return
                # gate: only STRUCTURAL problems block (rare: the categorizer couldn't
                # run and expenses have no usable merchant text). Low-confidence
                # classifications are analyzed as best-guess; their review is OPTIONAL.
                if report.get("uncategorized"):
                    q.put({"event": "error", "report": report,
                           "message": f"{report['uncategorized']} transaction(s) had no merchant text to "
                                      "categorize — resolve or exclude them before analyzing."})
                    q.put(None); return
            token = uuid.uuid4().hex
            res = orchestrator.analyze(txns, token, emit=lambda e: q.put({"event": "stage", "data": e}))
            res["token"] = token
            RESULTS[token] = res
            # Hand off only a small token over SSE; the (large) result is fetched
            # over a normal request — robust against dev-server chunk buffering.
            q.put({"event": "done", "token": token})
        except Exception as ex:  # surface a clean message; never leak transaction data
            q.put({"event": "error", "message": f"{type(ex).__name__}: {ex}"})
        q.put(None)

    threading.Thread(target=work, daemon=True).start()

    def gen():
        while True:
            item = q.get()
            if item is None:
                break
            yield f"data: {json.dumps(item)}\n\n"

    return Response(gen(), mimetype="text/event-stream",
                    headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"})


def main():
    print("CipherSpend running at  http://127.0.0.1:5057  (local only — nothing leaves this machine)")
    app.run(host="127.0.0.1", port=5057, threaded=True, debug=False)


if __name__ == "__main__":
    main()
