# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Stage 3 plaintext reference + faithful packed-layout twin for fhe-financial-app.

This package is CLEARTEXT ONLY. It is the ground truth (direct aggregation) and a
faithful numpy simulation of the approved two-ciphertext CKKS slot layout
(interleaved rotate-and-sum). It contains NO encryption — the CKKS implementation
is a later stage. See ARCHITECTURE.md.
"""

from . import taxonomy, scaling, layout, periods, completeness, errors
from . import data_io, aggregate, twin, metrics, fixtures

__all__ = [
    "taxonomy", "scaling", "layout", "periods", "completeness", "errors",
    "data_io", "aggregate", "twin", "metrics", "fixtures",
]
