# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Direct plaintext aggregation -- the GROUND TRUTH (Stage 3 reference).

Sums raw amounts (currency units) into (global_month, category),
(global_month, week-bin), and (global_month) income buckets. This is what the
faithful packed-layout twin and, later, the CKKS circuit must reproduce.
"""

from collections import defaultdict

from .periods import base_month, global_month_index, week_bin


def direct_aggregate(transactions, base=None):
    """Return (agg, base) where agg has keys 'cat', 'week', 'income'.

    agg['cat'][(global_m, c)]  = summed expense amount
    agg['week'][(global_m, w)] = summed expense amount in that week-bin
    agg['income'][global_m]    = summed income amount
    All in raw currency units.
    """
    if base is None:
        base = base_month([t["date"] for t in transactions])
    cat = defaultdict(float)
    week = defaultdict(float)
    income = defaultdict(float)
    for t in transactions:
        gm = global_month_index(t["date"], base)
        if t["type"] == "income":
            income[gm] += t["amount"]
        else:
            c = t["category_index"]
            w = week_bin(t["date"].day)
            cat[(gm, c)] += t["amount"]
            week[(gm, w)] += t["amount"]
    return {"cat": dict(cat), "week": dict(week), "income": dict(income)}, base
