# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Label each calendar month in the import window complete vs partial.

A month is COMPLETE iff the import window fully contains it (first..last day).
Completeness is about window COVERAGE, not transaction presence: a middle month
with zero transactions is still complete (and simply has zero aggregates). The
first/last months of a window are partial unless the window starts on the 1st /
ends on the last day.
"""

import calendar
import datetime

from .periods import base_month


def label_months(dates, window=None):
    """Return an ordered list of month labels spanning the import window.

    dates: iterable of datetime.date. window: optional (start_date, end_date);
    defaults to (min(dates), max(dates)).
    """
    dates = list(dates)
    if not dates:
        return []
    ws = window[0] if window else min(dates)
    we = window[1] if window else max(dates)
    base = base_month([ws])
    result = []
    y, m = ws.year, ws.month
    while (y, m) <= (we.year, we.month):
        dim = calendar.monthrange(y, m)[1]
        first = datetime.date(y, m, 1)
        last = datetime.date(y, m, dim)
        complete = (first >= ws) and (last <= we)
        cov_start = max(first, ws)
        cov_end = min(last, we)
        coverage_days = (cov_end - cov_start).days + 1
        result.append({
            "global_m": (y - base[0]) * 12 + (m - base[1]),
            "year": y,
            "month": m,
            "complete": complete,
            "coverage_days": coverage_days,
            "days_in_month": dim,
        })
        if m == 12:
            y, m = y + 1, 1
        else:
            m += 1
    return result
