# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""CSV loading and transaction normalization (client_clear parsing).

CSV columns: date (YYYY-MM-DD), amount (positive), category, type.
  - type == "expense": category is one of the 10 spending categories.
  - type == "income":  category is the reserved INCOME_LABEL.
Amounts are always positive; inflow/outflow is carried by `type`.
"""

import csv

from . import taxonomy
from .periods import to_date


def normalize_row(row):
    """Turn a raw CSV row dict into a normalized transaction dict."""
    ttype = row["type"].strip().lower()
    amount = float(row["amount"])
    if amount < 0:
        raise ValueError(f"amounts must be positive (type carries sign): {row!r}")
    txn = {
        "date": to_date(row["date"].strip()),
        "amount": amount,
        "type": ttype,
    }
    if ttype == "income":
        txn["category"] = taxonomy.INCOME_LABEL
        txn["category_index"] = None
    elif ttype == "expense":
        name = row["category"].strip()
        txn["category"] = name
        txn["category_index"] = taxonomy.category_index(name)  # raises on unknown
    else:
        raise ValueError(f"unknown transaction type {ttype!r} in {row!r}")
    return txn


def load_csv(path):
    with open(path, newline="") as f:
        return [normalize_row(row) for row in csv.DictReader(f)]


def write_csv(path, transactions):
    """Write normalized transactions back to the CSV contract (for fixtures)."""
    with open(path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["date", "amount", "category", "type"])
        for t in transactions:
            w.writerow([t["date"].isoformat(), f"{t['amount']:.2f}",
                        t["category"], t["type"]])
