# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Accuracy checks (absolute + relative) and guarded ratios.

Near-zero values make relative error unstable, so acceptance is
    |a - b| <= max(abs_tol, rel_tol * |b|)
i.e. the absolute tolerance dominates near zero. All tolerances here are
PROVISIONAL until measured against the real CKKS implementation.
"""

# Provisional tolerances for the exact-float twin-vs-reference comparison
# (the twin models packing/folds in float and adds no CKKS noise, so agreement
# should be near machine precision). Looser CKKS tolerances come later.
TWIN_ABS_TOL = 1e-6
TWIN_REL_TOL = 1e-9

# Default floor below which a ratio denominator is treated as undefined
# (currency units). Configurable per call.
DEFAULT_EPS_DENOM = 1.0


def is_close(a, b, abs_tol=TWIN_ABS_TOL, rel_tol=TWIN_REL_TOL):
    return abs(a - b) <= max(abs_tol, rel_tol * abs(b))


def assert_close(a, b, abs_tol=TWIN_ABS_TOL, rel_tol=TWIN_REL_TOL, msg=""):
    if not is_close(a, b, abs_tol, rel_tol):
        raise AssertionError(
            f"{msg} values differ: a={a!r} b={b!r} "
            f"|a-b|={abs(a-b):.3e} abs_tol={abs_tol:.3e} rel_tol={rel_tol:.3e}"
        )


def safe_ratio(numerator, denominator, eps_denom=DEFAULT_EPS_DENOM):
    """Return (value, flag).

    If |denominator| < eps_denom the ratio is unstable -> return (None, reason).
    Otherwise (numerator/denominator, None).
    """
    if abs(denominator) < eps_denom:
        return None, f"undefined: |denominator|={abs(denominator):.6g} < eps={eps_denom:g}"
    return numerator / denominator, None
