# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Deterministic synthetic transaction fixtures.

Every generator is seeded, so CSVs and tests are reproducible. Generators return
normalized transaction dicts (same shape as data_io.normalize_row output).
"""

import datetime
import random

from . import taxonomy

BASE_YEAR = 2024
BASE_MONTH = 1


def _ym(offset):
    """Map a 0-based month offset to (year, month) from BASE_YEAR-BASE_MONTH."""
    total = (BASE_MONTH - 1) + offset
    return BASE_YEAR + total // 12, total % 12 + 1


def _txn(date, amount, category, ttype):
    cat_index = None if ttype == "income" else taxonomy.category_index(category)
    return {"date": date, "amount": round(amount, 2), "type": ttype,
            "category": category, "category_index": cat_index}


def gen_basic(n_months=3, seed=0, big_transaction=True):
    """Moderate, in-capacity history across all categories, with monthly income.

    Includes one unusually large Housing transaction to exercise no-clip scaling.
    """
    rng = random.Random(seed)
    txns = []
    for o in range(n_months):
        year, month = _ym(o)
        # 2 income deposits per month
        for k in range(2):
            day = 1 + k * 14
            txns.append(_txn(datetime.date(year, month, day),
                             rng.uniform(2000, 4000), taxonomy.INCOME_LABEL, "income"))
        # a handful of expenses per category, spread across the month
        for c, name in enumerate(taxonomy.CATEGORY_NAMES):
            for k in range(rng.randint(2, 5)):
                day = rng.randint(1, 28)
                txns.append(_txn(datetime.date(year, month, day),
                                 rng.uniform(5, 200), name, "expense"))
    if big_transaction:
        year, month = _ym(0)
        txns.append(_txn(datetime.date(year, month, 3), 250000.00, "Housing", "expense"))
    return txns


def gen_overflow_category(seed=1):
    """> 32 expenses in one (month, category): 40 Groceries in month 0, no week > 64."""
    rng = random.Random(seed)
    year, month = _ym(0)
    txns = []
    for k in range(40):
        day = 1 + (k % 28)  # spread across the month so no single week-bin > 64
        txns.append(_txn(datetime.date(year, month, day),
                         rng.uniform(5, 120), "Groceries", "expense"))
    return txns


def gen_overflow_week(seed=2):
    """> 64 expenses in one (month, week-bin): 70 expenses on days 1-7 of month 0.

    Spread across all 10 categories (<= 8 each, so no category bucket overflows),
    isolating the weekly-bin overflow.
    """
    rng = random.Random(seed)
    year, month = _ym(0)
    txns = []
    for k in range(70):
        day = 1 + (k % 7)                       # days 1-7 -> week-bin 0
        name = taxonomy.CATEGORY_NAMES[k % 10]  # round-robin categories
        txns.append(_txn(datetime.date(year, month, day),
                         rng.uniform(5, 120), name, "expense"))
    return txns


def gen_overflow_income(seed=3):
    """> 64 income transactions in one month: 70 income deposits in month 0."""
    rng = random.Random(seed)
    year, month = _ym(0)
    txns = []
    for k in range(70):
        day = 1 + (k % 28)
        txns.append(_txn(datetime.date(year, month, day),
                         rng.uniform(50, 500), taxonomy.INCOME_LABEL, "income"))
    return txns


def gen_multi_year(n_months=14, seed=4):
    """> 12 months of history -> exercises month-group batching."""
    return gen_basic(n_months=n_months, seed=seed, big_transaction=False)


ALL_GENERATORS = {
    "basic": gen_basic,
    "overflow_category": gen_overflow_category,
    "overflow_week": gen_overflow_week,
    "overflow_income": gen_overflow_income,
    "multi_year": gen_multi_year,
}


def write_all(directory):
    """Write every fixture to `directory` as CSV. Returns {name: path}."""
    import os
    from .data_io import write_csv
    os.makedirs(directory, exist_ok=True)
    paths = {}
    for name, gen in ALL_GENERATORS.items():
        path = os.path.join(directory, f"{name}.csv")
        write_csv(path, gen())
        paths[name] = path
    return paths
