# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Approved two-ciphertext interleaved slot layout (constants + slot maps + fold).

See ARCHITECTURE.md for the correctness proof. This module encodes the EXACT
layout the CKKS circuit will use, so the faithful twin (twin.py) can simulate it
in float with numpy and be checked against direct aggregation.
"""

import numpy as np

# Crypto / packing constants
N_RING = 65536
N_SLOTS = N_RING // 2          # 32768 CKKS slots
STRIDE = 128                   # D, power of 2, >= max(B1, B2)
MONTHS_PER_BATCH = 12

# ct1: monthly category (expense) sums
N_CATEGORIES = 10
B1 = MONTHS_PER_BATCH * N_CATEGORIES   # 120 buckets
L1 = 32                                # lanes (per-(month,category) capacity)
CT1_ROTATIONS = [128, 256, 512, 1024, 2048]           # D*2^k, k=0..log2(L1)-1

# ct2: weekly (expense) buckets [0,60) + monthly income buckets [60,72)
WEEK_BINS = 5
WEEKLY_BUCKETS = MONTHS_PER_BATCH * WEEK_BINS          # 60
INCOME_BASE = WEEKLY_BUCKETS                           # income buckets start at 60
B2 = WEEKLY_BUCKETS + MONTHS_PER_BATCH                 # 72 buckets
L2 = 64                                                # lanes
CT2_ROTATIONS = [128, 256, 512, 1024, 2048, 4096]      # D*2^k, k=0..log2(L2)-1

# Sanity: interleaving is contamination-free only if D*L <= N_SLOTS and D >= B.
assert STRIDE >= B1 and STRIDE >= B2
assert STRIDE * L1 <= N_SLOTS
assert STRIDE * L2 <= N_SLOTS


# ---- bucket indices -------------------------------------------------------
def ct1_bucket(mm, c):
    """ct1 bucket for within-batch month mm in [0,12), category c in [0,10)."""
    return mm * N_CATEGORIES + c


def ct2_week_bucket(mm, w):
    """ct2 weekly bucket for within-batch month mm, week-bin w in [0,5)."""
    return mm * WEEK_BINS + w


def ct2_income_bucket(mm):
    """ct2 income bucket for within-batch month mm."""
    return INCOME_BASE + mm


# ---- slot maps (lane t at slot t*STRIDE + bucket) -------------------------
def ct1_slot(mm, c, lane):
    return lane * STRIDE + ct1_bucket(mm, c)


def ct2_week_slot(mm, w, lane):
    return lane * STRIDE + ct2_week_bucket(mm, w)


def ct2_income_slot(mm, lane):
    return lane * STRIDE + ct2_income_bucket(mm)


# ---- rotation / fold (float emulation of EvalRotate + EvalAdd) ------------
def rotate(x, r):
    """Emulate EvalRotate(x, r): result[i] = x[(i + r) mod n]."""
    return np.roll(x, -r)


def fold(x, rotations):
    """In-place-safe interleaved rotate-and-sum reduction. Returns a new array."""
    acc = x.copy()
    for r in rotations:
        acc = acc + rotate(acc, r)
    return acc


def new_slot_vector():
    return np.zeros(N_SLOTS, dtype=np.float64)
