# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Local post-decryption analytics (client_post_decrypt).

All nonlinear work -- shares, ratios, HHI concentration, weekly variability,
cosine/Euclidean similarity, per-category deltas, trends -- runs here in exact
float on the decrypted aggregates. Every ratio guards against zero / very small
denominators (returns None + a flag rather than an unstable or infinite value).
No runtime LLM is involved.
"""

import math

from . import taxonomy
from .errors import DEFAULT_EPS_DENOM, safe_ratio


def month_vectors(agg, global_m):
    """Extract (cat_vec[10], week_vec[5], income) for one month from an agg dict."""
    cat = [agg["cat"].get((global_m, c), 0.0) for c in range(taxonomy.N_CATEGORIES)]
    week = [agg["week"].get((global_m, w), 0.0) for w in range(5)]
    income = agg["income"].get(global_m, 0.0)
    return cat, week, income


def _group_sum(cat_vec, idx_set):
    return sum(cat_vec[i] for i in idx_set)


def monthly_metrics(cat_vec, week_vec, income, eps=DEFAULT_EPS_DENOM):
    """All per-month metrics for one month. Ratios return (value, flag)."""
    total_spend = sum(cat_vec)
    fixed = _group_sum(cat_vec, taxonomy.FIXED_IDX)
    essential = _group_sum(cat_vec, taxonomy.ESSENTIAL_IDX)
    discretionary = _group_sum(cat_vec, taxonomy.DISCRETIONARY_IDX)
    housing = _group_sum(cat_vec, taxonomy.HOUSING_IDX)

    # Category shares (guarded by total_spend).
    shares = [safe_ratio(cat_vec[c], total_spend, eps) for c in range(taxonomy.N_CATEGORIES)]

    # HHI concentration over category shares (guarded): sum(share^2).
    if total_spend < eps:
        hhi = (None, f"undefined: total_spend={total_spend:.6g} < eps={eps:g}")
    else:
        hhi = (sum((cat_vec[c] / total_spend) ** 2 for c in range(taxonomy.N_CATEGORIES)), None)

    net = income - total_spend
    return {
        "total_spend": total_spend,
        "income": income,
        "net": net,
        "savings_rate": safe_ratio(net, income, eps),
        "cashflow_index": safe_ratio(net, income + total_spend, eps),
        "fixed_load_income": safe_ratio(fixed, income, eps),
        "fixed_load_spend": safe_ratio(fixed, total_spend, eps),
        "essential_ratio_income": safe_ratio(essential, income, eps),
        "essential_ratio_spend": safe_ratio(essential, total_spend, eps),
        "discretionary_ratio_income": safe_ratio(discretionary, income, eps),
        "discretionary_ratio_spend": safe_ratio(discretionary, total_spend, eps),
        "housing_ratio_income": safe_ratio(housing, income, eps),
        "housing_ratio_spend": safe_ratio(housing, total_spend, eps),
        "category_shares": shares,
        "hhi": hhi,
        "weekly_variability": weekly_variability(week_vec),
    }


def weekly_variability(week_vec):
    """Population variance and std of the week-bin totals (exact float)."""
    n = len(week_vec)
    if n == 0:
        return {"variance": None, "std": None}
    mean = sum(week_vec) / n
    var = sum((w - mean) ** 2 for w in week_vec) / n
    return {"variance": var, "std": math.sqrt(var), "mean": mean}


def _shares_vector(cat_vec, eps=DEFAULT_EPS_DENOM):
    total = sum(cat_vec)
    if total < eps:
        return None
    return [c / total for c in cat_vec]


def similarity(cat_vec_a, income_a, cat_vec_b, income_b,
               income_weight=0.15, income_scale=None, eps=DEFAULT_EPS_DENOM):
    """Behavioral similarity between two months.

    Feature vector = per-category spending shares (primary) + one low-weight,
    cross-period-normalized income feature (so large income changes still move the
    score, but spending remains the primary driver). Returns cosine, Euclidean
    distance, and per-category share deltas, each guarded.
    """
    sa = _shares_vector(cat_vec_a, eps)
    sb = _shares_vector(cat_vec_b, eps)
    if sa is None or sb is None:
        return {"cosine": (None, "undefined: a zero-spend month"),
                "euclidean": (None, "undefined: a zero-spend month"),
                "category_deltas": None}

    # Cross-period income normalization (public: uses both months' incomes).
    denom = income_scale if income_scale is not None else max(income_a, income_b)
    if denom < eps:
        fa = fb = 0.0  # both incomes ~0 -> income feature carries no signal
    else:
        fa, fb = income_a / denom, income_b / denom
    va = sa + [income_weight * fa]
    vb = sb + [income_weight * fb]

    dot = sum(x * y for x, y in zip(va, vb))
    na = math.sqrt(sum(x * x for x in va))
    nb = math.sqrt(sum(y * y for y in vb))
    if na < 1e-12 or nb < 1e-12:
        cosine = (None, "undefined: zero-norm feature vector")
    else:
        cosine = (dot / (na * nb), None)
    euclidean = (math.sqrt(sum((x - y) ** 2 for x, y in zip(va, vb))), None)
    deltas = [sb[c] - sa[c] for c in range(taxonomy.N_CATEGORIES)]
    return {"cosine": cosine, "euclidean": euclidean, "category_deltas": deltas}


def baseline(agg, month_list, exclude=None, eps=DEFAULT_EPS_DENOM):
    """Mean per-category share + mean income over `month_list` (complete months).

    exclude: optional global_m to leave out (avoid self-inclusion bias).
    """
    months = [m for m in month_list if m != exclude]
    if not months:
        return None
    n = len(months)
    cat_acc = [0.0] * taxonomy.N_CATEGORIES
    inc_acc = 0.0
    counted = 0
    for gm in months:
        cat_vec, _, income = month_vectors(agg, gm)
        sv = _shares_vector(cat_vec, eps)
        if sv is None:
            continue
        for c in range(taxonomy.N_CATEGORIES):
            cat_acc[c] += sv[c]
        inc_acc += income
        counted += 1
    if counted == 0:
        return None
    return {"share_vector": [x / counted for x in cat_acc],
            "mean_income": inc_acc / counted, "months_used": counted}


def trend(agg, month_list, metric_key, eps=DEFAULT_EPS_DENOM):
    """Time series of one monthly metric across months (None where undefined)."""
    series = []
    for gm in month_list:
        cat_vec, week_vec, income = month_vectors(agg, gm)
        m = monthly_metrics(cat_vec, week_vec, income, eps)
        val = m[metric_key]
        if isinstance(val, tuple):  # guarded ratio (value, flag)
            val = val[0]
        series.append((gm, val))
    return series
