# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Calendar helpers: global month indexing and the 5-bin week rule."""

import datetime


def to_date(value):
    """Parse an ISO date string (YYYY-MM-DD) or pass through a datetime.date."""
    if isinstance(value, datetime.date):
        return value
    return datetime.date.fromisoformat(value)


def base_month(dates):
    """Return (year, month) of the earliest date -- the origin for month indexing."""
    earliest = min(dates)
    return (earliest.year, earliest.month)


def global_month_index(d, base):
    """0-based chronological month index relative to `base` (year, month)."""
    by, bm = base
    return (d.year - by) * 12 + (d.month - bm)


def week_bin(day):
    """Deterministic within-month bin: days 1-7,8-14,15-21,22-28,29-end -> 0..4.

    Bin 4 (day 29-end) is variable length; per-day views must divide by the
    public actual day-count of each bin.
    """
    return min((day - 1) // 7, 4)
