# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Input scaling for CKKS encoding.

`SCALE` is a PUBLIC reference divisor, not a cap. Amounts are divided by it before
encoding and multiplied back after decryption. Because it is a linear divisor,
unusually large transactions are NEVER clipped -- they simply exceed 1.0 in
normalized units. The choice of SCALE affects only CKKS precision (to be measured
against the real implementation), never correctness of the plaintext reference.
"""

DEFAULT_SCALE = 1000.0


def scale_amount(amount, scale=DEFAULT_SCALE):
    """Normalize a raw amount for encoding. No clipping."""
    return amount / scale


def unscale(value, scale=DEFAULT_SCALE):
    """Convert a decrypted/aggregated normalized value back to currency units."""
    return value * scale
