# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Fixed spending-category taxonomy and static client-side maps.

Income is NOT one of the 10 spending categories; it is a separate stream
(transaction type == "income"). Category attributes (group / fixed / housing)
live entirely on the client (client_clear) and are never sent to the server.
"""

# Ordered: index == position. 10 spending categories.
CATEGORIES = [
    # name,           group,            fixed, housing
    ("Housing",        "essential",     True,  True),
    ("Utilities",      "essential",     True,  False),
    ("Groceries",      "essential",     False, False),
    ("Transportation", "essential",     False, False),
    ("Insurance",      "essential",     True,  False),
    ("Healthcare",     "essential",     False, False),
    ("Dining",         "discretionary", False, False),
    ("Entertainment",  "discretionary", False, False),
    ("Shopping",       "discretionary", False, False),
    ("Subscriptions",  "discretionary", True,  False),
]

N_CATEGORIES = len(CATEGORIES)
assert N_CATEGORIES == 10

CATEGORY_NAMES = [c[0] for c in CATEGORIES]
CATEGORY_INDEX = {c[0]: i for i, c in enumerate(CATEGORIES)}

ESSENTIAL_IDX = frozenset(i for i, c in enumerate(CATEGORIES) if c[1] == "essential")
DISCRETIONARY_IDX = frozenset(i for i, c in enumerate(CATEGORIES) if c[1] == "discretionary")
FIXED_IDX = frozenset(i for i, c in enumerate(CATEGORIES) if c[2])
HOUSING_IDX = frozenset(i for i, c in enumerate(CATEGORIES) if c[3])

INCOME_LABEL = "Income"  # reserved category label for income rows


def category_index(name):
    """Return the 0-based index of a spending category name, or raise KeyError."""
    return CATEGORY_INDEX[name]
