# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Faithful packed-layout twin.

Two responsibilities:
  1. build_batches(): the client_clear packer + overflow batcher. Places bounded,
     scaled per-transaction contributions into the exact interleaved slot layout,
     spilling into additional batches with no truncation and no double-counting.
  2. twin_aggregate(): simulates the server circuit in float -- interleaved
     rotate-and-sum folds via numpy -- and recombines batches additively, then
     de-scales. This must match direct_aggregate() exactly (up to float noise);
     it adds NO CKKS noise (that is validated later against the real library).
"""

from collections import defaultdict

from . import layout, scaling
from .periods import base_month, global_month_index, week_bin


class Batch:
    """One (ct1, ct2) layout instance for a month-group, capacity layer `layer`."""

    __slots__ = ("group", "layer", "ct1", "ct2")

    def __init__(self, group, layer):
        self.group = group
        self.layer = layer
        self.ct1 = layout.new_slot_vector()
        self.ct2 = layout.new_slot_vector()


def build_batches(transactions, base=None, scale=scaling.DEFAULT_SCALE):
    """Pack transactions into batches. Returns (batches, meta).

    meta counts placements per stream so callers can prove nothing was dropped.
    Each transaction contributes exactly once per applicable stream:
      - expense -> one ct1 (month,category) lane AND one ct2 (month,week) lane
      - income  -> one ct2 (month) income lane
    """
    if base is None:
        base = base_month([t["date"] for t in transactions])

    # Deterministic order so lane/layer assignment is reproducible.
    ordered = sorted(
        enumerate(transactions),
        key=lambda it: (it[1]["date"], it[1]["type"], it[1]["category"], it[0]),
    )

    ct1_count = defaultdict(int)   # (group, mm, c) -> running index
    ct2w_count = defaultdict(int)  # (group, mm, w)
    ct2i_count = defaultdict(int)  # (group, mm)
    batches = {}                   # (group, layer) -> Batch
    meta = {"ct1_placements": 0, "ct2_week_placements": 0, "ct2_income_placements": 0}

    def get_batch(group, layer):
        key = (group, layer)
        b = batches.get(key)
        if b is None:
            b = Batch(group, layer)
            batches[key] = b
        return b

    for _, t in ordered:
        gm = global_month_index(t["date"], base)
        group, mm = divmod(gm, layout.MONTHS_PER_BATCH)
        val = scaling.scale_amount(t["amount"], scale)

        if t["type"] == "income":
            key = (group, mm)
            idx = ct2i_count[key]; ct2i_count[key] += 1
            layer, lane = divmod(idx, layout.L2)
            get_batch(group, layer).ct2[layout.ct2_income_slot(mm, lane)] += val
            meta["ct2_income_placements"] += 1
        else:
            c = t["category_index"]
            w = week_bin(t["date"].day)
            # ct1 category stream
            k1 = (group, mm, c)
            i1 = ct1_count[k1]; ct1_count[k1] += 1
            layer1, lane1 = divmod(i1, layout.L1)
            get_batch(group, layer1).ct1[layout.ct1_slot(mm, c, lane1)] += val
            meta["ct1_placements"] += 1
            # ct2 weekly stream
            k2 = (group, mm, w)
            i2 = ct2w_count[k2]; ct2w_count[k2] += 1
            layer2, lane2 = divmod(i2, layout.L2)
            get_batch(group, layer2).ct2[layout.ct2_week_slot(mm, w, lane2)] += val
            meta["ct2_week_placements"] += 1

    ordered_batches = [batches[k] for k in sorted(batches.keys())]
    return ordered_batches, meta


def twin_aggregate(batches, scale=scaling.DEFAULT_SCALE):
    """Fold each batch (float emulation of the CKKS circuit) and recombine.

    Returns {'cat','week','income'} in raw currency units, matching the shape of
    aggregate.direct_aggregate()'s output.
    """
    cat = defaultdict(float)
    week = defaultdict(float)
    income = defaultdict(float)

    for b in batches:
        v1 = layout.fold(b.ct1, layout.CT1_ROTATIONS)
        v2 = layout.fold(b.ct2, layout.CT2_ROTATIONS)
        base_gm = b.group * layout.MONTHS_PER_BATCH
        for mm in range(layout.MONTHS_PER_BATCH):
            gm = base_gm + mm
            for c in range(layout.N_CATEGORIES):
                v = v1[layout.ct1_bucket(mm, c)]
                if v != 0.0:
                    cat[(gm, c)] += v
            for w in range(layout.WEEK_BINS):
                v = v2[layout.ct2_week_bucket(mm, w)]
                if v != 0.0:
                    week[(gm, w)] += v
            vi = v2[layout.ct2_income_bucket(mm)]
            if vi != 0.0:
                income[gm] += vi

    unscale = scaling.unscale
    return {
        "cat": {k: unscale(v, scale) for k, v in cat.items()},
        "week": {k: unscale(v, scale) for k, v in week.items()},
        "income": {k: unscale(v, scale) for k, v in income.items()},
    }
