// Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
// Minimal CKKS smoke test — mirrors the FHE-dev image's fhe-smoke-test CKKS
// program (common.claude/.../environment/smoke_test.sh), run against the local
// OpenFHE 1.5.1 install since Docker is unavailable. Expects EvalAdd -> (5,7,9).
#include "openfhe.h"
using namespace lbcrypto;

int main() {
    CCParams<CryptoContextCKKSRNS> p;
    p.SetMultiplicativeDepth(1);
    p.SetScalingModSize(50);
    p.SetRingDim(1 << 14);
    auto cc = GenCryptoContext(p);
    cc->Enable(PKE);
    cc->Enable(LEVELEDSHE);
    auto keys = cc->KeyGen();
    std::vector<double> va{1.0, 2.0, 3.0};
    std::vector<double> vb{4.0, 5.0, 6.0};
    auto a = cc->MakeCKKSPackedPlaintext(va);
    auto b = cc->MakeCKKSPackedPlaintext(vb);
    auto ca = cc->Encrypt(keys.publicKey, a);
    auto cb = cc->Encrypt(keys.publicKey, b);
    auto cs = cc->EvalAdd(ca, cb);
    Plaintext r;
    cc->Decrypt(keys.secretKey, cs, &r);
    r->SetLength(3);
    std::cout << "OpenFHE EvalAdd -> " << r << std::endl;  // expect ~(5, 7, 9)
    std::cout << "SMOKE OK" << std::endl;
    return 0;
}
