// Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
// Stage 4: encrypted environment & toolchain validation. NO financial circuit.
// Builds a CKKS context at the approved parameters, generates ONLY the required
// rotation keys, verifies a rotation works, measures real serialized sizes and
// encrypt/decrypt numerical error.
#include "openfhe.h"
#include "cryptocontext-ser.h"
#include "key/key-ser.h"
#include "ciphertext-ser.h"
#include "scheme/ckksrns/ckksrns-ser.h"

#include <cmath>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <sys/stat.h>
#include <vector>

using namespace lbcrypto;

static long fsize(const std::string& p) {
    struct stat st;
    return (stat(p.c_str(), &st) == 0) ? static_cast<long>(st.st_size) : -1;
}
static double MB(long b) { return static_cast<double>(b) / (1024.0 * 1024.0); }

int main() {
    // ---- approved parameters (circuit is depth 0; set library minimum depth 1) --
    const uint32_t ringDim = 65536;
    const uint32_t multDepth = 1;
    const uint32_t scaleMod = 50;
    const uint32_t firstMod = 60;

    CCParams<CryptoContextCKKSRNS> params;
    params.SetMultiplicativeDepth(multDepth);
    params.SetScalingModSize(scaleMod);
    params.SetFirstModSize(firstMod);
    params.SetRingDim(ringDim);                    // explicit — never inferred
    params.SetSecurityLevel(HEStd_128_classic);
    params.SetScalingTechnique(FLEXIBLEAUTO);
    params.SetKeySwitchTechnique(HYBRID);

    auto cc = GenCryptoContext(params);
    cc->Enable(PKE);
    cc->Enable(KEYSWITCH);
    cc->Enable(LEVELEDSHE);

    const uint32_t actualN = cc->GetRingDimension();
    std::cout << "== CKKS context ==\n";
    std::cout << "requested RingDim    : " << ringDim << "\n";
    std::cout << "actual GetRingDim    : " << actualN << "\n";
    std::cout << "slots (N/2)          : " << actualN / 2 << "\n";
    std::cout << "security             : HEStd_128_classic\n";
    std::cout << "scaling technique    : FLEXIBLEAUTO  scaleMod=" << scaleMod
              << " firstMod=" << firstMod << "\n";
    std::cout << "multiplicativeDepth  : " << multDepth << " (circuit uses depth 0)\n";
    {   // authoritative modulus chain of a fresh ciphertext, from the constructed context
        auto ep = cc->GetCryptoParameters()->GetElementParams();
        const auto& towers = ep->GetParams();
        double logQ = 0.0;
        for (const auto& t : towers) logQ += std::log2(t->GetModulus().ConvertToDouble());
        std::cout << "ciphertext RNS limbs : " << towers.size()
                  << " (modulus count)\n";
        std::cout << "total logQ           : " << logQ << " bits (ciphertext modulus chain)\n";
    }
    if (actualN != ringDim) {
        std::cout << "FAIL: ring dimension is not 65536\n";
        return 1;
    }

    auto keys = cc->KeyGen();
    // ONLY the six required rotation keys for the approved layout. No relin key
    // (the circuit has no ciphertext x ciphertext multiply).
    const std::vector<int32_t> rots = {128, 256, 512, 1024, 2048, 4096};
    cc->EvalRotateKeyGen(keys.secretKey, rots);
    std::cout << "rotation keys        : {128,256,512,1024,2048,4096} (6)\n";
    std::cout << "relinearization key  : none (no ct x ct multiply)\n";

    // ---- encrypt/decrypt error over a full-slot known vector ----
    const size_t n = actualN / 2;
    std::vector<double> x(n);
    for (size_t i = 0; i < n; ++i) x[i] = std::sin(0.001 * static_cast<double>(i)) * 10.0 + 0.5;
    auto pt = cc->MakeCKKSPackedPlaintext(x);
    auto ct = cc->Encrypt(keys.publicKey, pt);
    Plaintext out;
    cc->Decrypt(keys.secretKey, ct, &out);
    out->SetLength(n);
    auto y = out->GetRealPackedValue();
    double maxerr = 0.0, sumsq = 0.0;
    for (size_t i = 0; i < n; ++i) {
        double e = std::fabs(y[i] - x[i]);
        maxerr = std::max(maxerr, e);
        sumsq += e * e;
    }
    std::cout << "\n== encrypt/decrypt error (" << n << " slots) ==\n";
    std::cout << "max abs error        : " << maxerr << "\n";
    std::cout << "RMSE                 : " << std::sqrt(sumsq / static_cast<double>(n)) << "\n";
    std::cout << "decode log precision : " << out->GetLogPrecision() << " bits\n";

    // ---- confirm a required rotation key actually works (generic, not the circuit) --
    auto ctRot = cc->EvalRotate(ct, 128);
    Plaintext outRot;
    cc->Decrypt(keys.secretKey, ctRot, &outRot);
    outRot->SetLength(n);
    auto yr = outRot->GetRealPackedValue();
    double rotErr = 0.0;
    for (size_t i = 0; i + 128 < n; ++i) rotErr = std::max(rotErr, std::fabs(yr[i] - x[i + 128]));
    std::cout << "\n== rotation key check (EvalRotate by 128) ==\n";
    std::cout << "max abs error vs shift: " << rotErr << "  (rotation keys functional)\n";

    // ---- serialize + measure REAL sizes ----
    const std::string d = "artifacts";
    std::filesystem::create_directories(d);
    bool ok = true;
    ok &= Serial::SerializeToFile(d + "/cc.bin", cc, SerType::BINARY);
    ok &= Serial::SerializeToFile(d + "/pub.bin", keys.publicKey, SerType::BINARY);
    ok &= Serial::SerializeToFile(d + "/sec.bin", keys.secretKey, SerType::BINARY);
    ok &= Serial::SerializeToFile(d + "/ct.bin", ct, SerType::BINARY);
    {
        std::ofstream f(d + "/rot6.bin", std::ios::out | std::ios::binary);
        ok &= cc->SerializeEvalAutomorphismKey(f, SerType::BINARY);
    }
    if (!ok) {
        std::cout << "FAIL: serialization error\n";
        return 1;
    }

    const long ccB = fsize(d + "/cc.bin");
    const long pubB = fsize(d + "/pub.bin");
    const long secB = fsize(d + "/sec.bin");
    const long ctB = fsize(d + "/ct.bin");
    const long rotB = fsize(d + "/rot6.bin");
    std::cout << "\n== measured serialized sizes (BINARY) ==\n";
    std::cout << "crypto context       : " << ccB << " B (" << MB(ccB) << " MB)\n";
    std::cout << "public key           : " << pubB << " B (" << MB(pubB) << " MB)\n";
    std::cout << "secret key           : " << secB << " B (" << MB(secB) << " MB)\n";
    std::cout << "1 fresh ciphertext   : " << ctB << " B (" << MB(ctB) << " MB)\n";
    std::cout << "6 rotation keys total: " << rotB << " B (" << MB(rotB) << " MB)\n";
    std::cout << "  ~per rotation key  : " << rotB / 6 << " B (" << MB(rotB / 6) << " MB)\n";
    std::cout << "\n== derived per-request transfer (2 input + 2 output ct) ==\n";
    std::cout << "input ciphertexts (2): " << MB(2 * ctB) << " MB\n";
    std::cout << "setup keys (pub+6 rot): " << MB(pubB + rotB) << " MB (sent once)\n";

    std::cout << "\nSTAGE4 OK\n";
    return 0;
}
