#!/usr/bin/env python3
# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Train the on-device merchant classifier and export a compact model to
web/categorizer.json (loaded by BOTH the Python categorizer and the in-browser
JS runtime). Run:  ./.venv/bin/python scripts/train_categorizer.py"""
import json, os, sys
import numpy as np, scipy.sparse as sp
from collections import Counter
from sklearn.linear_model import LogisticRegression

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from app import categorize_model as CM

def main():
    texts, labels = CM.build_training_examples()
    featsets = [CM.features(CM.canonicalize(t)) for t in texts]
    df = Counter(g for fs in featsets for g in fs)
    vocab = {g: i for i, g in enumerate(sorted(g for g, c in df.items() if c >= 2))}
    rows, cols = [], []
    for r, fs in enumerate(featsets):
        for g in fs:
            if g in vocab: rows.append(r); cols.append(vocab[g])
    X = sp.csr_matrix((np.ones(len(rows)), (rows, cols)), shape=(len(texts), len(vocab)))
    cats = CM.CATEGORIES
    y = np.array([cats.index(l) for l in labels])
    clf = LogisticRegression(C=6.0, max_iter=500, class_weight="balanced")
    clf.fit(X, y)

    # prune uninformative n-grams to keep the model small, then re-index
    coef = clf.coef_                          # (10, V)
    keep = np.where(np.abs(coef).max(axis=0) > 0.20)[0]
    inv = {i: g for g, i in vocab.items()}
    new_vocab = [inv[i] for i in keep]
    new_index = {g: j for j, g in enumerate(new_vocab)}
    pruned = coef[:, keep]

    model = {
        "categories": cats,
        "ngrams": list(CM.NGRAMS),
        "vocab": new_vocab,
        "coef": [[round(float(v), 4) for v in row] for row in pruned],
        "intercept": [round(float(v), 4) for v in clf.intercept_],
        "rules": CM.STRONG,
        "rule_bonus": 2.3,
        "trained_examples": len(texts),
    }
    out = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "web", "categorizer.json")
    with open(out, "w") as f:
        json.dump(model, f, separators=(",", ":"))
    print(f"features kept: {len(new_vocab)} / {len(vocab)}   examples: {len(texts)}")
    print(f"wrote {out}   ({os.path.getsize(out)/1024:.0f} KB)")

if __name__ == "__main__":
    main()
