// Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
// Stage 5.5 decrypt: recover the target slots from the folded ciphertexts.
// ct1 target slots [0,120) = monthly category sums; ct2 [0,60) = monthly weekly
// sums, [60,72) = monthly income sums. Public de-scaling happens in the Python
// client harness. Uses the secret key (client only).
#include "pipeline_common.hpp"
#include "ciphertext-ser.h"
#include "cryptocontext-ser.h"
#include "key/key-ser.h"
#include "scheme/ckksrns/ckksrns-ser.h"

#include <iostream>
#include <string>
#include <vector>

using namespace lbcrypto;
using namespace stage5;

static constexpr size_t CT1_TARGETS = 120;  // 12 months * 10 categories
static constexpr size_t CT2_TARGETS = 72;   // 60 weekly + 12 income

int main(int argc, char** argv) {
    if (argc != 5) {
        std::cerr << "usage: decrypt <client_home> <out_ct_dir> <decrypted_dir> <num_batches>\n";
        return 1;
    }
    const std::string client = argv[1], outdir = argv[2], dec = argv[3];
    const int nb = std::stoi(argv[4]);

    CryptoContext<DCRTPoly> cc;
    if (!Serial::DeserializeFromFile(client + "/cc.bin", cc, SerType::BINARY)) return 2;
    cc->Enable(PKE);
    cc->Enable(KEYSWITCH);
    cc->Enable(LEVELEDSHE);
    PrivateKey<DCRTPoly> sk;
    if (!Serial::DeserializeFromFile(client + "/sk.bin", sk, SerType::BINARY)) return 3;

    for (int b = 0; b < nb; ++b) {
        Ciphertext<DCRTPoly> o1, o2;
        Serial::DeserializeFromFile(outdir + "/batch" + std::to_string(b) + "_ct1_out.bin", o1, SerType::BINARY);
        Serial::DeserializeFromFile(outdir + "/batch" + std::to_string(b) + "_ct2_out.bin", o2, SerType::BINARY);
        Plaintext r1, r2;
        cc->Decrypt(sk, o1, &r1);
        cc->Decrypt(sk, o2, &r2);
        r1->SetLength(CT1_TARGETS);
        r2->SetLength(CT2_TARGETS);
        auto a1 = r1->GetRealPackedValue();
        auto a2 = r2->GetRealPackedValue();
        write_f64(dec + "/batch" + std::to_string(b) + "_ct1.f64",
                  std::vector<double>(a1.begin(), a1.begin() + CT1_TARGETS));
        write_f64(dec + "/batch" + std::to_string(b) + "_ct2.f64",
                  std::vector<double>(a2.begin(), a2.begin() + CT2_TARGETS));
    }
    std::cout << "decrypt ok: " << nb << " batches\n";
    return 0;
}
