// Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
// Stage 5.2/5.3 encrypt: read the client-side packed slot vectors (already scaled
// by the public divisor and laid out per the approved interleaved layout) and
// encrypt ct1 (category) and ct2 (weekly+income) per batch. Uses the public key
// only -- never the secret key.
#include "pipeline_common.hpp"
#include "ciphertext-ser.h"
#include "cryptocontext-ser.h"
#include "key/key-ser.h"
#include "scheme/ckksrns/ckksrns-ser.h"

#include <iostream>
#include <string>

using namespace lbcrypto;
using namespace stage5;

int main(int argc, char** argv) {
    if (argc != 5) {
        std::cerr << "usage: encrypt <client_home> <packed_dir> <in_ct_dir> <num_batches>\n";
        return 1;
    }
    const std::string client = argv[1], packed = argv[2], out = argv[3];
    const int nb = std::stoi(argv[4]);

    CryptoContext<DCRTPoly> cc;
    if (!Serial::DeserializeFromFile(client + "/cc.bin", cc, SerType::BINARY)) return 2;
    cc->Enable(PKE);
    cc->Enable(KEYSWITCH);
    cc->Enable(LEVELEDSHE);
    PublicKey<DCRTPoly> pk;
    if (!Serial::DeserializeFromFile(client + "/pk.bin", pk, SerType::BINARY)) return 3;

    for (int b = 0; b < nb; ++b) {
        auto v1 = read_f64(packed + "/batch" + std::to_string(b) + "_ct1.f64", SLOTS);
        auto v2 = read_f64(packed + "/batch" + std::to_string(b) + "_ct2.f64", SLOTS);
        auto p1 = cc->MakeCKKSPackedPlaintext(v1);
        auto p2 = cc->MakeCKKSPackedPlaintext(v2);
        auto c1 = cc->Encrypt(pk, p1);
        auto c2 = cc->Encrypt(pk, p2);
        Serial::SerializeToFile(out + "/batch" + std::to_string(b) + "_ct1_in.bin", c1, SerType::BINARY);
        Serial::SerializeToFile(out + "/batch" + std::to_string(b) + "_ct2_in.bin", c2, SerType::BINARY);
    }
    std::cout << "encrypt ok: " << nb << " batches\n";
    return 0;
}
