// Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
// Stage 5.1 keygen: context + public key + secret key + ONLY the six rotation
// keys. The secret key is written to the CLIENT home only; the server home
// receives the context and rotation keys (no secret key).
#include "pipeline_common.hpp"
#include "ciphertext-ser.h"
#include "cryptocontext-ser.h"
#include "key/key-ser.h"
#include "scheme/ckksrns/ckksrns-ser.h"

#include <filesystem>
#include <iostream>
#include <sys/stat.h>

using namespace lbcrypto;
using namespace stage5;

int main(int argc, char** argv) {
    if (argc != 3) {
        std::cerr << "usage: keygen <client_home> <server_home>\n";
        return 1;
    }
    const std::string client = argv[1], server = argv[2];
    std::filesystem::create_directories(client);
    std::filesystem::create_directories(server);

    CCParams<CryptoContextCKKSRNS> p;
    p.SetMultiplicativeDepth(1);          // circuit depth is 0; library minimum
    p.SetScalingModSize(50);
    p.SetFirstModSize(60);
    p.SetRingDim(RING);                   // explicit 65536
    p.SetSecurityLevel(HEStd_128_classic);
    p.SetScalingTechnique(FLEXIBLEAUTO);
    p.SetKeySwitchTechnique(HYBRID);

    auto cc = GenCryptoContext(p);
    cc->Enable(PKE);
    cc->Enable(KEYSWITCH);
    cc->Enable(LEVELEDSHE);
    if (cc->GetRingDimension() != RING) {
        std::cerr << "FAIL: ring dimension != 65536\n";
        return 2;
    }

    auto keys = cc->KeyGen();
    cc->EvalRotateKeyGen(keys.secretKey, ALL_ROTATIONS);  // 6 rotation keys only

    bool ok = true;
    ok &= Serial::SerializeToFile(client + "/cc.bin", cc, SerType::BINARY);
    ok &= Serial::SerializeToFile(client + "/pk.bin", keys.publicKey, SerType::BINARY);
    ok &= Serial::SerializeToFile(client + "/sk.bin", keys.secretKey, SerType::BINARY);  // client only
    ok &= Serial::SerializeToFile(server + "/cc.bin", cc, SerType::BINARY);
    {
        std::ofstream f(server + "/rotkeys.bin", std::ios::out | std::ios::binary);
        ok &= cc->SerializeEvalAutomorphismKey(f, SerType::BINARY);
    }
    if (!ok) {
        std::cerr << "FAIL: serialization\n";
        return 3;
    }
    // Confine the secret key to the owner: 0700 client home, 0600 sk.bin. The CKKS
    // secret key must not be world-readable on a multi-user host.
    ::chmod(client.c_str(), S_IRWXU);                             // 0700
    ::chmod((client + "/sk.bin").c_str(), S_IRUSR | S_IWUSR);     // 0600
    std::cout << "keygen ok: N=" << cc->GetRingDimension()
              << " rotations={128,256,512,1024,2048,4096} relin=none\n";
    return 0;
}
