// Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
// Shared constants + I/O + the fold (rotations + additions only) for the Stage 5
// two-ciphertext CKKS aggregation pipeline. NO ct x ct multiply, NO relin.
#pragma once
#include "openfhe.h"
#include <fstream>
#include <stdexcept>
#include <string>
#include <vector>

using namespace lbcrypto;

namespace stage5 {

constexpr uint32_t RING = 65536;
constexpr uint32_t SLOTS = RING / 2;  // 32768

// Fold rotation schedules for the two ciphertexts (from the approved layout).
inline const std::vector<int32_t> CT1_ROTATIONS = {128, 256, 512, 1024, 2048};
inline const std::vector<int32_t> CT2_ROTATIONS = {128, 256, 512, 1024, 2048, 4096};
// Union actually generated at keygen (ct1's set is a subset of ct2's).
inline const std::vector<int32_t> ALL_ROTATIONS = {128, 256, 512, 1024, 2048, 4096};

inline std::vector<double> read_f64(const std::string& path, size_t n) {
    std::ifstream f(path, std::ios::in | std::ios::binary);
    if (!f) throw std::runtime_error("cannot open " + path);
    std::vector<double> v(n);
    f.read(reinterpret_cast<char*>(v.data()), static_cast<std::streamsize>(n * sizeof(double)));
    if (!f) throw std::runtime_error("short read " + path);
    return v;
}

inline void write_f64(const std::string& path, const std::vector<double>& v) {
    std::ofstream f(path, std::ios::out | std::ios::binary);
    if (!f) throw std::runtime_error("cannot write " + path);
    f.write(reinterpret_cast<const char*>(v.data()),
            static_cast<std::streamsize>(v.size() * sizeof(double)));
}

// Interleaved rotate-and-sum fold: rotations + additions only (depth 0).
inline Ciphertext<DCRTPoly> fold(const CryptoContext<DCRTPoly>& cc,
                                 Ciphertext<DCRTPoly> ct,
                                 const std::vector<int32_t>& rotations) {
    Ciphertext<DCRTPoly> acc = ct;
    for (int32_t r : rotations) {
        Ciphertext<DCRTPoly> rotated = cc->EvalRotate(acc, r);
        acc = cc->EvalAdd(acc, rotated);
    }
    return acc;
}

}  // namespace stage5
