# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Stage 5 encrypted test harness.

Client-side packing (reference.twin.build_batches, Stage-3 verified) produces the
exact interleaved slot vectors; the four C++ programs run the real CKKS
keygen -> encrypt -> server-fold -> decrypt; this driver recombines the decrypted
target slots, reverses the public scaling, and compares against BOTH the direct
plaintext oracle and the numpy packed-layout twin, with combined absolute/relative
tolerances, plus conservation checks. Reports errors, runtime, memory, and sizes.
"""

import os
import subprocess
import sys
import time
from collections import defaultdict

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from reference import fixtures, layout, scaling            # noqa: E402
from reference.aggregate import direct_aggregate           # noqa: E402
from reference.twin import build_batches, twin_aggregate   # noqa: E402

BIN = os.path.join(ROOT, "stage5", "build")
RUN = os.path.join(ROOT, "stage5", "run")
CLIENT = os.path.join(RUN, "client_home")
SERVER = os.path.join(RUN, "server_home")

ABS_TOL = 1e-2   # 1 cent
REL_TOL = 1e-4
REL_FLOOR = 1.0  # only score relative error where |oracle| >= $1

CT1_TARGETS, CT2_TARGETS = 120, 72


def run(cmd):
    t0 = time.perf_counter()
    p = subprocess.run(cmd, capture_output=True, text=True)
    dt = time.perf_counter() - t0
    if p.returncode != 0:
        raise RuntimeError(f"cmd failed ({p.returncode}): {' '.join(cmd)}\n{p.stderr}")
    return dt, p.stdout.strip()


def run_with_rss(cmd):
    """Run under /usr/bin/time -l, return (wall, peak_rss_bytes, stdout)."""
    t0 = time.perf_counter()
    p = subprocess.run(["/usr/bin/time", "-l"] + cmd, capture_output=True, text=True)
    dt = time.perf_counter() - t0
    if p.returncode != 0:
        raise RuntimeError(f"cmd failed: {' '.join(cmd)}\n{p.stderr}")
    rss = None
    for line in p.stderr.splitlines():
        if "maximum resident set size" in line:
            rss = int(line.strip().split()[0])   # bytes on macOS
    return dt, rss, p.stdout.strip()


def export_packed(batches, packed_dir):
    os.makedirs(packed_dir, exist_ok=True)
    for i, b in enumerate(batches):
        b.ct1.astype("<f8").tofile(os.path.join(packed_dir, f"batch{i}_ct1.f64"))
        b.ct2.astype("<f8").tofile(os.path.join(packed_dir, f"batch{i}_ct2.f64"))


def recombine_decrypted(batches, dec_dir, scale):
    """Read decrypted target slots and recombine additively across batches."""
    cat, week, income = defaultdict(float), defaultdict(float), defaultdict(float)
    for i, b in enumerate(batches):
        a1 = np.fromfile(os.path.join(dec_dir, f"batch{i}_ct1.f64"), dtype="<f8", count=CT1_TARGETS)
        a2 = np.fromfile(os.path.join(dec_dir, f"batch{i}_ct2.f64"), dtype="<f8", count=CT2_TARGETS)
        base = b.group * layout.MONTHS_PER_BATCH
        for mm in range(layout.MONTHS_PER_BATCH):
            gm = base + mm
            for c in range(layout.N_CATEGORIES):
                cat[(gm, c)] += a1[mm * 10 + c]
            for w in range(layout.WEEK_BINS):
                week[(gm, w)] += a2[mm * 5 + w]
            income[gm] += a2[layout.INCOME_BASE + mm]
    unscale = scaling.unscale
    return {"cat": {k: unscale(v, scale) for k, v in cat.items()},
            "week": {k: unscale(v, scale) for k, v in week.items()},
            "income": {k: unscale(v, scale) for k, v in income.items()}}


def error_stats(ckks, ref):
    """Per-stream max abs, max rel, RMSE of ckks vs ref over the union of keys."""
    out = {}
    for stream in ("cat", "week", "income"):
        keys = set(ckks[stream]) | set(ref[stream])
        max_abs = max_rel = 0.0
        sq = 0.0
        n = 0
        for k in keys:
            a = ckks[stream].get(k, 0.0)
            b = ref[stream].get(k, 0.0)
            e = abs(a - b)
            max_abs = max(max_abs, e)
            if abs(b) >= REL_FLOOR:
                max_rel = max(max_rel, e / abs(b))
            sq += e * e
            n += 1
        out[stream] = {"max_abs": max_abs, "max_rel": max_rel,
                       "rmse": (sq / n) ** 0.5 if n else 0.0, "n": n}
    return out


def within_tol(stats):
    return all(s["max_abs"] <= ABS_TOL or s["max_rel"] <= REL_TOL for s in stats.values())


def stream_total(agg, stream):
    return sum(agg[stream].values())


def keygen_once():
    import shutil
    if os.path.exists(RUN):
        shutil.rmtree(RUN)
    os.makedirs(RUN)
    dt, out = run([os.path.join(BIN, "keygen"), CLIENT, SERVER])
    # trust-boundary: server home must not contain the secret key
    assert not os.path.exists(os.path.join(SERVER, "sk.bin")), "sk leaked to server home!"
    sizes = {name: os.path.getsize(os.path.join(d, f))
             for d, name, f in [(CLIENT, "cc", "cc.bin"), (CLIENT, "pk", "pk.bin"),
                                (CLIENT, "sk", "sk.bin"), (SERVER, "rotkeys", "rotkeys.bin")]}
    return dt, out, sizes


def run_fixture(name, gen):
    txns = gen()
    direct, base = direct_aggregate(txns)
    batches, meta = build_batches(txns, base=base)
    twin = twin_aggregate(batches)
    nb = len(batches)

    fdir = os.path.join(RUN, "fixtures", name)
    packed = os.path.join(fdir, "packed")
    inct = os.path.join(fdir, "in")
    outct = os.path.join(fdir, "out")
    dec = os.path.join(fdir, "dec")
    for d in (packed, inct, outct, dec):
        os.makedirs(d, exist_ok=True)
    export_packed(batches, packed)

    t_enc, _ = run([os.path.join(BIN, "encrypt"), CLIENT, packed, inct, str(nb)])
    # measure server stage RSS (the compute stage) on the largest / each fixture
    t_srv, rss, _ = run_with_rss([os.path.join(BIN, "server"), SERVER, inct, outct, str(nb)])
    t_dec, _ = run([os.path.join(BIN, "decrypt"), CLIENT, outct, dec, str(nb)])

    ckks = recombine_decrypted(batches, dec, scaling.DEFAULT_SCALE)

    vs_oracle = error_stats(ckks, direct)
    vs_twin = error_stats(ckks, twin)

    # conservation (CKKS side)
    exp_sum = sum(t["amount"] for t in txns if t["type"] == "expense")
    inc_sum = sum(t["amount"] for t in txns if t["type"] == "income")
    cons = {
        "cat_total": stream_total(ckks, "cat"), "week_total": stream_total(ckks, "week"),
        "income_total": stream_total(ckks, "income"),
        "expense_ref": exp_sum, "income_ref": inc_sum,
        "cat_resid": abs(stream_total(ckks, "cat") - exp_sum),
        "week_resid": abs(stream_total(ckks, "week") - exp_sum),
        "income_resid": abs(stream_total(ckks, "income") - inc_sum),
    }
    # placement conservation (from the packer meta)
    n_exp = sum(1 for t in txns if t["type"] == "expense")
    n_inc = sum(1 for t in txns if t["type"] == "income")
    placement_ok = (meta["ct1_placements"] == n_exp and
                    meta["ct2_week_placements"] == n_exp and
                    meta["ct2_income_placements"] == n_inc)

    return {
        "name": name, "n_txn": len(txns), "n_batches": nb,
        "groups": sorted({b.group for b in batches}),
        "has_overflow_layer": any(b.layer >= 1 for b in batches),
        "vs_oracle": vs_oracle, "vs_twin": vs_twin, "cons": cons,
        "placement_ok": placement_ok,
        "t_enc": t_enc, "t_srv": t_srv, "t_dec": t_dec, "server_rss": rss,
        "pass": within_tol(vs_oracle) and within_tol(vs_twin) and placement_ok
        and cons["cat_resid"] <= ABS_TOL and cons["week_resid"] <= ABS_TOL
        and cons["income_resid"] <= ABS_TOL,
    }


def main():
    print("=" * 78)
    print("STAGE 5 — encrypted two-ciphertext CKKS aggregation, end-to-end test")
    print("=" * 78)
    kdt, kout, ksz = keygen_once()
    mb = lambda b: b / (1024 * 1024)
    print(f"\n[keygen] {kout}  ({kdt:.2f}s)")
    print(f"  cc={ksz['cc']}B  pk={mb(ksz['pk']):.2f}MB  sk={mb(ksz['sk']):.2f}MB  "
          f"rotkeys(6)={mb(ksz['rotkeys']):.2f}MB")
    print("  trust boundary: server home has NO sk.bin  [OK]")

    results = [run_fixture(n, g) for n, g in fixtures.ALL_GENERATORS.items()]

    # sample ciphertext sizes from the basic fixture
    ct_in = os.path.join(RUN, "fixtures", "basic", "in", "batch0_ct1_in.bin")
    ct_out = os.path.join(RUN, "fixtures", "basic", "out", "batch0_ct1_out.bin")
    print(f"\n[sizes] input ct={mb(os.path.getsize(ct_in)):.2f}MB  "
          f"folded output ct={mb(os.path.getsize(ct_out)):.2f}MB")

    print("\n" + "-" * 78)
    print("PER-FIXTURE RESULTS")
    print("-" * 78)
    for r in results:
        status = "PASS" if r["pass"] else "FAIL"
        print(f"\n[{status}] {r['name']}: {r['n_txn']} txns, {r['n_batches']} batch(es), "
              f"groups={r['groups']}, overflow_layer={r['has_overflow_layer']}")
        for label, key in [("CKKS vs oracle", "vs_oracle"), ("CKKS vs twin ", "vs_twin")]:
            for stream in ("cat", "week", "income"):
                s = r[key][stream]
                print(f"    {label} [{stream:6}] max_abs={s['max_abs']:.3e}  "
                      f"max_rel={s['max_rel']:.3e}  rmse={s['rmse']:.3e}")
        c = r["cons"]
        print(f"    conservation: cat_resid={c['cat_resid']:.3e}  "
              f"week_resid={c['week_resid']:.3e}  income_resid={c['income_resid']:.3e}  "
              f"placement_ok={r['placement_ok']}")
        rss = f"{mb(r['server_rss']):.0f}MB" if r["server_rss"] else "n/a"
        print(f"    timing: encrypt={r['t_enc']:.2f}s server={r['t_srv']:.2f}s "
              f"decrypt={r['t_dec']:.2f}s  server_peak_rss={rss}")

    npass = sum(r["pass"] for r in results)
    print("\n" + "=" * 78)
    print(f"SUMMARY: {npass}/{len(results)} fixtures PASS  "
          f"(abs_tol={ABS_TOL}, rel_tol={REL_TOL})")
    print("=" * 78)
    return 0 if npass == len(results) else 1


if __name__ == "__main__":
    sys.exit(main())
