// Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
// Stage 5.4 server: interleaved rotate-and-sum fold of ct1 and ct2 per batch.
// Rotations + additions only -- no ct x ct multiply, no decryption, no secret
// key. Refuses to run if a secret key is present in the server home.
#include "pipeline_common.hpp"
#include "ciphertext-ser.h"
#include "cryptocontext-ser.h"
#include "key/key-ser.h"
#include "scheme/ckksrns/ckksrns-ser.h"

#include <filesystem>
#include <iostream>
#include <string>

using namespace lbcrypto;
using namespace stage5;

int main(int argc, char** argv) {
    if (argc != 5) {
        std::cerr << "usage: server <server_home> <in_ct_dir> <out_ct_dir> <num_batches>\n";
        return 1;
    }
    const std::string server = argv[1], in = argv[2], out = argv[3];
    const int nb = std::stoi(argv[4]);

    // Trust-boundary guard: the server must never hold the secret key.
    if (std::filesystem::exists(server + "/sk.bin")) {
        std::cerr << "REFUSE: secret key present in server home\n";
        return 2;
    }

    CryptoContext<DCRTPoly> cc;
    if (!Serial::DeserializeFromFile(server + "/cc.bin", cc, SerType::BINARY)) return 3;
    cc->Enable(PKE);
    cc->Enable(KEYSWITCH);
    cc->Enable(LEVELEDSHE);
    {
        std::ifstream f(server + "/rotkeys.bin", std::ios::in | std::ios::binary);
        if (!cc->DeserializeEvalAutomorphismKey(f, SerType::BINARY)) return 4;
    }

    for (int b = 0; b < nb; ++b) {
        Ciphertext<DCRTPoly> c1, c2;
        Serial::DeserializeFromFile(in + "/batch" + std::to_string(b) + "_ct1_in.bin", c1, SerType::BINARY);
        Serial::DeserializeFromFile(in + "/batch" + std::to_string(b) + "_ct2_in.bin", c2, SerType::BINARY);
        auto o1 = fold(cc, c1, CT1_ROTATIONS);
        auto o2 = fold(cc, c2, CT2_ROTATIONS);
        Serial::SerializeToFile(out + "/batch" + std::to_string(b) + "_ct1_out.bin", o1, SerType::BINARY);
        Serial::SerializeToFile(out + "/batch" + std::to_string(b) + "_ct2_out.bin", o2, SerType::BINARY);
    }
    std::cout << "server ok: folded " << nb << " batches (rotations+adds only)\n";
    return 0;
}
