// Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
// CipherSpend production frontend (vanilla SPA). Renders the REAL Stage-6 result
// contract streamed from the local device runtime; performs no analytics itself.
"use strict";

/* ---------------- state ---------------- */
const S = {view:"landing", screen:"dashboard", result:null, token:null, sel:null,
  cmpA:null, cmpB:null, cmpData:null, cmpLoading:false, serverView:false, coached:false, countedOnce:false,
  csvText:null, inspect:null, cfg:null, preview:null, uploadStep:"select"};
const DATA_SCREENS=["dashboard","timeline","compare","insights"];
const root=document.getElementById("root");
const reduceMotion=()=>matchMedia("(prefers-reduced-motion:reduce)").matches;

/* ---------------- formatting ---------------- */
const fmt=n=>"$"+Math.round(n).toLocaleString("en-US");
const pct=x=>x==null?"—":(x*100).toFixed(1)+"%";
const pp=x=>(x>=0?"+":"")+x.toFixed(1)+" pp";
const sgn=x=>(x>=0?"+":"")+x.toFixed(2);
const word=x=>x>0?"rose":"fell";
const dirCls=x=>x>0?"up":x<0?"down":"flat";
const arrow=x=>x>0?"▲":x<0?"▼":"—";
const gv=(g,f)=>(g&&g.defined)?f(g.value):'<span class="guard">— <span style="font-size:11px">n/a</span></span>';
const esc=s=>String(s).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const MN=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
const mlabel=m=>`${MN[m.month-1]} ${m.year}`;
const niceMonth=iso=>{const p=/^(\d{4})-(\d{2})/.exec(iso||"");return p?`${MN[+p[2]-1]} ${p[1]}`:esc(iso||"");};

/* ---------------- result accessors ---------------- */
const R=()=>S.result;
const cats=()=>R().categories;
const monthByGm=gm=>R().months.find(m=>m.global_m===gm);
const completeMonths=()=>R().months.filter(m=>m.complete);
function prevComplete(gm){const c=completeMonths();const i=c.findIndex(m=>m.global_m===gm);return i>0?c[i-1]:null;}
const essIdx=()=>cats().filter(c=>c.group==="essential").map(c=>c.index);
const discIdx=()=>cats().filter(c=>c.group==="discretionary").map(c=>c.index);

/* ---------------- charts ---------------- */
function rankedBar(m){
  const items=cats().map(c=>({n:c.name,v:m.raw.category_sums[c.index]})).sort((a,b)=>b.v-a.v);
  const max=items[0].v||1;
  return items.map((it,idx)=>`<div class="bar-row"><span class="cat" title="${esc(it.n)}">${esc(it.n)}</span>
    <div class="bar-track"><div class="bar-fill" style="width:${(it.v/max*100).toFixed(1)}%;opacity:${(1-idx*.055).toFixed(2)};animation-delay:${idx*45}ms"></div></div>
    <span class="val money">${fmt(it.v)}</span></div>`).join("");
}
function gauge(g){const v=g&&g.defined?Math.max(-1,Math.min(1,g.value)):0;
  return `<div class="gauge-wrap"><div class="gauge-mark" style="left:${((v+1)/2*100).toFixed(1)}%"></div></div>
  <div class="gauge-scale"><span>−1 outflow</span><span>0</span><span>+1 inflow</span></div>`;}
function meter(val,lbl,rlbl){const w=val==null?0:Math.max(0,Math.min(1,val))*100;
  return `<div class="meter"><div class="row"><span>${lbl}</span><b>${val==null?"—":pct(val)}</b></div>
  <div class="track"><div class="fill" style="width:${w}%"></div></div>${rlbl?`<div class="meter-note">${rlbl}</div>`:""}</div>`;}
function sparkline(vals,w=300,h=58){
  if(!vals.length)return "";
  const mn=Math.min(...vals),mx=Math.max(...vals),rng=(mx-mn)||1;
  const pts=vals.map((v,i)=>[i/Math.max(1,vals.length-1)*w,h-6-(v-mn)/rng*(h-14)]);
  const d=pts.map((p,i)=>(i?"L":"M")+p[0].toFixed(1)+" "+p[1].toFixed(1)).join(" ");
  const area=`M0 ${h} `+pts.map(p=>"L"+p[0].toFixed(1)+" "+p[1].toFixed(1)).join(" ")+` L${w} ${h} Z`;
  const last=pts[pts.length-1];
  return `<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none" style="width:100%;height:${h}px;display:block">
    <path d="${area}" style="fill:var(--acc)" opacity=".08"/><path d="${d}" style="fill:none;stroke:var(--acc)" stroke-width="2" stroke-linejoin="round" stroke-linecap="round"/>
    <circle cx="${last[0].toFixed(1)}" cy="${last[1].toFixed(1)}" r="3.5" style="fill:var(--acc);stroke:var(--surface)" stroke-width="2"/></svg>`;
}
function dumbbell(c){
  const N=cats().length, sa=c.shares_from||[], sb=c.shares_to||[], ppv=c.category_pp_deltas||[];
  const rows=cats().map(cc=>({n:cc.name,a:sa[cc.index]||0,b:sb[cc.index]||0,pp:ppv[cc.index]||0}))
    .sort((x,y)=>Math.abs(y.pp)-Math.abs(x.pp));
  const max=Math.max(...rows.map(r=>Math.max(r.a,r.b)),.01);
  return `<div class="dumb">`+rows.map(r=>{
    const ax=r.a/max*100,bx=r.b/max*100,lo=Math.min(ax,bx),hi=Math.max(ax,bx);
    const dir=r.pp>.05?"up":r.pp<-.05?"down":"flat", col=dir==="up"?"var(--pos)":dir==="down"?"var(--neg)":"var(--muted)";
    return `<div class="dumb-row"><span class="dumb-cat">${esc(r.n)}</span>
      <div class="dumb-track"><div class="dumb-conn" style="left:${lo}%;width:${(hi-lo).toFixed(1)}%;background:${col}"></div>
        <div class="dumb-dot a" style="left:${ax.toFixed(1)}%"></div><div class="dumb-dot b" style="left:${bx.toFixed(1)}%;background:${col}"></div></div>
      <span class="dumb-delta ${dir}">${r.pp>=0?"+":""}${r.pp.toFixed(1)} pp</span></div>`;
  }).join("")+`</div><div class="dumb-legend"><span><i class="a"></i>${niceMonth(c.from)} (share)</span><span><i class="b"></i>${niceMonth(c.to)}</span></div>`;
}

/* ---------------- theme ---------------- */
function toggleTheme(){const cur=document.documentElement.getAttribute("data-theme")||(matchMedia("(prefers-color-scheme:dark)").matches?"dark":"light");
  document.documentElement.setAttribute("data-theme",cur==="dark"?"light":"dark");}

/* ---------------- landing ---------------- */
function landing(){return `<div class="landing">
  <div class="landing-top"><div class="brand"><span class="glyph">◈</span> CipherSpend</div>
    <div style="display:flex;gap:10px;align-items:center"><span class="chip secure">🔒 Private by design</span>
      <button class="iconbtn" data-act="theme" aria-label="Toggle theme">◐</button></div></div>
  <div class="landing-main"><div class="hero">
    <span class="kicker">🔒 Analyzed under encryption — unlocked only on your device</span>
    <h1>Your money, understood.<br><span class="em">Never seen.</span></h1>
    <p class="sub">A local demo that studies your spending in depth while it stays encrypted — the analytics run on ciphertext, and only your device holds the key to read the results.</p>
    <div class="hero-cta"><button class="btn btn-primary btn-lg" data-act="demo">Try demo dataset</button>
      <button class="btn btn-ghost btn-lg" data-act="upload">Use my own data</button></div>
    <button class="learn" data-act="learn">See how it works →</button>
    <div class="how-strip">
      <div class="how-cell"><div class="ic">▣</div><h4>Encrypted on your device</h4><p>Transactions are categorized and scrambled here, before anything leaves.</p></div>
      <div class="how-cell"><div class="ic">⚙</div><h4>Analyzed while encrypted</h4><p>The server computes on the scrambled data with FHE — it never sees your numbers.</p></div>
      <div class="how-cell"><div class="ic">🔑</div><h4>Unlocked only by you</h4><p>Results are decrypted locally, with a key that never leaves your device.</p></div>
    </div></div></div></div>`;}

/* ---------------- on-device merchant classifier (in-browser) ---------------- */
let _modelReady=null, _modelInfo=null;
function ensureModel(){                       // load once; runs concurrently with keygen
  if(!_modelReady && window.CipherCategorizer)
    _modelReady=CipherCategorizer.load("/categorizer.json").then(i=>{_modelInfo=i;return i;}).catch(()=>null);
  return _modelReady||Promise.resolve(null);
}

/* ---------------- onboarding (own-data path) + inline key creation ---------------- */
function startOnboarding(){
  clearTimeout(S.keygenTimer);
  S.view="onboard"; S.isDemo=false; S.keygen={status:"working"};
  ensureModel();                              // load the local classifier alongside key generation
  render();
  fetch("/api/keygen",{method:"POST"}).then(r=>r.json()).then(k=>{
    if(S.view!=="onboard")return;
    S.keygen=(k&&k.ok)?{status:"ready",created:!!k.created}:{status:"ready",created:false,degraded:true};
    render();
    // gentle auto-advance once the key is truly ready; a passive user flows through,
    // an active reader can click Continue or open "Learn more" (which cancels this).
    S.keygenTimer=setTimeout(()=>{if(S.view==="onboard")gotoUpload();}, reduceMotion()?250:1400);
  }).catch(()=>{
    if(S.view!=="onboard")return;
    S.keygen={status:"ready",created:false,degraded:true}; render();
  });
}
function gotoUpload(){clearTimeout(S.keygenTimer);S.view="upload";S.uploadStep="select";render();}
function onboardView(){
  const kg=S.keygen||{status:"working"}, ready=kg.status==="ready";
  const beats=["Encrypted on your device","Analyzed while encrypted","Unlocked only by you"]
    .map(t=>`<span class="onboard-beat"><span class="d"></span>${t}</span>`).join("");
  const sub = !ready
    ? "This happens entirely on your device — nothing is sent anywhere yet."
    : kg.degraded
      ? "Your private key is created and kept on this device — set up the moment you continue, and it never leaves."
      : (kg.created
          ? "It was just created on this device, and it never leaves. The server only ever receives keys that compute on encrypted data — never the one that unlocks it."
          : "It already lives on this device, and it never leaves. The server only ever receives keys that compute on encrypted data — never the one that unlocks it.");
  const inner=`<div class="onboard">
    <span class="eyebrow">${ready?"Ready · on your device":"On your device"}</span>
    <div class="keyring ${ready?"ready":"working"}"><span class="kg">${ready?"🔑":"🔐"}</span></div>
    <h1>${ready?"Your private key is ready":"Preparing your private key…"}</h1>
    <p class="sub">${sub}</p>
    ${ready&&!kg.degraded?`<div class="keydetail">128-bit key · stays on this device · CKKS · ring 65,536</div>`:""}
    <div class="onboard-beats">${beats}</div>
    <div class="onboard-cta"><button class="btn btn-primary btn-lg" data-act="onboard-continue" ${ready?"":"disabled"}>${ready?"Continue to upload →":"Preparing your key…"}</button></div>
    <button class="learn" data-act="learn">New to this? See how it keeps your data private →</button>
  </div>`;
  return `<div class="landing"><div class="landing-top">
    <div class="brand"><span class="glyph">◈</span> CipherSpend</div>
    <button class="btn btn-quiet" data-act="home">← Back</button></div>
    <div class="landing-main">${inner}</div></div>`;
}

/* ---------------- "Learn more" explainer sheet ---------------- */
function learnSheetHTML(){return `<div class="sheet-bg"><div class="sheet">
  <div class="sheet-head"><div><span class="eyebrow" style="color:var(--secure)">How it works</span>
    <h2>Doing the math inside a locked box</h2></div>
    <button class="iconbtn" data-act="sheet-close" aria-label="Close">✕</button></div>
  <p class="sheet-lead">To analyze your spending, most apps first have to see it. CipherSpend doesn't. Your finances are scrambled on your device, and every calculation runs on the scrambled version — useful to you, meaningless to anyone else.</p>
  <div class="learn-steps">
    <div class="learn-step"><div class="ln">1</div><div><h4>Locked on your device</h4><p>Your transactions are encrypted right here, before anything is sent. The key that unlocks them is created on this device and never leaves it.</p></div></div>
    <div class="learn-step"><div class="ln">2</div><div><h4>Analyzed while still locked</h4><p>The server adds up and compares the encrypted figures without ever unlocking them — like doing arithmetic inside a sealed box it can't open.</p></div></div>
    <div class="learn-step"><div class="ln">3</div><div><h4>Unlocked only by you</h4><p>The encrypted results come back and are unlocked on your device, with your key. You see the insights; no one else sees the data behind them.</p></div></div>
  </div>
  <div class="learn-gloss"><b>The technical name is fully homomorphic encryption (FHE)</b> — a way to compute on data that stays encrypted the whole time. It's what lets CipherSpend understand your money without ever seeing it.</div>
  <div class="learn-table">
    <div class="lt-col"><div class="lt-h" style="color:var(--secure)">🔒 Never seen by the server</div>
      <ul><li>Your amounts, categories, and merchants</li><li>Individual transactions and dates</li><li>Your private key and your results</li></ul></div>
    <div class="lt-col"><div class="lt-h">👁 All the server can tell</div>
      <ul><li>The size of the encrypted data</li><li>Roughly how many months you sent</li><li>How long the computation took</li></ul></div>
  </div>
  <div class="sheet-foot"><button class="btn btn-primary" data-act="sheet-close">Got it</button></div>
</div></div>`;}
function openLearnSheet(){clearTimeout(S.keygenTimer);if(document.querySelector(".sheet-bg"))return;
  document.body.insertAdjacentHTML("beforeend",learnSheetHTML());}
function closeLearnSheet(){document.querySelector(".sheet-bg")?.remove();}

/* ---------------- CSV upload flow ---------------- */
function uploadView(){
  if(S.uploadStep==="select")return uploadSelect();
  if(S.uploadStep==="map")return uploadMap();
  if(S.uploadStep==="preview")return uploadPreview();
  return "";
}
function uploadShell(inner){return `<div class="landing"><div class="landing-top">
  <div class="brand"><span class="glyph">◈</span> CipherSpend</div>
  <button class="btn btn-quiet" data-act="home">← Back</button></div>
  <div style="max-width:860px;margin:0 auto;padding:10px clamp(20px,5vw,56px) 60px;width:100%">${inner}</div></div>`;}
function uploadSelect(){return uploadShell(`
  <div class="page-head"><h1>Import your transactions</h1><p>Everything here happens on your device. Your file is parsed and categorized locally — nothing is sent until you encrypt it.</p></div>
  <div id="dropzone" class="dropzone" role="button" tabindex="0" aria-label="Choose or drop a CSV file">
    <input id="csvfile" type="file" accept=".csv,text/csv" hidden>
    <div class="dz-ring"><span class="dz-arrow">↥</span></div>
    <h3>Drag your CSV here</h3>
    <p class="dz-sub">or <span class="dz-browse">browse your files</span></p>
    <p id="filemsg" class="dz-msg"></p>
  </div>
  <div class="dz-foot"><span class="cap">Canonical columns: <b>date, description, amount, category, type</b> — a header row is expected.</span>
    <a class="btn btn-quiet" href="/api/example.csv">↓ Download an example</a></div>`);}
function selOptions(list,sel){return list.map(o=>`<option value="${esc(o)}" ${o===sel?"selected":""}>${esc(o)}</option>`).join("");}

/* --- mapping: auto-confirm obvious matches, ask only for the unclear --- */
const FIELD_LBL={date:"Date",description:"Description",amount:"Amount",category:"Category",type:"Type"};
const REQ_FIELD={date:true,amount:true,category:true};
const SIGN_LBL={type_field:"A type column",amount_sign_neg_expense:"− means expense",amount_sign_pos_expense:"+ means expense"};
function mapComplete(){
  const q=S.inspect,c=S.cfg; if(!q||!c)return false;
  if(!c.mapping.date||!c.mapping.amount)return false;
  if(!c.mapping.category&&!c.auto_categorize)return false;   // a column OR local auto-categorization
  if(!c.sign_mode)return false;
  if(c.sign_mode==="type_field"&&(q.types||[]).some(t=>!c.type_map[t]))return false;
  if((q.categories||[]).some(ct=>!c.category_map[ct]))return false;
  return true;
}
function uploadMap(){
  const q=S.inspect,c=S.cfg;
  const FIELDS=["date","description","amount","category","type"];
  const ddCol=f=>`<select data-map="${f}"><option value="">— none —</option>${selOptions(q.headers,c.mapping[f])}</select>`;
  const rowCol=f=>{const autoCat=f==="category"&&c.auto_categorize;
    const need=!c.mapping[f]&&REQ_FIELD[f]&&!autoCat;
    const tag=autoCat?'<span class="optl">optional · auto-categorized</span>':REQ_FIELD[f]?'<span class="reqd">required</span>':'<span class="optl">optional</span>';
    return `<div class="maprow ${need?'need':''}"><span class="ml">${FIELD_LBL[f]}${tag}</span>${ddCol(f)}</div>`;};
  const chipCol=f=>`<span class="mapchip"><b>${FIELD_LBL[f]}</b><span class="ar">→</span>${esc(c.mapping[f])}${q.mapping_confidence[f]==="fuzzy"?'<span class="mc-tag auto">auto-detected</span>':'<span class="mc-tag ok">✓</span>'}</span>`;
  const matched=FIELDS.filter(f=>c.mapping[f]), unmatched=FIELDS.filter(f=>!c.mapping[f]);
  let colsBody;
  if(S.reviewCols)colsBody=`<div class="maprows">${FIELDS.map(rowCol).join("")}</div><button class="linkbtn" data-act="review-cols">Done</button>`;
  else colsBody=`${unmatched.length?`<div class="maprows">${unmatched.map(rowCol).join("")}</div>`:""}
    ${matched.length?`<div class="autobox"><div class="autobox-head"><span class="ok-dot">✓</span> ${matched.length} column${matched.length>1?'s':''} matched automatically <button class="linkbtn" data-act="review-cols">Change</button></div><div class="chips">${matched.map(chipCol).join("")}</div></div>`:""}`;

  const signSet=!!c.sign_mode;
  const signSeg=`<div class="seg">${q.sign_options.map(o=>`<button class="${c.sign_mode===o?'active':''}" data-sign="${o}">${SIGN_LBL[o]}</button>`).join("")}</div>`;
  const signCard=`<div class="card ${signSet?'':'attn'}"><div class="card-h"><h3>How is income vs. expense marked?</h3>${signSet?'<span class="pill-ok">confirmed</span>':'<span class="pill-attn">needs your choice</span>'}</div>
    <div class="cap">We never guess this.${(q.flags.negatives&&q.flags.positives)?' Your amounts include both + and − values.':''}</div>${signSeg}
    <label class="chkrow"><input type="checkbox" data-flagged ${c.include_flagged?"checked":""}> Include transfer / refund-like rows (excluded by default)</label></div>`;

  let typeCard="";
  if(c.sign_mode==="type_field"&&(q.types||[]).length){
    const recog=q.types.filter(t=>c.type_map[t]), unrec=q.types.filter(t=>!c.type_map[t]);
    const ddT=t=>`<div class="maprow ${!c.type_map[t]?'need':''}"><span class="ml">${esc(t)}</span><select data-typemap="${esc(t)}"><option value="">— choose —</option>${["income","expense","exclude"].map(o=>`<option ${c.type_map[t]===o?"selected":""}>${o}</option>`).join("")}</select></div>`;
    const chipT=t=>`<span class="mapchip"><b>${esc(t)}</b><span class="ar">→</span>${esc(c.type_map[t])}<span class="mc-tag ok">✓</span></span>`;
    const body=S.reviewTypes?`<div class="maprows">${q.types.map(ddT).join("")}</div><button class="linkbtn" data-act="review-types">Done</button>`
      :`${unrec.length?`<div class="maprows">${unrec.map(ddT).join("")}</div>`:""}${recog.length?`<div class="autobox"><div class="autobox-head"><span class="ok-dot">✓</span> ${recog.length} recognized <button class="linkbtn" data-act="review-types">Review</button></div><div class="chips">${recog.map(chipT).join("")}</div></div>`:""}`;
    typeCard=`<div class="card"><div class="card-h"><h3>Transaction types</h3></div><div class="cap">map each value to income or expense</div>${body}</div>`;
  }

  const ddCat=ct=>{const opts=["Income","Exclude",...q.taxonomy];return `<div class="maprow ${!c.category_map[ct]?'need':''}"><span class="ml">${esc(ct)}</span><select data-catmap="${esc(ct)}"><option value="">— choose —</option>${opts.map(o=>`<option ${c.category_map[ct]===o?"selected":""}>${esc(o)}</option>`).join("")}</select></div>`;};
  const chipCat=ct=>`<span class="mapchip"><b>${esc(ct)}</b><span class="ar">→</span>${esc(c.category_map[ct])}<span class="mc-tag ok">✓</span></span>`;
  const recogC=(q.categories||[]).filter(ct=>c.category_map[ct]), unrecC=(q.categories||[]).filter(ct=>!c.category_map[ct]);
  let catBody;
  if(!(q.categories||[]).length)catBody=c.mapping.category
    ? `<p class="cap">No category values found in that column.</p>`
    : `<div class="autobox"><div class="autobox-head"><span class="ok-dot">🔒</span> No category column — CipherSpend will categorize each transaction <b>locally</b> from its description.</div>
       <div class="cap" style="margin:8px 0 0">Merchant names never leave your device. You'll review anything it can't confidently place, right before analysis. Or map a Category column under <b>Columns</b> to use your own.</div></div>`;
  else if(S.reviewCats)catBody=`<div class="maprows">${q.categories.map(ddCat).join("")}</div><button class="linkbtn" data-act="review-cats">Done</button>`;
  else catBody=`${unrecC.length?`<div class="needlab">${unrecC.length} categor${unrecC.length>1?'ies':'y'} we didn't recognize — map or exclude each</div><div class="maprows">${unrecC.map(ddCat).join("")}</div>`:""}${recogC.length?`<div class="autobox"><div class="autobox-head"><span class="ok-dot">✓</span> ${recogC.length} of ${q.categories.length} categories recognized <button class="linkbtn" data-act="review-cats">Review</button></div><div class="chips">${recogC.map(chipCat).join("")}</div></div>`:""}`;
  const catCard=`<div class="card"><div class="card-h"><h3>Categories</h3></div><div class="cap">each maps to one of the ${q.taxonomy.length} standard categories, or Income / Exclude</div>${catBody}</div>`;

  const fl=q.flags,fn=[fl.currency_symbols?`${fl.currency_symbols} row(s) with non-USD currency symbols will be set aside (no auto-conversion).`:"",
    fl.duplicates?`${fl.duplicates} exact-duplicate row(s) detected — kept as-is; review if unintended.`:""].filter(Boolean);
  const ready=mapComplete();
  return uploadShell(`
    <div class="page-head"><h1>Review &amp; categorize</h1><p>${q.row_count} rows${q.date_range?` · ${niceMonth(q.date_range[0])} → ${niceMonth(q.date_range[1])}`:""}. We matched what we could; only what's unclear needs you.</p></div>
    <div class="card"><div class="card-h"><h3>Columns</h3></div><div class="cap">how your file's columns map to the canonical fields</div>${colsBody}</div>
    ${signCard}${typeCard}${catCard}
    ${fn.length?`<div class="note warn"><span class="ni">!</span><div>${fn.join("<br>")}</div></div>`:""}
    <div class="map-foot"><button class="btn btn-primary btn-lg" data-act="do-preview" ${ready?'':'disabled'}>Preview import →</button>
      <button class="btn btn-ghost" data-act="home">Cancel</button>
      ${ready?'':'<span class="foot-hint">Finish the highlighted fields to continue</span>'}</div>`);
}
const INVLBL={date:"unreadable dates",amount:"invalid amounts",currency:"non-USD amounts (not auto-converted)",
  zero:"zero amounts",unmapped_category:"unmapped categories",unmapped_type:"unmapped types",other:"other issues"};
function uploadPreview(){
  const p=S.preview;
  const total=p.counts.total, comp=p.complete_months||0, part=p.partial_months||0, inv=p.counts.invalid||0;
  const isum=p.invalid_summary||{};
  const excl=p.counts.excluded||0;
  const unmapped=(isum.unmapped_category||0)+(isum.unmapped_type||0);
  const catz=p.categorization||{}, flagged=p.flagged||0, uncat=p.uncategorized||0, other=catz.other||0;
  const TAX=(S.inspect&&S.inspect.taxonomy)||[];
  const y=p.rows_total||(total+inv+excl+uncat);      // every data row read from the file
  const x=total;                                     // rows that will be analyzed
  const N=n=>Number(n).toLocaleString("en-US");
  // Only STRUCTURAL problems block: an unmapped-column gap, or (rare) rows with no
  // merchant text to categorize. Low-confidence classifications are analyzed as a
  // best guess and their review is OPTIONAL — it never blocks the run.
  const blockedMap=unmapped>0 && (unmapped>=x || unmapped>=0.10*y);
  const blocked=blockedMap || uncat>0;

  const covParts=[];
  if(flagged)covParts.push(`${N(flagged)} optional to review`);
  if(excl)covParts.push(`${N(excl)} excluded`); if(inv)covParts.push(`${N(inv)} invalid`);
  if(uncat)covParts.push(`${N(uncat)} need attention`);
  const coverage=`<div class="coverage ${blocked?'bad':((flagged||inv||excl)?'warn':'ok')}">
    <div class="cov-main"><b>${N(x)}</b> of <b>${N(y)}</b> rows will be analyzed</div>
    <div class="cov-sub">${covParts.length?covParts.join(" · "):"Every row will be included."}</div></div>`;

  const catSummary=catz.enabled?`<div class="card"><div class="card-h"><h3>Categorized automatically on your device</h3><span class="pill-ok">🔒 local model · nothing sent</span></div>
    <div class="cap">A local AI model inferred a category for every transaction from its description — no manual work needed. Merchant names never left this device${S.cfg&&S.cfg._catms?` · ${S.cfg._catms} ms`:""}.</div>
    <div class="catstats catstats4"><div class="catstat"><b>${N(catz.auto||0)}</b><span>high confidence</span></div>
      <div class="catstat"><b>${N(catz.flagged||0)}</b><span>medium<br>(optional review)</span></div>
      <div class="catstat ${other?'attn':''}"><b>${N(other)}</b><span>uncertain<br>(“Other”, flagged)</span></div>
      <div class="catstat"><b>${N(catz.user_excluded||0)}</b><span>excluded by you</span></div></div></div>`:"";

  // OPTIONAL review — already analyzed; correct any you like, or ignore entirely
  const reviewCard=(catz.review_items&&catz.review_items.length)?`<details class="card reviewcard"><summary><span><b>Optional:</b> fine-tune ${N(flagged)} lower-confidence transaction(s) across ${N(catz.review_items.length)} merchant(s)</span><span class="pill-muted">not required</span></summary>
    <div class="cap" style="margin-top:10px">Each is already included with a best-guess category. Adjust any you want — it applies to every matching transaction — or exclude one.</div>
    <div class="maprows" style="margin-top:12px">${catz.review_items.map(it=>`<div class="maprow"><span class="ml">${esc(it.sample||"(no description)")}${it.count>1?` <span class="optl">${N(it.count)} txns</span>`:''} ${it.uncertain?'<span class="mc-tag other">Other</span>':`<span class="mc-tag auto">${esc(it.suggested)}</span>`}</span>
      <select data-review="${esc(it.key)}"><option value="">${it.uncertain?'— pick a category —':`keep: ${esc(it.suggested)}`}</option>${TAX.map(cc=>`<option>${esc(cc)}</option>`).join("")}<option value="__exclude__">Exclude from analysis</option></select></div>`).join("")}</div></details>`:"";

  if(total===0 && uncat===0){
    return uploadShell(`
      <div class="page-head"><h1>Nothing to analyze yet</h1><p>Your last checkpoint on-device — and here, no rows could be used.</p></div>
      ${coverage}
      <div class="emptybox"><div class="eb-icon">◍</div><h3>No usable transactions found</h3>
        <p>${inv?`All ${N(inv)} row(s) were set aside — 0 of ${N(y)} could be used. Nothing was guessed or dropped silently; here's why:`:'This file had no rows we could read.'}</p>
        ${inv?`<ul class="reasons">${Object.entries(isum).map(([k,n])=>`<li><b>${N(n)}</b> ${INVLBL[k]||k}</li>`).join("")}</ul>`:""}
        <div class="eb-cta"><button class="btn btn-primary" data-act="back-map">← Adjust mapping</button><button class="btn btn-ghost" data-act="home">Choose another file</button></div></div>`);
  }

  const banners=[];
  if(blockedMap)banners.push(`<div class="note bad"><span class="ni">!</span><div><b>Most of your data won't be analyzed.</b> ${N(unmapped)} of ${N(y)} rows can't be used because their categories or types aren't mapped — that's not a full run. Map or exclude them first; analysis is blocked until then. <button class="linkbtn" data-act="back-map">Adjust mapping →</button></div></div>`);
  else if(unmapped)banners.push(`<div class="note warn"><span class="ni">!</span><div><b>${N(unmapped)} row(s) aren't mapped yet.</b> Go back and map every category and type so nothing is skipped. <button class="linkbtn" data-act="back-map">Adjust mapping →</button></div></div>`);
  if(uncat)banners.push(`<div class="note bad"><span class="ni">!</span><div><b>${N(uncat)} transaction(s) have no merchant text to categorize.</b> They're held for your attention — not analyzed and not dropped. Resolve or exclude them to continue.</div></div>`);
  if(comp===0&&part>0)banners.push(`<div class="note info"><span class="ni">◐</span><div><b>Only partial month(s).</b> You can browse them, but trends, baselines, and comparisons need at least one complete calendar month.</div></div>`);
  else if(comp===1)banners.push(`<div class="note info"><span class="ni">1</span><div><b>One complete month.</b> Your dashboard will be ready; add another month later to unlock trends and comparisons.</div></div>`);
  if((p.est_batches||1)>1)banners.push(`<div class="note info"><span class="ni">⧉</span><div><b>~${p.est_batches} encrypted batches.</b> Longer histories are split into ${p.months_per_batch}-month batches — normal. It only affects the coarse history length the server can infer, never your values.</div></div>`);

  const rows=(p.invalid_rows||[]).slice(0,10).map(r=>`<tr><td class="mono">row ${r.row}</td><td>${esc(r.reason)}</td></tr>`).join("");
  const footHint=uncat>0?`Resolve the ${N(uncat)} transaction(s) with no merchant text to continue`
    :blockedMap?`Blocked — map or exclude the unmapped rows to run on your full history`:"";
  return uploadShell(`
    <div class="page-head"><h1>Import preview</h1><p>Review before anything is encrypted. This is your last checkpoint on-device.</p></div>
    ${coverage}
    ${catSummary}
    ${reviewCard}
    ${banners.join("")}
    <div class="kpis" style="margin-bottom:16px">
      <div class="stat"><div class="lbl">Will be analyzed</div><div class="fig money">${N(x)}</div><div class="delta flat">${N(p.counts.expense)} expense · ${N(p.counts.income)} income</div></div>
      <div class="stat"><div class="lbl">Total spending</div><div class="fig money">${fmt(p.totals.spend)}</div></div>
      <div class="stat"><div class="lbl">Total income</div><div class="fig money">${fmt(p.totals.income)}</div></div>
      <div class="stat"><div class="lbl">Months</div><div class="fig money">${comp}<span class="fig-sub"> complete${part?` · +${part} partial`:''}</span></div></div></div>
    ${p.warnings.length?`<div class="card"><div class="card-h"><h3>Good to know</h3></div><ul class="tidy">${p.warnings.map(w=>`<li>${esc(w)}</li>`).join("")}</ul></div>`:""}
    ${inv?`<div class="card"><div class="card-h"><h3>${N(inv)} row(s) set aside</h3><span class="pill-muted">skipped, not deleted</span></div>
      <div class="cap">Nothing was guessed or silently dropped. What was set aside:</div>
      <div class="reason-chips">${Object.entries(isum).map(([k,n])=>`<span class="rchip"><b>${N(n)}</b> ${INVLBL[k]||k}</span>`).join("")}</div>
      <table class="tbl" style="margin-top:12px"><tbody>${rows}</tbody></table>${p.invalid_truncated?`<p class="cap" style="margin-top:8px">…and ${N(p.invalid_truncated)} more</p>`:""}</div>`:""}
    <div class="map-foot">${blocked
      ? `${blockedMap?`<button class="btn btn-primary btn-lg" data-act="back-map">← Adjust mapping</button>`:''}<button class="btn ${blockedMap?'btn-ghost':'btn-primary'} btn-lg" disabled>🔒 Encrypt &amp; analyze</button><span class="foot-hint">${footHint}</span>`
      : `<button class="btn btn-primary btn-lg" data-act="do-analyze">🔒 Encrypt &amp; analyze</button><button class="btn btn-ghost" data-act="back-map">← Adjust mapping</button>`}</div>`);
}
function rePreview(){
  fetch("/api/preview",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:S.csvText,cfg:S.cfg})})
    .then(r=>r.json()).then(p=>{S.preview=p;render();});
}

/* ---------------- FHE pipeline (real, event-driven) ---------------- */
const STAGES=[
 {key:"read",t:"Reading & categorizing",zl:"On your device",z:"dev"},
 {key:"encrypt",t:"Encrypting locally",zl:"On your device",z:"dev"},
 {key:"upload",t:"Uploading encrypted data",zl:"Crossing the boundary",z:"cross"},
 {key:"compute",t:"Computing on encrypted data",zl:"On the server (blind)",z:"srv"},
 {key:"return",t:"Returning encrypted results",zl:"Crossing the boundary",z:"cross"},
 {key:"decrypt",t:"Decrypting locally",zl:"On your device",z:"dev"},
 {key:"analytics",t:"Building analytics & insights",zl:"On your device",z:"dev"},
];
function pipelineView(){return `<div class="pipe" id="pipe">
  <div class="pipe-top"><div class="brand"><span class="glyph">◈</span> CipherSpend</div><span class="chip secure">🔒 nothing leaves this device unencrypted</span></div>
  <div class="pipe-body"><div class="pipe-inner">
    <div class="pipe-h"><h2>Analyzing your spending — privately</h2><p>Real numbers stay <b>below the lock line</b>; only scrambled ciphertext crosses it. Timings and sizes below are measured live.</p>${(S.preview&&S.preview.categorization&&S.preview.categorization.enabled)?`<p class="pipe-catnote">🔒 ${(S.preview.categorization.auto||0).toLocaleString()} transactions categorized locally from their descriptions${S.preview.categorization.user_excluded?` · ${S.preview.categorization.user_excluded} excluded by you`:""} — merchant names never left this device. Your private key was created in parallel.</p>`:""}</div>
    <div class="diagram"><div class="zone device"><div class="zl">🔒 Your device · plaintext</div><div class="tokens" id="devTokens"></div></div>
      <div class="boundary-col"><div class="boundary"></div></div>
      <div class="zone server"><div class="zl">☁ Server · encrypted only</div><div class="tokens" id="srvTokens"></div><div class="terminal" id="term"></div></div></div>
    <div class="steps" id="steps">${STAGES.map((s,i)=>`<div class="step" data-k="${s.key}"><div class="dot">${i+1}</div>
      <div><span class="zt ${s.z}">${s.zl}</span><h4>${s.t}</h4><p class="pdesc"></p><div class="barmini"><i></i></div></div></div>`).join("")}</div>
    <div class="pipe-foot"><div class="progress"><i id="pipeProg"></i></div><span class="mono" style="font-size:12px;color:var(--muted)" id="pipePct">0%</span></div>
  </div></div></div>`;}

async function analyzeStream(body,onStage,onDone,onError){
  let resp;
  try{resp=await fetch("/api/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});}
  catch(e){onError({message:"could not reach the local runtime"});return;}
  const reader=resp.body.getReader(),dec=new TextDecoder();let buf="",settled=false;
  const handle=msg=>{if(msg.event==="stage")onStage(msg.data);
    else if(msg.event==="done"){settled=true;onDone(msg.token);}
    else if(msg.event==="error"){settled=true;onError(msg);}};
  try{
    while(true){const {value,done}=await reader.read();if(done)break;buf+=dec.decode(value,{stream:true});
      let i;while((i=buf.indexOf("\n\n"))>=0){const chunk=buf.slice(0,i);buf=buf.slice(i+2);
        const line=chunk.replace(/^data: /,"");if(!line)continue;let msg;try{msg=JSON.parse(line);}catch(e){continue;}handle(msg);}}
  }catch(e){/* stream may end abruptly on the dev server; the token event already settled it */}
  if(!settled)onError({message:"the analysis stream ended unexpectedly"});
}
function runPipeline(body){
  root.insertAdjacentHTML("beforeend",pipelineView());
  const pipe=document.getElementById("pipe");
  const steps=[...pipe.querySelectorAll(".step")], dev=pipe.querySelector("#devTokens"), srv=pipe.querySelector("#srvTokens");
  const term=pipe.querySelector("#term"), prog=pipe.querySelector("#pipeProg"), pct=pipe.querySelector("#pipePct");
  const CIP=["a7f3d1","9c2104","e0b8af","4d5a72","b16f0e","72ce88"];
  const cipN=n=>CIP.slice(0,n).map(c=>`<span class="tok cipher">${c}…</span>`).join("");
  const plain=["Rent","Payroll","Groceries","Dining","Utilities"].map(t=>`<span class="tok plain">${t}</span>`).join("");
  const log=(cls,t)=>{const d=document.createElement("div");d.className="ln "+cls;d.textContent=t;term.appendChild(d);};
  let done=0;
  const advance=(key,ev)=>{
    const step=pipe.querySelector(`.step[data-k="${key}"]`); if(!step)return;
    steps.forEach(s=>s.classList.remove("active")); step.classList.add("active"); step.classList.add("done");
    step.querySelector("i").style.width="100%";
    const ms=ev.ms!=null?` · ${ev.ms} ms`:""; step.querySelector(".pdesc").textContent=(ev.detail||"")+ms;
    done++; prog.style.width=(done/7*100)+"%"; pct.textContent=Math.round(done/7*100)+"%";
    if(key==="read")dev.innerHTML=plain;
    if(key==="encrypt")dev.innerHTML=CIP.slice(0,5).map(c=>`<span class="tok cipher">${c}…</span>`).join("");
    if(key==="upload"){srv.innerHTML=cipN(5);log("up",`↑ uploaded ciphertext … ${(ev.bytes/1e6).toFixed(2)} MB`);}
    if(key==="compute"){srv.innerHTML=cipN(6);log("mut","· server: no secret key present");log("mut",`· ${ev.detail} · ${ev.ms} ms`);}
    if(key==="return"){log("up",`↓ returned encrypted result … ${(ev.bytes/1e6).toFixed(2)} MB`);srv.innerHTML=cipN(2);}
    if(key==="decrypt")dev.innerHTML=plain;
    if(key==="analytics")log("mut",`· built ${ev.detail}`);
  };
  const punch=()=>{const p=document.createElement("div");p.className="punch";
    p.innerHTML=`<div class="lock">🔒</div><div class="big">The server just computed your analytics —<br>and read <span style="color:var(--secure)">zero</span> of your transactions.</div>
    <div class="sub">Every number you're about to see was decrypted only here, on your device.</div>`;pipe.appendChild(p);};
  const fail=msg=>{const p=document.createElement("div");p.className="punch";
    p.innerHTML=`<div class="lock">⚠</div><div class="big" style="font-size:26px">We couldn't finish the analysis</div>
    <div class="sub">${esc(msg.message||"Something went wrong on this device.")}<br>Your data never left this machine — nothing was sent.</div>
    <div class="punch-cta"><button class="btn btn-primary btn-lg" data-act="home">Back to start</button>${S.csvText?'<button class="btn btn-ghost btn-lg" data-act="fail-retry">Adjust mapping</button>':''}</div>`;pipe.appendChild(p);};
  analyzeStream(body, ev=>advance(ev.stage,ev),
    async token=>{
      try{const r=await fetch("/api/result?token="+encodeURIComponent(token));S.result=await r.json();}
      catch(e){fail({message:"could not load the analytics result"});return;}
      S.token=S.result.token;const d=S.result.defaults;S.sel=d.dashboard_gm;S.cmpA=d.compare_a_gm;S.cmpB=d.compare_b_gm;S.countedOnce=false;
      punch(); setTimeout(()=>{pipe.remove();S.view="app";S.screen="dashboard";render();setTimeout(maybeCoach,900);}, reduceMotion()?400:1700);},
    msg=>fail(msg));
}

/* ---------------- app shell ---------------- */
const NAV=[["dashboard","Dashboard","▤"],["timeline","Timeline","▦"],["compare","Compare","⇄"],["insights","Insights","✦"]];
function shell(inner){const sv=DATA_SCREENS.includes(S.screen);
  return `<div class="shell"><aside class="sidebar"><div class="side-brand brand"><span class="glyph">◈</span> CipherSpend</div>
    ${NAV.map(([id,l,ic])=>`<button class="nav-item ${S.screen===id?'active':''}" data-nav="${id}"><span class="ic">${ic}</span>${l}</button>`).join("")}
    <div class="nav-sep"></div><button class="nav-item ${S.screen==='privacy'?'active':''}" data-nav="privacy"><span class="ic">🔒</span>Privacy</button>
    <button class="nav-item" data-act="home"><span class="ic">⌂</span>Start over</button></aside>
  <div class="main">${S.result&&S.result.source&&S.result.source.demo!==false&&S.isDemo?`<div class="demo-banner">Exploring demo data — a realistic sample account. <a data-act="upload">Use your own data</a></div>`:""}
    <div class="topbar">${S.screen==="dashboard"?monthSelect():`<strong style="font-size:15px">${(NAV.find(n=>n[0]===S.screen)||[,S.screen==='privacy'?'Privacy':''])[1]}</strong>`}
      <div class="spacer"></div>
      ${sv?`<button class="sv-toggle ${S.serverView?'on':''}" data-act="sv" aria-label="${S.serverView?'Exit server view':'See what the server sees'}"><span class="svt-ic" aria-hidden="true">${S.serverView?'✕':'👁'}</span><span class="svt-t">${S.serverView?'Exit server view':'See what the server sees'}</span></button>`:""}
      <button class="chip secure" data-nav="privacy" aria-label="Encrypted with your local key — open Privacy"><span class="chip-ic" aria-hidden="true">🔒</span><span class="chip-t">Encrypted · local key</span></button>
      <button class="iconbtn" data-act="theme" aria-label="Toggle theme">◐</button></div>
    <div class="boundary-line"></div>
    <div class="content ${S.serverView&&sv?'server-view':''}">${S.serverView&&sv?serverBanner():""}${inner}</div></div>
  <nav class="tabbar">${NAV.map(([id,l,ic])=>`<button class="${S.screen===id?'active':''}" data-nav="${id}"><span style="font-size:16px">${ic}</span>${l}</button>`).join("")}</nav></div>`;}
function monthSelect(){return `<span class="month-select">📅 <select data-sel>${R().months.map(m=>`<option value="${m.global_m}" ${m.global_m===S.sel?"selected":""}>${mlabel(m)}${m.complete?"":" · partial"}</option>`).join("")}</select></span>`;}

/* ---------------- consumer wording (presentation only — no analytics changes) ---------------- */
const DRIVER_PLAIN={
  "total spending level":"your overall spending",
  "income / cash flow":"your income and cash flow",
  "category mix":"a shift in where your money went",
  "fixed-cost load":"your fixed costs",
  "spending rhythm":"how evenly you spent through the month"};
function plainDriver(d){return DRIVER_PLAIN[d]||d;}
// Translate the story engine's technical headline into plain language. The raw
// technical phrasing (incl. any index/decimal) is returned as `tech` for the
// optional details toggle — never shown as the headline.
function plainHeadline(st){
  const raw=(st&&st.headline)||""; let m;
  const rose=/ rose /.test(raw);
  const strip=s=>s.replace(/ (rose|fell) /," ");
  if((m=/^Total spending (rose|fell) ([\d.]+%)/.exec(raw)))return {h:`Spending ${m[1]} ${m[2]}`,tech:null};
  if((m=/^Income (rose|fell) ([\d.]+%)/.exec(raw)))return {h:`Income ${m[1]} ${m[2]}`,tech:null};
  if((m=/^([A-Za-z]+) share (rose|fell) ([+\-][\d.]+ pp)/.exec(raw)))
    return {h:`${m[1]} took a ${m[2]==="rose"?"bigger":"smaller"} share of spending`,tech:`${m[1]} share ${m[3]}`};
  if(/^Cash-flow index/.test(raw))return {h:rose?"More of your income was left over":"Less of your income was left over",tech:strip(raw)};
  if(/^Weekly rhythm/.test(raw))return {h:rose?"Your spending was less even, week to week":"Your spending was steadier, week to week",tech:strip(raw)};
  if(/^Fixed-cost load/.test(raw))return {h:rose?"Fixed costs took a bigger share of spending":"Fixed costs took a smaller share of spending",tech:strip(raw)};
  if(/^Spending was stable/.test(raw))return {h:"A steady month — no big changes",tech:null};
  return {h:raw,tech:null};   // graceful fallback for any future template
}
function techDetails(text){return text?`<details class="techdet"><summary>Details</summary><span>${esc(text)}</span></details>`:"";}

/* ---------------- dashboard ---------------- */
function dashboard(){
  const m=monthByGm(S.sel); const prev=prevComplete(S.sel);
  const st=(R().month_stories||{})[String(S.sel)];
  const dNet=prev?m.metrics.net_cash_flow-prev.metrics.net_cash_flow:0;
  const dSpend=prev?m.metrics.total_spending-prev.metrics.total_spending:0;
  const dInc=prev?m.metrics.total_income-prev.metrics.total_income:0;
  const spend=completeMonths().map(x=>x.metrics.total_spending);
  const ph=st?plainHeadline(st):null;
  return `<div class="grid stagger" style="gap:18px">
    <div class="hero-card"><span class="eyebrow">${mlabel(m)}${m.complete?"":' · <span class="badge partial">◐ Partial</span>'}${prev?` · vs ${mlabel(prev)}`:""}</span>
      <h2>${ph?esc(ph.h):"Your first month is ready."}</h2>
      <p>${st&&st.source&&st.source.dominant?`The biggest driver was <b>${esc(plainDriver(st.source.driver))}</b>.`:"Spending held steady across your categories this month."}${m.complete?"":" This is a partial month, excluded from trends and baselines."}</p>${ph?techDetails(ph.tech):""}</div>
    <div class="kpis">
      ${statMoney("Net cash flow",m.metrics.net_cash_flow,prev?dNet:null)}
      ${statMoney("Total spending",m.metrics.total_spending,prev?dSpend:null)}
      ${statMoney("Total income",m.metrics.total_income,prev?dInc:null)}
      ${statPct("Savings rate",m.metrics.savings_rate)}</div>
    <div class="two-col"><div class="card hoverable"><h3>Where it went</h3><div class="cap">${mlabel(m)} · by category</div>${rankedBar(m)}</div>
      <div style="display:flex;flex-direction:column;gap:16px">
        <div class="card hoverable"><h3>Cash flow</h3><div class="cap">how much money came in vs. went out</div>${gauge(m.metrics.cash_flow_index)}
          <div class="svd" style="font-size:13px;color:var(--secondary);margin-top:8px">${m.metrics.net_cash_flow>=0?"Net positive this month — more came in than went out":"Net negative this month — more went out than came in"}</div>${m.metrics.cash_flow_index.defined?techDetails(`Cash-flow index ${sgn(m.metrics.cash_flow_index.value)} (−1 outflow … +1 inflow)`):""}</div>
        <div class="card hoverable"><h3>Where spending is spread</h3><div class="cap">across your categories</div>${meter(m.metrics.concentration_hhi.normalized,"Concentration",(m.metrics.concentration_hhi.normalized||0)<.35?"Spread widely across categories":"Concentrated in a few categories")}</div></div></div>
    <div><div class="eyebrow" style="margin-bottom:11px">What changed${prev?` vs ${mlabel(prev)}`:""}</div><div class="insight-row">
      ${st&&st.cards.length?st.cards.map(c=>`<div class="insight"><div class="k">Category change</div><h4>${esc(c.title)}</h4><p>${esc(c.detail)}</p></div>`).join(""):`<div class="insight"><div class="k">Stable</div><h4>No large category shifts</h4><p>Every category stayed within the reporting threshold.</p></div>`}
      ${st?`<div class="insight"><div class="k">Source of change</div><h4>${st.source.dominant?"Driven by "+esc(plainDriver(st.source.driver)):"No single driver"}</h4><p>${st.source.dominant?"The largest single factor behind this month's change.":"Everything changed within the reporting floor."}</p>${st.source.dominant?techDetails(`Largest normalized component: ${st.source.driver} (${st.source.val.toFixed(3)})`):""}</div>`:""}</div></div>
    ${completeMonths().length>=2
      ? `<div class="card hoverable"><div style="display:flex;justify-content:space-between;align-items:center"><div><h3>Spending over time</h3><div class="cap" style="margin:0">${completeMonths().length} complete months</div></div><button class="btn btn-quiet" data-nav="timeline">Full timeline →</button></div><div style="margin-top:14px">${sparkline(spend)}</div></div>`
      : `<div class="card"><h3>Spending over time</h3><div class="cap" style="margin:0">${completeMonths().length} complete month${completeMonths().length===1?"":"s"} so far</div><p style="font-size:13.5px;color:var(--secondary);margin:12px 0 0">Add another complete calendar month to see your spending trend, month-over-month changes, and comparisons.</p></div>`}
    </div>`;
}
function statMoney(lbl,val,delta){const d=delta||0;const dl=delta==null?"":`<div class="delta ${dirCls(d)}">${arrow(d)} ${d>=0?"+":"−"}${fmt(Math.abs(d))} vs last</div>`;
  return `<div class="stat"><div class="lbl">${lbl}</div><div class="fig money" data-count="${val}" data-fmt="money">${fmt(val)}</div>${dl}</div>`;}
function statPct(lbl,g){return `<div class="stat"><div class="lbl">${lbl}</div><div class="fig money" ${g.defined?`data-count="${g.value}" data-fmt="pct"`:""}>${gv(g,pct)}</div><div class="delta flat">of income</div></div>`;}

/* ---------------- timeline ---------------- */
function timeline(){
  const cm=completeMonths(); const tr=R().timeline.trends;
  if(cm.length<2)return `<div class="page-head"><h1>Timeline</h1><p>Trends need at least two complete calendar months.</p></div>
    <div class="emptybox"><div class="eb-icon">▦</div><h3>${cm.length===0?"No complete months yet":"Just one complete month so far"}</h3>
      <p>${cm.length===0?"Only partial months are in view — trends and baselines need at least one full calendar month.":"Add another complete month and your spending, savings, and cash-flow trends will appear here."}</p>
      <div class="eb-cta"><button class="btn btn-primary" data-nav="dashboard">Back to dashboard</button><button class="btn btn-ghost" data-act="upload">Add more data</button></div></div>`;
  const spread=v=>v<0.15?"Very spread out":v<0.25?"Spread out":v<0.4?"Somewhat focused":"Concentrated";
  const specs=[
    {name:"Savings rate",key:"savings_rate",fig:pct,tech:null,mono:true},
    {name:"Cash flow",key:"cash_flow_index",fig:v=>v>0.02?"Money left over":v<-0.02?"Spent more than earned":"Roughly even",tech:v=>`Cash-flow index ${sgn(v)}`,mono:false},
    {name:"Discretionary spending",key:"discretionary_ratio_of_spend",fig:pct,tech:null,mono:true},
    {name:"Spending spread",key:"concentration_hhi",fig:spread,tech:v=>`HHI ${v.toFixed(2)}`,mono:false}];
  return `<div class="page-head"><h1>Timeline</h1><p>Your spending shape across ${cm.length} complete months. Hover the chart to scrub any month. Partial months are excluded.</p></div>
    <div class="rail">${R().months.map(m=>`<button class="${m.global_m===S.sel?'active':''}" data-sel="${m.global_m}">${MN[m.month-1]} '${String(m.year).slice(2)}${m.complete?"":'<span class="pdot"></span>'}</button>`).join("")}</div>
    <div class="card hoverable" style="margin-bottom:16px"><h3>Needs, wants & income over time</h3><div class="cap">essential vs discretionary spending, with income</div>
      <div class="tl-legend" style="margin-top:12px"><span><i style="background:var(--c-ess)"></i>Essential</span><span><i style="background:var(--c-disc)"></i>Discretionary</span><span><i style="background:var(--ink);height:3px;border-radius:2px"></i>Income</span></div>
      <div class="tl-hero" id="tlHero">${stackedArea()}<div class="tl-guide" id="tlGuide" style="left:0"></div></div><div class="tl-read" id="tlRead"></div></div>
    <div class="sm-grid stagger">${specs.map(sp=>{const t=tr[sp.key]||{series:[],summary:{}};const vals=t.series.map(p=>p.value==null?0:p.value);
      const last=t.summary.last, dir=t.summary.direction||"flat";
      return `<div class="card sm hoverable"><div class="top"><div><div class="cap" style="margin:0">${sp.name}</div><div class="cur${sp.mono?" money":""}">${last==null?"—":sp.fig(last)}</div></div><span class="dir ${dir}">${dir}</span></div>${sparkline(vals,320,58)}${last!=null&&sp.tech?techDetails(sp.tech(last)):""}</div>`;}).join("")}</div>`;
}
function stackedArea(){
  const cm=completeMonths(),n=cm.length,ei=essIdx(),di=discIdx();
  const ess=cm.map(m=>ei.reduce((s,i)=>s+m.raw.category_sums[i],0));
  const disc=cm.map(m=>di.reduce((s,i)=>s+m.raw.category_sums[i],0));
  const inc=cm.map(m=>m.metrics.total_income);
  const maxY=Math.max(...cm.map(m=>m.raw.total_spending),...inc,1)*1.08;
  const W=760,H=230,pL=6,pR=6,pB=22,pT=8,iw=W-pL-pR,ih=H-pT-pB;
  const X=k=>pL+(n<=1?iw/2:k/(n-1)*iw),Y=v=>pT+ih-v/maxY*ih;
  const discTop=cm.map((_,k)=>ess[k]+disc[k]);
  const areaTo=(top,bot)=>{let d="M "+X(0)+" "+Y(bot(0));for(let k=0;k<n;k++)d+=" L "+X(k).toFixed(1)+" "+Y(top[k]).toFixed(1);for(let k=n-1;k>=0;k--)d+=" L "+X(k).toFixed(1)+" "+Y(bot(k)).toFixed(1);return d+" Z";};
  const line=arr=>arr.map((v,k)=>(k?"L":"M")+X(k).toFixed(1)+" "+Y(v).toFixed(1)).join(" ");
  const labels=cm.map((m,k)=>`<text x="${X(k).toFixed(1)}" y="${H-6}" text-anchor="middle" style="fill:var(--muted);font-size:9px;font-family:var(--font-sans)">${MN[m.month-1]}</text>`).join("");
  return `<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none" style="width:100%;height:230px;display:block">
    <path d="${areaTo(ess,()=>0)}" style="fill:var(--c-ess)" opacity=".55"/><path d="${areaTo(discTop,k=>ess[k])}" style="fill:var(--c-disc)" opacity=".5"/>
    <path d="${line(inc)}" style="fill:none;stroke:var(--ink)" stroke-width="2" stroke-linejoin="round"/>${labels}</svg>`;
}
function initTimelineScrub(){
  const hero=document.getElementById("tlHero"),guide=document.getElementById("tlGuide"),read=document.getElementById("tlRead");
  if(!hero||!read)return;const cm=completeMonths(),n=cm.length,ei=essIdx(),di=discIdx();
  const upd=k=>{k=Math.max(0,Math.min(n-1,k));const m=cm[k];
    const e=ei.reduce((s,i)=>s+m.raw.category_sums[i],0),d=di.reduce((s,i)=>s+m.raw.category_sums[i],0);
    guide.style.left=(n<=1?50:k/(n-1)*100)+"%";
    read.innerHTML=`<div class="rd"><div class="l">${mlabel(m)}</div><div class="v" style="font-size:13px;color:var(--muted)">${m.days_in_month} days</div></div>
      <div class="rd"><div class="l">Essential</div><div class="v" style="color:var(--c-ess)">${fmt(e)}</div></div>
      <div class="rd"><div class="l">Discretionary</div><div class="v" style="color:var(--c-disc)">${fmt(d)}</div></div>
      <div class="rd"><div class="l">Income</div><div class="v">${fmt(m.metrics.total_income)}</div></div>
      <div class="rd"><div class="l">Net</div><div class="v" style="color:${m.metrics.net_cash_flow>=0?'var(--pos)':'var(--neg)'}">${m.metrics.net_cash_flow>=0?"+":"−"}${fmt(Math.abs(m.metrics.net_cash_flow))}</div></div>`;};
  hero.onpointermove=e=>{const r=hero.getBoundingClientRect();upd(Math.round((e.clientX-r.left)/r.width*(n-1)));};
  upd(n-1);
}

/* ---------------- compare ---------------- */
function simVerdict(cos){if(cos==null)return["—",""];if(cos>=.985)return["Nearly identical","almost the same spending shape across both months"];
  if(cos>=.94)return["Broadly similar","the overall pattern held, with a few shifts"];if(cos>=.82)return["Noticeably different","the mix of where money went changed"];return["Very different","money was distributed quite differently"];}
function comparePage(){
  const cm=completeMonths();
  if(cm.length<2)return `<div class="page-head"><h1>Compare</h1><p>Comparisons need at least two complete calendar months.</p></div>
    <div class="emptybox"><div class="eb-icon">⇄</div><h3>${cm.length===0?"No complete months to compare":"Only one complete month so far"}</h3>
      <p>${cm.length===0?"Only partial months are in view. A comparison needs two full calendar months.":"Add a second complete month and you'll be able to compare any two side by side."}</p>
      <div class="eb-cta"><button class="btn btn-primary" data-nav="dashboard">Back to dashboard</button><button class="btn btn-ghost" data-act="upload">Add more data</button></div></div>`;
  const opts=sel=>cm.map(m=>`<option value="${m.global_m}" ${m.global_m===sel?"selected":""}>${mlabel(m)}</option>`).join("");
  const c=S.cmpData;
  let body;
  if(c&&c.error){body=`<div class="card">Couldn't load this comparison — try two different months.</div>`;}
  else if(!c){body=`<div class="card">Loading comparison…</div>`;}
  else{const cos=c.cosine&&c.cosine.defined?c.cosine.value:null;const v=simVerdict(cos);const pv=cos!=null?Math.round(cos*100):0;
    body=`<div class="card hoverable" style="margin-bottom:16px"><div class="verdict"><div class="ring" style="--p:${pv}"><b>${pv}%</b></div>
      <div><div class="vt">${v[0]}</div><div class="vs">${v[1]}</div><div class="meta">${pv}% of the spending pattern held${c.involves_partial?" · one side is a partial month":""}${techDetails(`cosine ${cos==null?"—":cos.toFixed(3)} · distance ${c.euclidean&&c.euclidean.defined?c.euclidean.value.toFixed(3):"—"}`)}</div></div></div></div>
      <div class="card hoverable"><h3>What moved, category by category</h3><div class="cap">share of spending, ${niceMonth(c.from)} → ${niceMonth(c.to)} · sorted by biggest change</div>${dumbbell(c)}</div>`;}
  return `<div class="page-head"><h1>Compare</h1><p>How two periods line up — computed locally, after decryption.</p></div>
    <div class="pickers"><select data-cmp="A">${opts(S.cmpA)}</select><span style="color:var(--muted)">→</span><select data-cmp="B">${opts(S.cmpB)}</select></div>${body}`;
}
async function loadCompare(){
  if(S.cmpLoading)return; S.cmpLoading=true;   // guard against render->fetch loops
  try{const r=await fetch("/api/compare",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token:S.token,a:S.cmpA,b:S.cmpB})});
    if(!r.ok)throw new Error("compare "+r.status);S.cmpData=await r.json();}
  catch(e){S.cmpData={error:true};}
  S.cmpLoading=false; if(S.screen==="compare")render();
}

/* ---------------- insights ---------------- */
function insights(){
  const ms=R().month_stories||{}; const cm=completeMonths().slice().reverse();
  const feed=cm.filter(m=>ms[String(m.global_m)]).slice(0,6);
  return `<div class="page-head"><h1>Your monthly briefing</h1><p>A calm, factual read of what changed each month — a mirror, not a nudge. No advice, no motives.</p></div>
    <div class="grid stagger" style="gap:16px">${feed.map(m=>{const st=ms[String(m.global_m)];const ph=plainHeadline(st);
      return `<div class="card hoverable"><span class="eyebrow" style="color:var(--acc-ink)">${mlabel(m)} · vs ${niceMonth(st.from)}</span>
      <h3 style="font-size:19px;margin-top:8px">${esc(ph.h)}</h3>
      <div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:14px">${st.cards.slice(0,2).map(c=>`<div style="padding:12px 14px;background:var(--sunken);border-radius:var(--r-sm)"><div style="font-size:12.5px;font-weight:650">${esc(c.title)}</div><div style="font-size:12px;color:var(--secondary);margin-top:3px">${esc(c.detail)}</div></div>`).join("")}</div>
      <p style="font-size:13px;color:var(--secondary);margin:14px 0 0">Source of change: <b style="color:var(--ink)">${st.source.dominant?esc(plainDriver(st.source.driver)):"no single driver"}</b>${st.stable.length?` · ${st.stable.length} categor${st.stable.length===1?"y":"ies"} stable`:""}.</p>${techDetails(ph.tech)}</div>`;}).join("")}</div>`;
}

/* ---------------- privacy ---------------- */
function privacyPage(){
  const p=R()?R().pipeline:{ciphertext_in_mb:"—"};
  const never=[["Your transaction amounts","every dollar figure stays encrypted end to end"],
    ["Your categories & merchants","the server never learns what you spent on, or where"],
    ["Dates & individual transactions","only fixed-shape encrypted aggregates are computed"],
    ["Your private key","generated on your device; it never leaves"],
    ["Any readable result","outputs come back encrypted; only your device unlocks them"]];
  const does=[[`The size of the encrypted data`,`~${p.ciphertext_in_mb} MB of ciphertext this run — reveals nothing about contents`],
    ["How many monthly batches","a coarse sense of history length — blurred by fixed-shape padding"],
    ["Timing","how long the computation ran — independent of your values"]];
  return `<div class="priv-hero"><span class="eyebrow">Privacy</span><h1>What the server can — and cannot — see</h1>
    <p>CipherSpend uses fully homomorphic encryption (FHE): the server computes your analytics directly on encrypted data and never holds the key to unlock it. Here's the honest, complete picture — including the little that does leak, and how we blur it.</p>
    <div style="margin-top:16px;display:flex;gap:10px;flex-wrap:wrap"><button class="btn btn-primary" data-act="sv-go">👁 See what the server sees</button></div></div>
  <div class="priv-cols"><div class="card"><h3 style="color:var(--secure)">🔒 Never leaves your device</h3><ul class="seelist">${never.map(([a,b])=>`<li class="never"><span class="mk">✓</span><span><b>${a}</b> — ${b}</span></li>`).join("")}</ul></div>
    <div class="card"><h3>👁 What the server does observe</h3><div class="cap" style="margin-top:2px">Shown openly — trust comes from precision, not hand-waving.</div><ul class="seelist">${does.map(([a,b])=>`<li class="does"><span class="mk">!</span><span><b>${a}</b> — ${b}</span></li>`).join("")}</ul></div></div>
  <div class="card" style="margin-top:16px"><h3>How it stays private</h3><div class="cap">measured this run</div>
    <div style="display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:6px">
      <div><div class="eyebrow">Scheme</div><div style="font-weight:640;margin-top:4px">CKKS · ring ${p.ring_dimension||65536}</div><p style="font-size:12.5px;color:var(--secondary);margin:4px 0 0">${p.security||"HEStd_128_classic"}, no bootstrapping</p></div>
      <div><div class="eyebrow">Ciphertext moved</div><div style="font-weight:640;margin-top:4px">${p.ciphertext_in_mb||"—"} MB up · ${p.ciphertext_out_mb||"—"} MB back</div><p style="font-size:12.5px;color:var(--secondary);margin:4px 0 0">blind aggregation only</p></div>
      <div><div class="eyebrow">Keys on server</div><div style="font-weight:640;margin-top:4px">Public + evaluation only</div><p style="font-size:12.5px;color:var(--secondary);margin:4px 0 0">the secret key is never uploaded</p></div></div>
    ${R()&&R().limitations?`<ul style="margin:16px 0 0;padding-left:18px;color:var(--muted);font-size:12px;line-height:1.9">${R().limitations.map(l=>`<li>${esc(l)}</li>`).join("")}</ul>`:""}</div>`;
}

/* ---------------- server view + cascade ---------------- */
function serverBanner(){return `<div class="sv-banner" role="note" aria-label="Server view">
  <span class="bi" aria-hidden="true">🔒</span><div>
  <h4>The server's-eye view</h4><p>Every value below is replaced with an illustrative stand-in for the ciphertext the server holds — a visual placeholder, not the real OpenFHE bytes, but nothing here is readable to the server or to a screen reader either way. The section titles and layout are drawn here on your device from your decrypted results; they are never sent to the server. Exit server view to see your figures.</p>
  <div class="meta">server holds: encrypted ciphertext only · ${R()&&R().pipeline?R().pipeline.ciphertext_in_mb:"~4"} MB · nothing readable</div></div></div>`;}
const SENS=".hero-card h2, .hero-card p, .stat .fig, .stat .delta, .bar-row .cat, .bar-row .val, .sm .cur, .verdict .vt, .verdict .vs, .verdict .meta, .dumb-cat, .dumb-delta, .meter .row b, .meter-note, .svd, .insight h4, .insight p, .tl-read .v";
function cipherStr(s){const clean=(s||"").replace(/\s+/g,"");const n=Math.max(3,Math.min(11,clean.length||4));
  const hex="0123456789abcdef";let seed=(0x9e3779b1^(clean.length*2654435761))>>>0;
  for(const c of (s||""))seed=(Math.imul(seed^c.charCodeAt(0),2654435761))>>>0;let o="";
  for(let i=0;i<n;i++){seed=(Math.imul(seed,1664525)+1013904223)>>>0;o+=hex[seed>>>28];}return o;}
function collectSensitive(rootEl){const set=new Set();rootEl.querySelectorAll(SENS).forEach(el=>set.add(el));
  const skip=el=>!el||el.closest(".sv-banner,.page-head,.eyebrow,h3,.cap,.zl,.rail,.month-select,.dir,.chip,.tl-legend,.dumb-legend,.verdict .ring");
  const walk=document.createTreeWalker(rootEl,NodeFilter.SHOW_TEXT);let nd;const extra=[];
  while(nd=walk.nextNode()){const t=nd.nodeValue;if(!/\d/.test(t)&&t.trim().replace(/\s/g,"").length<12)continue;
    const p=nd.parentElement;if(!p||p.classList.contains("sv-text")||skip(p)||set.has(p))continue;
    const span=document.createElement("span");span.textContent=nd.nodeValue;p.replaceChild(span,nd);extra.push(span);}
  extra.forEach(e=>set.add(e));return [...set].filter(el=>el.textContent.trim().length);}
function scrambleView(){const rootEl=document.querySelector(".content.server-view");if(!rootEl)return;
  // Obscure every sensitive value/interpretation, and hide the (fake) ciphertext
  // from assistive tech so screen readers hear the banner's explanation, not hex.
  collectSensitive(rootEl).forEach(el=>{el.textContent=cipherStr(el.textContent);el.classList.add("sv-text");el.setAttribute("aria-hidden","true");});
  // charts/bars/gauges carry no text but still visualize shape — hide from SR too.
  rootEl.querySelectorAll("svg, .gauge-wrap, .meter .track, .bar-track").forEach(el=>el.setAttribute("aria-hidden","true"));}
function runCascade(els){const GLY="0123456789abcdef";
  els.sort((a,b)=>{const ra=a.getBoundingClientRect(),rb=b.getBoundingClientRect();return (ra.top-rb.top)||(ra.left-rb.left);});
  const per=460,stag=22,t0=performance.now();els.forEach((el,i)=>{el._f=el.textContent;el._d=i*stag;});
  function frame(t){let done=true;els.forEach(el=>{const e=(t-t0)-el._d,fin=el._f,L=fin.length;
    if(e<0){done=false;let s="";for(let k=0;k<L;k++)s+=/[0-9a-zA-Z]/.test(fin[k])?GLY[(Math.random()*16)|0]:fin[k];el.textContent=s;return;}
    const p=Math.min(1,e/per);if(p<1){done=false;const lock=Math.floor(p*L);let s=fin.slice(0,lock);
      for(let k=lock;k<L;k++)s+=/[0-9a-zA-Z]/.test(fin[k])?GLY[(Math.random()*16)|0]:fin[k];el.textContent=s;}else el.textContent=fin;});
    if(!done)requestAnimationFrame(frame);}requestAnimationFrame(frame);}
function toggleServerView(on){const going=on!==undefined?on:!S.serverView;S.serverView=going;
  if(!DATA_SCREENS.includes(S.screen))S.screen="dashboard";render();
  if(reduceMotion())return;const rootEl=document.querySelector(".content");if(!rootEl)return;
  const els=going?[...rootEl.querySelectorAll(".sv-text")]:collectSensitive(rootEl);runCascade(els.filter(e=>e.textContent.trim().length));}

/* ---------------- polish ---------------- */
function animateCounts(){if(reduceMotion())return;document.querySelectorAll("[data-count]").forEach(el=>{const target=+el.dataset.count,ft=el.dataset.fmt,t0=performance.now(),dur=460;
  function step(t){const p=Math.min(1,(t-t0)/dur),e=1-Math.pow(1-p,3),v=target*e;el.textContent=ft==="money"?fmt(v):ft==="pct"?pct(v):v.toFixed(0);if(p<1)requestAnimationFrame(step);}requestAnimationFrame(step);});}
function maybeCoach(){if(S.coached||S.serverView||S.screen!=="dashboard")return;const btn=document.querySelector('[data-act="sv"]');if(!btn)return;
  S.coached=true;const r=btn.getBoundingClientRect();const c=document.createElement("div");c.className="coach";
  c.style.top=(r.bottom+10)+"px";c.style.left=Math.max(12,r.right-250)+"px";
  c.innerHTML=`<b>Curious what our servers see?</b><br>Flip this to watch your data turn to ciphertext.<br><button data-act="coach-x">Got it</button>`;document.body.appendChild(c);}

/* ---------------- render + events ---------------- */
function render(){
  document.querySelector(".coach")?.remove();
  if(S.view==="landing"){root.innerHTML=landing();return;}
  if(S.view==="onboard"){root.innerHTML=onboardView();return;}
  if(S.view==="upload"){root.innerHTML=uploadView();wireUpload();return;}
  if(S.view!=="app"||!S.result){root.innerHTML=landing();return;}
  let inner="";
  if(S.screen==="dashboard")inner=dashboard();
  else if(S.screen==="timeline")inner=timeline();
  else if(S.screen==="compare"){inner=comparePage();if(completeMonths().length>=2&&!S.cmpData&&!S.cmpLoading)loadCompare();}
  else if(S.screen==="insights")inner=insights();
  else if(S.screen==="privacy")inner=privacyPage();
  root.innerHTML=shell(inner);
  if(S.serverView&&DATA_SCREENS.includes(S.screen))scrambleView();
  else{if(S.screen==="dashboard"&&!S.countedOnce){S.countedOnce=true;animateCounts();}if(S.screen==="timeline")initTimelineScrub();}
}

async function ingestCsv(text){
  S.csvText=text;
  const msg=document.getElementById("filemsg"); if(msg)msg.textContent="Parsing on device…";
  let q;
  try{const r=await fetch("/api/inspect",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text})}); q=await r.json();}
  catch(e){if(msg)msg.textContent="Couldn't reach the local runtime."; return;}
  if(!q||!q.ok){if(msg)msg.textContent="Could not read that CSV — expected a comma-separated file with a header row."; return;}
  S.inspect=q;
  S.cfg={mapping:{...q.suggested_mapping}, sign_mode:q.suggested_sign,
    category_map:{...q.suggested_category_map}, type_map:{...q.suggested_type_map}, include_flagged:false,
    category_overrides:{}, excluded_merchants:[]};
  // keep only confident suggestions; unrecognized items stay empty so the user must choose (never a silent guess)
  for(const k in S.cfg.category_map)if(!S.cfg.category_map[k])delete S.cfg.category_map[k];
  for(const k in S.cfg.type_map)if(!S.cfg.type_map[k])delete S.cfg.type_map[k];
  S.cfg.auto_categorize=!S.cfg.mapping.category;   // no category column → categorize locally from descriptions
  S.cfg.client_categories={};
  await classifyInBrowser(q);                      // run the on-device model over merchant descriptions
  S.reviewCols=false; S.reviewCats=false; S.reviewTypes=false;
  S.uploadStep="map"; render();
}
// Classify unique merchant descriptions IN THE BROWSER with the local model. The
// raw descriptions never leave the device; results feed the backend as client
// categories (parity-verified against the Python reference).
async function classifyInBrowser(q){
  if(!S.cfg.auto_categorize || !(q.descriptions&&q.descriptions.length))return;
  await ensureModel();
  if(!(window.CipherCategorizer&&CipherCategorizer.ready()))return;   // backend model is the fallback
  const t0=performance.now();
  const map=CipherCategorizer.classifyMany(q.descriptions);
  const out={};
  for(const k in map){const r=map[k]; out[k]={category:r.category, confidence:r.confidence, model_stage:r.model_stage};}
  S.cfg.client_categories=out;
  S.cfg._catms=Math.round(performance.now()-t0);
}
// Re-derive category/type values from the user's CURRENTLY chosen columns, so a
// column the importer didn't auto-detect (e.g. a category column named "Label")
// surfaces its values for mapping instead of being silently left empty.
async function reinspect(){
  collectMapForm();
  let q;
  try{const r=await fetch("/api/inspect",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:S.csvText,mapping:S.cfg.mapping})}); q=await r.json();}
  catch(e){return;}
  if(!q||!q.ok)return;
  const oldCat=S.cfg.category_map||{}, oldType=S.cfg.type_map||{};
  S.inspect=q;
  // preserve the user's existing choices for values that still exist; auto-confirm newly-recognized ones
  const cat={}; for(const c of q.categories){const v=oldCat[c]||q.suggested_category_map[c]; if(v)cat[c]=v;}
  const typ={}; for(const t of q.types){const v=oldType[t]||q.suggested_type_map[t]; if(v)typ[t]=v;}
  S.cfg.category_map=cat; S.cfg.type_map=typ;
  S.cfg.auto_categorize=!S.cfg.mapping.category;   // recompute after a column change
  render();
}
function acceptFile(file){
  const msg=document.getElementById("filemsg");
  if(!file)return;
  if(file.name&&!/\.csv$/i.test(file.name)&&!(file.type&&/csv|text/.test(file.type))){
    if(msg)msg.textContent="That doesn't look like a .csv — please choose a CSV export."; return;}
  file.text().then(ingestCsv).catch(()=>{if(msg)msg.textContent="Couldn't read that file.";});
}
function wireUpload(){
  const f=document.getElementById("csvfile"); if(!f)return;
  f.addEventListener("change",e=>acceptFile(e.target.files[0]));
  const dz=document.getElementById("dropzone"); if(!dz)return;
  const open=()=>f.click();
  dz.addEventListener("click",e=>{if(e.target.closest("a"))return; open();});
  dz.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();open();}});
  ["dragenter","dragover"].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();e.stopPropagation();dz.classList.add("drag");}));
  ["dragleave","dragend"].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();e.stopPropagation();if(e.target===dz)dz.classList.remove("drag");}));
  dz.addEventListener("drop",e=>{e.preventDefault();e.stopPropagation();dz.classList.remove("drag");
    const file=e.dataTransfer&&e.dataTransfer.files&&e.dataTransfer.files[0]; acceptFile(file);});
}
function collectMapForm(){
  document.querySelectorAll("[data-map]").forEach(s=>S.cfg.mapping[s.dataset.map]=s.value||null);
  document.querySelectorAll("[data-catmap]").forEach(s=>{if(s.value)S.cfg.category_map[s.dataset.catmap]=s.value;else delete S.cfg.category_map[s.dataset.catmap];});
  document.querySelectorAll("[data-typemap]").forEach(s=>{if(s.value)S.cfg.type_map[s.dataset.typemap]=s.value;else delete S.cfg.type_map[s.dataset.typemap];});
  const fl=document.querySelector("[data-flagged]");if(fl)S.cfg.include_flagged=fl.checked;
}

document.addEventListener("click",e=>{
  if(e.target.classList.contains("sheet-bg")){closeLearnSheet();return;}   // click backdrop to close
  const t=e.target.closest("[data-act],[data-nav],[data-sign]");
  const rail=e.target.closest(".rail button[data-sel]");
  if(rail){S.sel=+rail.dataset.sel;render();return;}
  if(!t)return;
  const {act,nav,sign}=t.dataset;
  if(sign){collectMapForm();S.cfg.sign_mode=sign;render();return;}
  if(nav){S.screen=nav;S.serverView=false;
    if(nav==="compare"){S.cmpA=R().defaults.compare_a_gm;S.cmpB=R().defaults.compare_b_gm;S.cmpData=R().default_compare||null;}
    render();return;}
  switch(act){
    case"theme":toggleTheme();break;
    case"home":clearTimeout(S.keygenTimer);S.view="landing";S.result=null;S.token=null;S.serverView=false;render();break;
    case"learn":openLearnSheet();break;
    case"upload":startOnboarding();break;
    case"onboard-continue":gotoUpload();break;
    case"sheet-close":closeLearnSheet();break;
    case"demo":S.isDemo=true;runPipeline({mode:"demo"});break;
    case"do-preview":{collectMapForm();
      fetch("/api/preview",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:S.csvText,cfg:S.cfg})})
        .then(r=>r.json()).then(p=>{S.preview=p;S.uploadStep="preview";render();});break;}
    case"back-map":S.uploadStep="map";render();break;
    case"fail-retry":document.getElementById("pipe")?.remove();S.view="upload";S.uploadStep="map";render();break;
    case"review-cols":collectMapForm();S.reviewCols=!S.reviewCols;render();break;
    case"review-cats":collectMapForm();S.reviewCats=!S.reviewCats;render();break;
    case"review-types":collectMapForm();S.reviewTypes=!S.reviewTypes;render();break;
    case"do-analyze":S.isDemo=false;runPipeline({mode:"upload",text:S.csvText,cfg:S.cfg});break;
    case"sv":toggleServerView();break;
    case"sv-go":S.screen="dashboard";toggleServerView(true);break;
    case"coach-x":document.querySelector(".coach")?.remove();break;
  }
});
document.addEventListener("change",e=>{
  if(e.target.dataset.review!==undefined){                    // categorize-review decision for a merchant
    const key=e.target.dataset.review, val=e.target.value;
    S.cfg.category_overrides=S.cfg.category_overrides||{};
    S.cfg.excluded_merchants=(S.cfg.excluded_merchants||[]).filter(k=>k!==key);
    delete S.cfg.category_overrides[key];
    if(val==="__exclude__")S.cfg.excluded_merchants.push(key);
    else if(val)S.cfg.category_overrides[key]=val;
    rePreview(); return;
  }
  if(e.target.dataset.map!==undefined){reinspect();return;}   // column changed → re-derive its values
  if(e.target.dataset.sel!==undefined&&e.target.tagName==="SELECT"){S.sel=+e.target.value;render();}
  if(e.target.dataset.cmp==="A"){S.cmpA=+e.target.value;S.cmpData=null;render();}
  if(e.target.dataset.cmp==="B"){S.cmpB=+e.target.value;S.cmpData=null;render();}
});
document.addEventListener("keydown",e=>{if(e.key==="Escape")closeLearnSheet();});
render();
