// Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
// On-device (in-browser) merchant classifier. Loads the exported char-ngram linear
// model (categorizer.json) from the LOCAL app and runs inference in pure JS — no
// model download beyond the local asset, instant cold-start, ZERO external network.
// Mirrors app/categorize_model.py (canonicalize + features) and app/categorize.py
// (scoring) exactly, so browser results match the Python reference.
"use strict";
const CipherCategorizer = (() => {
  let M = null;                      // {categories, vocab:Map, coef, intercept, rules, rule_bonus}
  const HIGH = 0.70, MED = 0.45;

  async function load(url = "/categorizer.json") {
    const m = await (await fetch(url)).json();       // served from localhost only
    const vocab = new Map();
    m.vocab.forEach((g, i) => vocab.set(g, i));
    M = {categories: m.categories, vocab, coef: m.coef, intercept: m.intercept,
         rules: m.rules, rule_bonus: m.rule_bonus || 2.3, size: JSON.stringify(m).length};
    return {features: m.vocab.length, categories: m.categories.length, bytes: M.size};
  }
  const ready = () => M !== null;

  // --- canonical merchant extraction (mirror of categorize_model.canonicalize) ---
  function canonicalize(desc) {
    let s = (desc || "").toLowerCase();
    s = s.replace(/\*/g, " ").replace(/#/g, " ").replace(/\//g, " ");
    s = s.replace(/https?:\/\/|www\./g, " ");
    s = s.replace(/\b([a-z][a-z0-9\-]{2,})\.(?:com|net|org|io|co|es|de|fr|mx|uk|it|pt|eu)\b/g, "$1");
    s = s.replace(/\b(?:\+?\d[\d\-.() ]{6,}\d)\b/g, " ");
    s = s.replace(/\d{1,2}[\-/]\d{1,2}(?:[\-/]\d{2,4})?/g, " ");
    s = s.replace(/\b[a-z]*\d{3,}[a-z0-9]*\b/g, " ");
    s = s.replace(/[^a-zÀ-ſ ]+/g, " ");
    s = s.replace(/\b(pos|debit|credit|card|purchase|payment|pmt|ach|ppd|des|id|ref|recurring|trans|transaction|auth|authorized|online|web|recur|bill|billpay|checkcard|ckcd|visa|mastercard|amex|xxxx|usd|eur|gbp|mxn|the|inc|llc|ltd|co|corp|sa|gmbh|srl|bv|of|and)\b/g, " ");
    s = s.replace(/\b(a[klrz]|c[aot]|d[ce]|fl|ga|hi|i[adln]|k[sy]|la|m[adeinost]|n[cdehjmvy]|o[hkr]|pa|ri|s[cd]|t[nx]|ut|v[at]|w[aivy])\b/g, " ");
    return s.replace(/\s+/g, " ").trim();
  }

  // --- word-boundary char n-grams 3-5 (mirror of categorize_model.features) ---
  function features(canonical) {
    const s = " " + (canonical || "").replace(/\s+/g, " ").trim() + " ";
    const out = new Set();
    if (s === "  ") return out;
    for (const n of [3, 4, 5]) {
      for (let i = 0; i + n <= s.length; i++) {
        const g = s.slice(i, i + n);
        if (g.trim() !== "") out.add(g);
      }
    }
    return out;
  }

  function softmax(a) { const m = Math.max(...a); const e = a.map(v => Math.exp(v - m)); const s = e.reduce((x, y) => x + y, 0); return e.map(v => v / s); }

  // --- classify one description -> {category, confidence, short_reason, model_stage} ---
  function classify(desc) {
    if (!M) throw new Error("model not loaded");
    const canon = canonicalize(desc);
    const idx = []; for (const g of features(canon)) { const j = M.vocab.get(g); if (j !== undefined) idx.push(j); }
    const logits = M.intercept.slice();
    for (let c = 0; c < M.categories.length; c++) { const row = M.coef[c]; let s = 0; for (const j of idx) s += row[j]; logits[c] += s; }
    let ruleHit = null;
    for (const tok of canon.split(" ")) { const cat = M.rules[tok]; if (cat && M.categories.includes(cat)) { logits[M.categories.indexOf(cat)] += M.rule_bonus; ruleHit = tok; } }
    const probs = softmax(logits);
    let top = 0; for (let i = 1; i < probs.length; i++) if (probs[i] > probs[top]) top = i;
    const cat = M.categories[top], conf = probs[top];
    const stage = ruleHit ? "rules+classifier" : "classifier";
    const reason = ruleHit ? `matches '${ruleHit}' + spending patterns` : `closest to ${cat.toLowerCase()} spending patterns`;
    return {category: cat, confidence: Math.round(conf * 1000) / 1000, short_reason: reason,
            model_stage: stage, canonical: canon, uncertain: conf < MED, flagged: conf < HIGH, key: canon};
  }

  // classify a list of unique descriptions -> {canonicalKey: result}
  function classifyMany(descs) {
    const map = {};
    for (const d of descs) { const r = classify(d); map[r.key] = r; }
    return map;
  }

  return {load, ready, canonicalize, features, classify, classifyMany, HIGH, MED};
})();
if (typeof module !== "undefined") module.exports = CipherCategorizer;
